pypa/setuptools

changelog.d/3072.misc.rst, pkg_resources/_vendor/jaraco/text/__init__.py, setup.py, tools/vendored.py
=> Remove lorem_ipsum from jaraco.text when vendored.

CHANGES.rst, changelog.d/2897.docs.rst, changelog.d/3034.docs.rst, changelog.d/3056.docs.rst, tools/finalize.py
This change address partially #3076.
The following tasks are handled:
- Locating the releases pertinent to those entries.
- Rendering those entries into the appropriate release.
Instead of writing a check that fails if any files are left in the `chagelog.d` directory after `tox -e finalize`, I reworked the existing `check_changes` function.
Previously, this function would check if the file name has one of the allowed substrings. While this check is useful it is not fail-proof. For example, a file named `9999.docs.rst` has the valid `doc` substring so it would pass the check, but it would still be an invalid name.
[PR docs]: …
=> Consolidate lingering news fragments named 'docs' 

.github/workflows/ci-sage.yml
=> Add integration testing with python from Debian, Ubuntu, Fedora, Gentoo, Arch Linux, OpenSUSE, Slackware

.github/workflows/main.yml
Uses [concurrency to cancel any in-progress job or run](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-concurrency-to-cancel-any-in-progress-job-or-run) to help address #3093
Closes 
[PR docs]:
=> Using concurrency to cancel any in-progress job or run

.github/workflows/main.yml
=> Limit tests for stdlib distutils to one job.

changelog.d/3103.misc.rst, setuptools/_entry_points.py
- Add test for loading entry points from a string. Ref #3103.
- Fix issue where string-based entry points would be omitted. Fixes #3103.
Closes #3103
[PR docs]:
=> Restore entry points from string

setuptools/tests/test_build_meta.py, tox.ini
As discussed in #3087, `test_build_meta` seems to be flaky specially for the combination of Windows + PyPy.
This is a proposed workaround for such scenarios.
- Added a timeout for the process pool executor
- Added a env var to control the timeout (useful for contributors with slower machines or network)
Closes 
[PR docs]:
=> Add timeout to `test_build_meta`

.github/workflows/main.yml
From times to times, tests (specially on PyPy) seem to get stuck and be cancelled by GitHub after the default timeout (6h).
Before these tests are cancelled, however they count as an active job and limit the amount of concurrent jobs/workflows PyPA's organization may have running.
Currently, the slowest job running for the `main` workflow seem to be the test for PyPy+Windows, which take around 55 min. Therefore, chances are that, if any test is taking much more than 1h to run, it got stuck.
We can be pragmatic and reduce the timeout for the `main` workflow and free the resources quickly.
[PR docs]:
https://setuptools.pypa.io/en/latest/development/developer-guide.html#ma …
=> Reduce GitHub Actions timeout from 6h to 75min

.github/workflows/main.yml, changelog.d/3093.misc.rst
This is an attempt to prevent the `release` job from being cancelled.
The problem was described in https://github.com/pypa/setuptools/pull/3097#issuecomment-1040377788 and https://github.com/pypa/setuptools/issues/3093#issuecomment-1041517254.
Add `github.ref_type` to the `concurrency.group`
According to the [docs](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) `github.ref_type` can be either `tag` or `branch`, so my hope is that it should differentiate between a push to main and a new tag, but I don't know how to test that...
The drawback of this change is that the CI workflow will run twice for the commit being tagged (but I think that is not problematic, giving that tags are only created sporadically and the number of duplication will be very small) …
=> Tweak concurrency group for CI so `tag` is not cancelled by `push`

.codecov.yml, .github/workflows/main.yml, setup.cfg
Currently, CI jobs running on PyPy are (painfully) slow.
This seems to be a well know side effect of enabling coverage.
The change proposed here is to disable coverage on PyPy for both Windows and MacOS (which seem to be very slow).
Coverage for PyPy on Ubuntu is preserved because, while being slower than CPython, it is still OK-ish.
Hopefully tests running on PyPy/Ubuntu will include most of PyPy's specific corner cases.
[PR docs]:
=> Disable coverage on PyPy

changelog.d/3120.misc.rst, setuptools/tests/test_build_meta.py
In previous PRs, I have tried to improve the situation with tests being flaky on PyPy (specially via timeouts).
Still, there seems to be problems with `ProcessPoolExecutor`:
- https://github.com/pypa/setuptools/runs/5241255918?check_suite_focus=true#step:5:321
- https://github.com/pypa/setuptools/runs/5250475520?check_suite_focus=true#step:5:38
This might be related to the fact that `pytest-xdist` can struggle to run tests that use threads/processes themselves and that can be worse in PyPy. One alternative could be disabling `xdist` for PyPy (but I don't know how much longer the tests would take)
- Intercept `futures.process.BrokenProcessPool`/`MemoryError` on PyPy and `xfail`
Closes  …
=> [CI] Attempt to capture yet another common PyPy error

CHANGES.rst, changelog.d/3124.misc.rst, docs/conf.py
Currently, there are a series of links being incorrectly displayed in the CHANGELOG, for example:
- Improve regex in `docs/conf.py` to avoid accidentally matching `#<issue-number>` or PEP mentions.
- Extend matching of `pypa/<repo>#<issue>` and `pypa/<repo>@<commit>` to any PyPA repository (currently only distutils is supported).
- Manually convert some entries to make use of the improvements above.
[PR docs]:
=> [Docs] Fix incorrectly displayed links in CHANGELOG

setuptools/tests/test_build_meta.py
Everyday the combination Windows + PyPy on the CI surprises me with new and exciting ways of unexpectedly failing 😅
This time I found that an `OSError` or `PermissionError` might happen when running the process pool for the backend tests:
- https://github.com/pypa/setuptools/runs/5260647654?check_suite_focus=true#step:5:73
- https://github.com/pypa/setuptools/runs/5264625500?check_suite_focus=true#step:5:150
- Added `OSError` to the list of exceptions that will cause an `XFAIL` on PyPy.
[PR docs]:
=> [CI] XFAIL on OSError in `test_build_meta` for PyPy

changelog.d/3137.change.rst, setuptools/command/easy_install.py, setuptools/package_index.py
=> Use samefile from stdlib, supported on Windows since Python 3.2.

setuptools/command/easy_install.py, setuptools/package_index.py
In https://github.com/pypa/setuptools/pull/3137, the custom `samefile` checker was removed in favour of the function provided in the stdlib.
However stdlib's version of the function will fail if both files don't exist.
Therefore replacing it is causing the [tests to fail](https://github.com/pypa/setuptools/runs/5346375426?check_suite_focus=true).
- Make sure that file exist before doing the `samefile` comparison.
Closes 
[PR docs]:
=> Check for file existence before using `samefile`

changelog.d/3133.misc.rst, setuptools/tests/environment.py, setuptools/tests/fixtures.py
In specifically set environment like the build environment in Fedora, we noticed some of the tests running subprocesses were failing. Typically they didn't see the correct paths, leading to multiple `ModuleNotFoundError: No module named setuptools` and failed meta-tests in [`test_virtualenv`](https://github.com/pypa/setuptools/blob/main/setuptools/tests/test_virtualenv.py#L95) (`DID NOT RAISE...`).
The changes: passing the copy of the environment minus PYTHONPATH for the subprocesses made the test suite pass during our builds.
[PR docs]:
=> Tests using virtual environments: pass the copy of existing env to the subprocesses

changelog.d/3148.doc.1.rst, changelog.d/3148.doc.2.rst, docs/conf.py, docs/setuptools.rst, docs/userguide/datafiles.rst, docs/userguide/miscellaneous.rst, docs/userguide/quickstart.rst
Using `MANIFEST.in` and adding non-Python files seems to be one of the most difficult aspects that beginners face when getting started with `setuptools`, as evidenced by a recent comment in https://github.com/pypa/packaging-problems/issues/84#issuecomment-1057750930.
The current docs also lack an explanation for the syntax of `MANIFEST.in` that is not bundled together with the deprecated/distutils documentation.
- Add links to the PyPUG instructions about using ``MANIFEST.in`` to existing docs,
- Mention more prominently VCS plugins as a viable alternative to ``MANIFEST.in``
- Add a section to ``miscellaneous.rst`` about how to control files in the distribution that also links to the PyPUG document about ``MANIFEST.in``.
- This new section also emphasize the usage of VCS plugins before …
=> [Docs] Improve mentions to `MANIFEST.in` and instructions for including data files

changelog.d/2887.change.1.rst, changelog.d/2887.change.2.rst, changelog.d/3068.change.rst, changelog.d/3152.change.rst, docs/userguide/package_discovery.rst, setup.cfg, setuptools/config/expand.py, setuptools/config/pyprojecttoml.py, setuptools/config/setupcfg.py, setuptools/discovery.py, setuptools/dist.py, setuptools/tests/config/test_expand.py, setuptools/tests/config/test_pyprojecttoml.py, setuptools/tests/config/test_setupcfg.py, setuptools/tests/test_config_discovery.py
In https://discuss.python.org/t/help-testing-experimental-features-in-setuptools/13821/2, a user pointed out that the auto-discovery of packages was not playing well with `attr:`.
The aim of this PR is to fix that, and make the discovery work when users want to use directives and dynamic configs (e.g. `attr:` and `cmdclass`) with `setup.cfg` or `pyproject.toml`.
- Run auto-discovery before using `package_dir` when parsing either `setup.cfg` or `pyproject.toml`.
- When parsing `setup.cfg` we have to be a bit more careful because the `parse_config_files` function can include files other than `setup.cfg`, so the best is to postpone the execution until the moment it is really necessary (the auto-discovery just run once, so we don't want to run it with incomplete arguments...)
Closes 
_(See …
=> [follow-up `pyproject.toml`] Fix auto-discovery when `attr:` directive is used in configuration

changelog.d/3144.doc.rst, docs/userguide/entry_point.rst
This adds documentation on using `console_scripts` from `setup.py`, which was previously only shown in setup.cfg
Closes 
[PR docs]:
=> Add setup.py code for console_scripts

changelog.d/3147.misc.rst, setuptools/tests/fixtures.py, tox.ini
- Check for ``PRE_BUILT_SETUPTOOLS_SDIST`` and ``PRE_BUILT_SETUPTOOLS_WHEEL`` environment variables before re-packaging the project in the `setuptools_wheel` and `setuptools_sdist` fixtures.
Closes #3147
[PR docs]:
=> [CI] Allow pre-built distribution to be used in tests with virtualenvs

docs/conf.py, docs/deprecated/distutils-legacy.rst
- State that the local copy of distutils is active by default
- Recommend `logging` instead of `distutils.log`
- Link PEP 632 migration advice.
Closes 
[PR docs]:
=> [Docs] Improve documentation about migration from distutils

.github/workflows/main.yml, setuptools/tests/test_build_meta.py, tox.ini
~According to a comment in pypa/distutils#118 this problem might be
solved by allowing tox to pass some environment variables.~ This approach does not work.
We can instead re-enable the tests for Windows, using 2019 (maybe that is better than skipping them completely?)
- ~Change `tox.ini` to pass `PROGRAMFILES(x86)` to tests
see https://github.com/pypa/distutils/issues/118#issuecomment-1052703319~
- Use `windows-2019` instead of `windows-latest` in the workflow description
[PR docs]:
=> Attempt to re-enable Windows tests

setuptools/config/pyprojecttoml.py, setuptools/tests/config/test_pyprojecttoml.py
`setup.cfg` accepts reading classifiers from a text file via the `file:` directive.
For compatibility, this PR ensures the same behaviour is possible via `pyproject.toml` and `tool.setuptools.dynamic.classifier`.
[PR docs]:
=> [follow-up `pyproject.toml`] Split lines when reading classifiers from file

changelog.d/3172.doc.rst, docs/build_meta.rst, docs/conf.py, docs/userguide/declarative_config.rst, docs/userguide/dependency_management.rst, docs/userguide/index.rst, docs/userguide/package_discovery.rst, docs/userguide/pyproject_config.rst, docs/userguide/quickstart.rst
- Added some docs about how to use `pyproject.toml` to config setuptools (aka PEP 621)
- Improved docs about auto-discovery
- Improved examples of declarative config for `setup.cfg`
- Improved examples in `quickstart` and `depencency management` for using experimental `pyproject.toml`.
Closes 
[PR docs]:
=> [follow-up `pyproject.toml`] Add initial docs about `pyproject.toml` configs

conftest.py, setup.cfg, setuptools/config/_apply_pyprojecttoml.py, setuptools/config/expand.py, setuptools/config/pyprojecttoml.py, setuptools/config/setupcfg.py, setuptools/tests/config/downloads/.gitignore, setuptools/tests/config/setupcfg_examples.txt, setuptools/tests/config/test_apply_pyprojecttoml.py, setuptools/tests/config/test_pyprojecttoml.py, setuptools/tests/integration/test_pip_install_sdist.py
> *This is part of #2970, split into several stacked PRs as requested in https://github.com/pypa/setuptools/pull/2970#pullrequestreview-868151658*
> *Follows #3066*
This change targets adding a standardised project configuration format as initially proposed by PEP 621 (with the possibility of modification/evolution according to follow-up PEPs).
For the configuration fields not covered by the standards, the approach proposed in [`ini2toml`](https://ini2toml.readthedocs.io/en/latest/setuptools_pep621.html) is adopted.
This operation relies on vendorised external libraries `tomli` and `validate-pyproject`.
- Implement `read_configuration` from `pyproject.toml` - 3eb62ac2912f8c0a8bfbdc5dbff809f983a14e2a
- Expand dynamic `entry_points` from `pyproject.toml` - …
=> [`pyproject.toml`: part 3] Add means to apply configuration from `pyproject.toml`

changelog.d/3068.change.rst, changelog.d/3068.deprecation.rst, docs/conf.py, pytest.ini, setuptools/config/__init__.py, setuptools/config/pyprojecttoml.py, setuptools/dist.py, setuptools/tests/config/test_pyprojecttoml.py, setuptools/tests/test_build_meta.py, setuptools/tests/test_editable_install.py
> *This is part of #2970, split into several stacked PRs as requested in https://github.com/pypa/setuptools/pull/2970#pullrequestreview-868151658*
> *Follows #3067*
This change builds on top of the recently added ability to parse and apply configurations from TOML files to distribution objects by tapping into the existing mechanism for handling configuration and making these TOML files to be read by default.
A series of deprecation warnings and tests is also added.
- Add `pyproject.toml` to `dist.parse_config_files` - b12b9d76a6fe5ff18646a3df19bbd193322ea7c4
- Add `PendingDeprecationWarning` for `setup.cfg` - 5baed645b8b67727a1cb8a4c74d3442381969d58
- Add backend test with `pyproject.toml`-based configs - b9ddb598ae1b6ec3d894b3dec2595a044a414203
- Test editable installs with …
=> [`pyproject.toml`: part 4] Integrate `pyproject.toml` configuration into existing classes

setuptools/config/_apply_pyprojecttoml.py, setuptools/config/expand.py, setuptools/config/pyprojecttoml.py, setuptools/config/setupcfg.py, setuptools/tests/config/test_setupcfg.py
> *This is part of #2970, split into several stacked PRs as requested in https://github.com/pypa/setuptools/pull/2970#pullrequestreview-868151658*
> *Follows #3068*
Type hints can help to increase confidence in the code and prevent unexpected bugs.
To typecheck the subpackage the following command can be used:
mypy setuptools/config --tb --show-error-codes --show-error-context --pretty
Type hints added to the packages:
- `setuptools.config.setupcfg`
- `setuptools.config.pyprojecttoml`
- `setuptools.config.expand`
[PR docs]:
=> [`pyproject.toml`: part 5] Add some type hints to the `setuptools.config` subpackage

.github/workflows/main.yml, tox.ini
According to pypa/distutils#118, we need to pass the following variables when compiling C-extensions on Windows:
- PROGRAMDATA
- PROGRAMFILES
- PROGRAMFILES(x86)
(compiler specific - VisualC++)
Closes #3135
*(Second attempt, in #3168 `PROGRAMDATA` was not passed)*
[PR docs]:
=> [CI] Attempt to update Windows hosts

setuptools/config/_apply_pyprojecttoml.py
When the user does not specify `Homepage` (or any variant such as `home-page`), distutils will warn the following message:
warning: check: missing required meta-data: url
This message is fine for `setup.cfg` builds because the field there is called `url`, but it does not work well for builds using `pyproject.toml` metadata because users can ask themselves "which url? I provided many..."
This problem was first identified in: https://discuss.python.org/t/help-testing-experimental-features-in-setuptools/13821
The change implemented here will add some other logging information that try to point the user in the correct direction for solving this issue.
Closes 
[PR docs]: …
=> [follow-up `pyproject.toml`] - Attempt to clarify which url is missing for pyproject-metadata builds

setuptools/config/expand.py, setuptools/config/pyprojecttoml.py, setuptools/config/setupcfg.py, setuptools/discovery.py, setuptools/dist.py, setuptools/tests/test_config_discovery.py
This is an incremental change on top of the existing integration between auto-discovery and `pyproject.toml` metadata configuration
- Fix missing assertion in text
- Rename variable alias (`silent` does not really capture the meaning of the what is happening)
- Use a lazy proxy for `package_dir` to avoid eagerly running auto-discovery
Closes 
[PR docs]:
=> [follow-up `discovery`, `pyproject.toml`] Improve integration between auto-discovery and `pyproject.toml` metadata

changelog.d/2887.change.1.rst, changelog.d/2894.breaking.rst, docs/userguide/package_discovery.rst, setuptools/config/pyprojecttoml.py, setuptools/discovery.py, setuptools/tests/test_config_discovery.py
[This CI build](https://github.com/pypa/setuptools/runs/5636559907?check_suite_focus=true) shows that some existing C-extension only packages might fail now that the safe-guards against flat-layouts with multi-top level modules/packages are in place.
This PR attempts to improve backward compatibility by disabling auto-discovery when `ext_modules` is set.
This backward compatibility behaviour will be disabled, however when `pyproject.toml` metadata is used (a.k.a. PEP 621-style config).
[PR docs]:
=> [follow-up `discovery`, `pyproject.toml`] Prevent existing C-extension only packages from failing

changelog.d/3178.change.rst, setuptools/windows_support.py
In appdirs.py, ctypes is only imported within a function, rather than always for appdirs.py.
https://github.com/pypa/setuptools/blob/02f3821b9af91feadae2326b78a814ac2fbbe520/pkg_resources/_vendor/appdirs.py#L506-L507
This is also done in both copies of _manylinux.py.
https://github.com/pypa/setuptools/blob/02f3821b9af91feadae2326b78a814ac2fbbe520/setuptools/_vendor/packaging/_manylinux.py#L154-L159
https://github.com/pypa/setuptools/blob/02f3821b9af91feadae2326b78a814ac2fbbe520/pkg_resources/_vendor/packaging/_manylinux.py#L154-L159
This PR applies this pattern to windows_support.py as well, only importing ctypes within `hide_file()`.
This will also save non-Windows users from always requiring ctypes (yes, windows_support.py is [imported regardless of …
=> Only import ctypes when necessary

changelog.d/2887.change.1.rst, changelog.d/2887.change.2.rst, changelog.d/2894.breaking.rst, docs/userguide/package_discovery.rst, setup.cfg, setuptools/__init__.py, setuptools/discovery.py, setuptools/dist.py, setuptools/tests/integration/helpers.py, setuptools/tests/test_config_discovery.py, setuptools/tests/test_dist.py, setuptools/tests/test_find_packages.py, setuptools/tests/test_find_py_modules.py
As discussed in #2887 and #2888, it would be nice to have some configurations automatically derived.
This is definitely possible for `packages` and `py_modules`, and (based on these two) also for `name` (as suggested by @jaraco).
This implementation supersedes #2888 (closes #2888).
- A new class `setuptools.discovery.ConfigDiscovery` implementing the automatic discovery logic
- Moved `PackageFinder` and `PEP420PackageFinder` to the `setuptools.discovery` module due to the implementation affinity.
- New `FlatLayoutPackageFinder` and `FlatLayoutModuleFinder` classes implementing a more careful discovery (more exclude patterns) since they are meant to be used directly with the project directory.
- `ConfigDiscovery` changes the `Distribution` object just before running commands. …
=> Towards no-config packaging: Automatic discovery of `packages`, `py_modules` and `name`

setuptools/tests/config/test_expand.py
- Add a unit test to verify that `attr:` can be solved via static import even when other imports happen first (#3176)
- Add a unit test to verify that `cmdclass` can be loaded from within the given package, (this is not exactly #3000, but similar).
Closes #3176
[PR docs]:
=> Add unit test for issue with `attr:`

docs/userguide/dependency_management.rst, docs/userguide/pyproject_config.rst, docs/userguide/quickstart.rst, setuptools/_vendor/_validate_pyproject/NOTICE, setuptools/tests/integration/test_pip_install_sdist.py
Spotted a tiny typo on the new `pyproject.toml` documentation. Grepping through the repository, the same typo was also present in other documents.
_(See [documentation][PR docs] for details)_~ Not applicable
=> Fix `bellow` typo in docs

changelog.d/3202.change.rst, setuptools/config/expand.py, setuptools/discovery.py, setuptools/tests/test_config_discovery.py
This is an attempt to fix #3196
- Avoid auto-discovery to add entries to ``package_dir`` in flat-layouts
- Avoid using paths starting with `./` in ``package_dir``
Closes 
[PR docs]:
=> Make sure auto-discovery does not break `include_package_data`

CHANGES.rst, changelog.d/3203.change.rst, setuptools/config/pyprojecttoml.py, setuptools/tests/config/test_pyprojecttoml.py
- Consider that `dist.include_package_data` can be given via `setup.py` when parsing `pyproject.toml`
- Add missing notes about changes to previous release
Closes #3203 
[PR docs]:
=> Avoid overwriting `dist.include_package_data` given by `setup.py`

changelog.d/3206.deprecation.rst, setuptools/__init__.py, setuptools/tests/test_setuptools.py
- Add the internal function `convert_path` back to `setuptools/__init__.py`
(despite being an internal function some packages seem to rely on it).
Closes #3201
[PR docs]:
=> Add `convert_path` back (but with deprecated status)

changelog.d/3208.change.1.rst, changelog.d/3208.change.2.rst, setuptools/config/expand.py, setuptools/config/pyprojecttoml.py, setuptools/tests/config/test_apply_pyprojecttoml.py, setuptools/tests/config/test_expand.py, setuptools/tests/config/test_pyprojecttoml.py, setuptools/tests/config/test_setupcfg.py
- Added a warning for non existing files listed with the ``file`` directive in ``setup.cfg`` and ``pyproject.toml``.
- Added a default value for dynamic ``classifiers`` in ``pyproject.toml`` when files are missing and errors being ignored.
Closes #3208
[PR docs]:
=> Make sure dynamic classifiers in `pyproject.toml` don't fail

changelog.d/3211.change.rst, setuptools/discovery.py, setuptools/tests/test_config_discovery.py
- Disable auto-discovery when package is using `numpy.distutils.misc_util.Configuration`
[PR docs]:
=> Disable auto-discovery when the 'configuration' attribute is passed

CHANGES.rst, changelog.d/3212.misc.rst, setuptools/command/easy_install.py, setuptools/command/install.py, setuptools/tests/test_easy_install.py
- Fix condition in the `setuptools.command.install` to detect whether the command was called directly from `setup()` or by another command.
Closes #3198
[PR docs]:
=> Fix missing dependencies with `setup.py install`

changelog.d/3217.doc.rst, docs/userguide/quickstart.rst
Fixed typo in pyproject.toml
```
cli-name = mypkg.mymodule:some_func    =>    cli-name = "mypkg.mymodule:some_func"
```
Closes #3216
[PR docs]:
=> Fix typo in quickstart section

changelog.d/3218.change.rst, setuptools/config/_apply_pyprojecttoml.py, setuptools/config/pyprojecttoml.py, setuptools/tests/config/test_apply_pyprojecttoml.py, setuptools/tests/config/test_pyprojecttoml.py
- Added a warning if the project has a valid `pyproject.toml` with a `[project]` table, but at the same time it is trying to set other configs via other files (e.g. `setup.py`), without setting `dynamic` properly
- In future releases (when support for `pyproject.toml` metadata stabilises), instead of warning, setuptools should fail.
Closes #3195
[PR docs]:
=> [`pyproject.toml`] Temporarily warn about improper backfilling without `dynamic`

MANIFEST.in, changelog.d/3233.misc.1.rst, changelog.d/3233.misc.2.rst, setuptools/tests/config/downloads/.gitignore, setuptools/tests/config/downloads/__init__.py, setuptools/tests/config/downloads/preload.py, setuptools/tests/config/test_apply_pyprojecttoml.py
- Adds `setupcfg_examples.txt` to sdist via `MANIFEST.in`
- Ensure `setupcfg_examples.txt` is included in `sdist` but not included in `wheel`
- Add script to pre-load examples from `setupcfg_examples.txt` in case developers want to run the tests offline.
Closes #3233
[PR docs]:
=> Fix problems with missing `setupcfg_examples.txt`

changelog.d/3151.breaking.rst, setuptools/command/easy_install.py, setuptools/tests/test_easy_install.py
Make `setup.py develop --user` install to the user site packages directory even if it is disabled in the current interpreter.
Closes https://github.com/pypa/setuptools/issues/3019
[PR docs]:
=> Fix editable --user installs with build isolation

setuptools/tests/test_easy_install.py
Due to an outdated merge base `test_easy_install` ended up introducing some incompatibility with v61.*
The changes implemented in this PR attempt to fix the incompatibilities.
[PR docs]:
=> Fix error with `test_easy_install`

changelog.d/3153.change.rst, pkg_resources/__init__.py, pkg_resources/tests/test_working_set.py
Requirements might be specified using normalized names as described in PEP 503 but working set would not match them to installed packages that are identified by their canonical name. This is the reason of this [issue in liccheck].
[PR docs]:
[issue in liccheck]: https://github.com/dhatim/python-license-check/issues/81
=> Match normalized requirement names

changelog.d/3167.change.rst, setuptools/archive_util.py, setuptools/tests/test_wheel.py, setuptools/wheel.py
- [?] News fragment added in [`changelog.d/`].
[PR docs]:
See https://github.com/pypa/setuptools/issues/3166 for more info.
=>  [BUG] wheel install_as_egg does not honor file mode

changelog.d/3088.misc.rst, setuptools/command/dist_info.py, setuptools/command/egg_info.py, setuptools/tests/test_dist_info.py
- Fix duplicated tag with the ``dist-info`` command
- Make sure directory created by ``dist-info`` has the same name as the one created by ``bdist_wheel`` and contains the same ``METADATA`` and ``entry_points.txt`` file.
Closes #3088
[PR docs]:
=> Fix version produced by `dist_info`

changelog.d/3244.misc.rst, setuptools/config/pyprojecttoml.py, setuptools/tests/config/test_pyprojecttoml.py
- Fix problem with dynamic readme coming from `setup.py`.
Closes #3244
[PR docs]:
=> [support for `pyproject.toml`] Fix problem with dynamic readme

changelog.d/3249.misc.rst, setuptools/config/expand.py, setuptools/tests/config/test_expand.py
- If the directory follows a `src-layout`-ish, try harder to make `package_dir` in the form `{"": "src"}`.
This might be later important for PEP 660 (e.g. when composing `pth` files or symlinking the top-level packages).
Closes 
[PR docs]:
=> [follow-up auto-discovery] Simplify `package_dir`

changelog.d/3258.change.rst, setuptools/_distutils/command/build.py, setuptools/_distutils/py39compat.py, setuptools/_distutils/sysconfig.py, setuptools/_distutils/tests/test_build.py, setuptools/_distutils/tests/test_install.py, setuptools/_distutils/tests/test_sysconfig.py, setuptools/_distutils/version.py
- Fix EXT_SUFFIX for windows py<3.8
- Fix SO too
- Move EXT_SUFFIX support to _py39compat, to be removed after support for Python 3.9 is dropped. Fall back to default behavior on Python 3.10. Remove functionality for SO, which has been long deprecated and is untested.
- 👹 Feed the hobgoblins (delint).
- Just modify the vars in place.
- Restore expectation that SO matches EXT_SUFFIX with rationale.
- Get the version logic correct.
- Move compatibility concerns out of the function to do the adding.
- Emit warning after parsing. Fixes pypa/distutils#122.
- Disable installation of Setuptools in tox instead of GHA. Ref pypa/distutils#99.
- Use cache_tag in default build_platlib dir
- Skip test_get_makefile_filename on non-CPython
- Update test_home_installation_scheme for pypy install paths
- …
=> Merge distutils at 5229dad46b

.github/workflows/main.yml, changelog.d/3282.misc.rst, setuptools/tests/config/downloads/__init__.py
Recently Github Actions started to fail with `HTTP Error 429: Too Many Requests`.
It would seem that GitHub is adding some throttle mechanism (or making it tighter)
- Adds caching, so when the test runs, it doesn't reach the network
- Back off for a few seconds in case of error when downloading the files (this prevents the script for populating the cache from failing).
Closes 
[PR docs]:
=> Cache downloaded files used during tests for `setuptools.config`

setuptools/config/_apply_pyprojecttoml.py, setuptools/dist.py, setuptools/tests/config/test_apply_pyprojecttoml.py
Same as https://github.com/pypa/setuptools/pull/3289 but without the changes under _distutils (companion to pypa/distutils#138).
=> Optional metadata sans distutils

.github/workflows/main.yml, changelog.d/3299.change.rst, docs/deprecated/distutils/examples.rst, docs/deprecated/distutils/setupscript.rst, setuptools/_distutils/_functools.py, setuptools/_distutils/command/bdist_msi.py, setuptools/_distutils/command/bdist_rpm.py, setuptools/_distutils/command/check.py, setuptools/_distutils/dist.py, setuptools/_distutils/sysconfig.py, setuptools/_distutils/tests/test_check.py, setuptools/_distutils/tests/test_dist.py, setuptools/_distutils/tests/test_register.py, setuptools/_distutils/tests/test_sdist.py, setuptools/_distutils/tests/test_sysconfig.py, tox.ini
- Detect when a venv is created from an in-tree build. Fixes #132
- make all fields documented as optional in the spec truly optional (dont warn when omitted), and stop coercing missing values to the string "UNKNOWN"
- Extract check for 'd is None'.
- Combine logic between prefix and base_prefix.
- Adapt style
- Simply emit the expected value instead of converting to an exit code and deciphering.
- Rely on jaraco.envs for environment creation.
- Prefer tabs
- Use pass_none decorator.
- Prefer tox 3.25 with built-in support for Windows env vars.
- Run tests using tox, even on cygwin.
- Prefer tabs
- address review comments
- fix a typo
- Update changelog
Closes 
[PR …
=> Merge with pypa/distutils@a7cfb56a7

CHANGES.rst, changelog.d/3292.misc.rst, setuptools/_importlib.py
- Add a warning about incompatible verions of `importlib_metadata`
Closes #3292, #3293
[PR docs]:
=> Add warnings about bundled dependencies incompatibilities.

docs/userguide/dependency_management.rst, docs/userguide/package_discovery.rst, docs/userguide/pyproject_config.rst, docs/userguide/quickstart.rst
The current documentation regarding `pyproject.toml` claims that support for using it to specify package metadata and build configuration options might be "completely removed" in a future setuptools release.
However, nowadays it is clear (https://github.com/pypa/setuptools/issues/1688#issuecomment-1079706929 and #3214) that `pyproject.toml` is not going to be removed, and is in fact intended to be the preferred format at some point in the future.
This makes an incremental change toward that future by clarifying that `pyproject.toml` support will not be removed in a future release of setuptools.
[PR docs]:
https://setuptools.pypa.io/en/latest/development/developer-guide. …
=> Clarify that `pyproject.toml` config will not be removed

docs/build_meta.rst
- Tense changed in first paragraph: should be either past or present; present seems fair since a lot of people still use or even need `setup.py`.
- Line 20: missing 'the'
- Under 'How to use it?' I added a Python file to the source tree; seems like the sort of thing a beginner could get confused about ("where does my code go?").
- A couple of small typos.
- [N] Changes have tests
- [N] News fragment added in [`changelog.d/`].
I was doubtful that these changes warranted this.
=> Some small typos and grammar fixes

changelog.d/1806.change.rst, setuptools/command/build_py.py, setuptools/tests/test_build_py.py
Calls to `glob` within `find_data_files` now have `recursive=True`. This allows for the use of the `**` globs in `package_data`.
Closes #1806
=> Allow recursive globs for package_data

changelog.d/3308.deprecation.rst, docs/userguide/quickstart.rst, setuptools/command/build_py.py, setuptools/tests/test_build_py.py
When discovering files in `build_py`, warn (`SetuptoolsDeprectationWarning`) if files and directories that correspond to a sub-package are included as "data".
This is the first step towards #3260 (we first need to issue a deprecation so packages relying on this behaviour can implement the required changes)
[PR docs]:
=> Warn about deprecation of behaviour that considers modules/packages as "data" when `include_package_data=True`

changelog.d/3262.deprecation.rst, docs/references/keywords.rst, docs/userguide/declarative_config.rst, docs/userguide/pyproject_config.rst, setuptools/config/_apply_pyprojecttoml.py, setuptools/config/setupcfg.py, setuptools/dist.py, setuptools/tests/config/test_apply_pyprojecttoml.py, setuptools/tests/config/test_setupcfg.py
The docs in https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
and https://packaging.python.org/en/latest/guides/packaging-namespace-packages/
seem to suggest that using `namespace_packages` is a deprecated practice.
- Add warnings for `namespace_packages`
- Use `SetuptoolsDeprecationWarning` for the other deprecations in `setup.cfg` (`SetuptoolsDeprecationWarning` is used broadly instead of `DeprecationWarning` in the code base to make sure the warning message is not accidentally silenced.
Closes 
[PR docs]:
=> Add deprecation messages for `namespace_packages`

CHANGES.rst, changelog.d/3331.doc.rst
These two items `**` and `package_data` in the `CHANGES.rst` file were being identified as links rather than code due to the single backticks.
In turn leading to Sphinx emitting warnings about this and the docs failing to build.
Closes: No issue that I am aware of? However these warnings were preventing the docs from building on my machine.
=> Replaced single backticks with double ones

changelog.d/3332.doc.rst, docs/userguide/package_discovery.rst
1. Grammar fixes: "namespace package" -> "namespace packages" and other such small fixes.
2. Modified directory trees shown to illustrate src-layout and flat-layout, by adding two package directories `mypkg1` and `mypkg2` instead of a single package directory `mypkg`. This is in order to improve consistency with the previous example which shows two packages `mypkg1` and `mypkg2`, and make it clear that multiple packages are allowed.
3. Typo fix: "aditional" -> "additional"
[PR docs]:
=> Minor changes to the User Guide's Package Discovery page

changelog.d/3336.misc.rst, setuptools/tests/test_easy_install.py
This has the same reasoning as in https://github.com/pypa/setuptools/pull/3133 -- the test imported the previously installed setuptools version in our environment and since that version did not yet use `__EASYINSTALL_INDEX`, it reached https://pypi.org/simple/ instead. That way, we recognized it as a problem. If the installed version had already used `__EASYINSTALL_INDEX`, we would probably never realize that it is the installed version that is being tested here.
The three individual commits follow my train of thoughts, so I preserved them here separated, for easier review. 
1. The test was very hard to grasp for me, so I removed the `pytest.raises` detour -- happy to revert if there was a reason for it
2. I changed the test to modify the `$PYTHONPATH` value instead of overriding it, …
=> Make test_setup_install_includes_dependencies work with custom PYTHONPATH set

changelog.d/3350.doc.rst, docs/userguide/datafiles.rst
Clarify glob pattern matching for dotfiles in User's Guide (Data Files section).
Please comment or directly edit any issues with suggested change, such as phrasing or location of the documentation change.
Closes #3350
[PR docs]:
=> Clarify glob pattern matching for dotfiles in User's Guide (#3350)

setuptools/command/build_py.py
In https://github.com/pypa/setuptools/issues/3340#issuecomment-1150716323, it was suggested to modify a warning message to make it more clear for users.
- Modifies the warning in `build_py _IncludePackageDataAbuse` according to the users suggestion.
Closes 
[PR docs]:
=> Change warning about namespace packages and data files

changelog.d/3358.doc.rst, docs/references/keywords.rst, docs/userguide/declarative_config.rst
- Expand on the summary about ``package_dir`` in the Keywords page to make it more clear what this configuration parameter does.
Closes #3357
[PR docs]:
=> Clarify the `package_dir` configuration

docs/userguide/entry_point.rst
Console scripts section:
- Added `pyproject.toml` snippet
- Modified `setup.py` snippet (corrected indentation and removed unnecessary name, version, etc. fields)
- Changed the example to use src-layout
- Some changes in the wording etc.
Added GUI Scripts section:
- Included `setup.cfg` / `setup.py` / `pyproject.toml` snippets
- Added an example Hello world function that can be invoked through a GUI script
Other changes:
- Added note on distinction between Console and GUI scripts
- Added note on how installers like Pip create wrapper scripts around invoked functions
- Included few lines stating that invoked functions should not accept any arguments and parse user input within the function body
_Have not finished this yet. Will update here with further changes._
_(See [documentation][PR …
=> Changes to the User Guide's Entry Points page

changelog.d/3363.doc.rst, docs/conf.py, docs/deprecated/index.rst, docs/deprecated/running_commands.rst, docs/index.rst, docs/userguide/development_mode.rst, docs/userguide/index.rst, docs/userguide/quickstart.rst
The existing docs seem to assume that the user is familiar with the history of packaging in the Python ecosystem (or at least know what is `distutils`).
Since that is not always the case and that `distutils` is in the process of being adopted by `setuptools`, the documentation should be changed to minimize mentions to `distutils` and avoid expecting too much knowledge from the users.
The benefit of this approach is that it can make the docs more accessible and easier to understand.
This PR is not exhaustive and do not implement all the necessary changes to achieve this view, and it is likely that many follow up PRs would be required.
- Modify landing page to clarify what `setuptools` does (making it more clear to understand for beginners).
- Remove mentions to `distutils`, `transition to …
=> Improve docs by avoiding confusion with distutils

changelog.d/3364.doc.rst, docs/build_meta.rst, docs/deprecated/dependency_links.rst, docs/deprecated/index.rst, docs/userguide/dependency_management.rst
- Extract `depencency_liks` section to a new file:
`deprecated/dependency_links.rst`
- Add note about directly URLs not being accepted in PyPI.
- Simplify intro about build system requirement.
- Simplify intro about optional dependencies.
- Fix confusion in example about "Project" and "Package".
- "Demote" section about extras in entry-points to a note.
[PR docs]:
=> Update dependency management docs

changelog.d/3256.change.rst, setup.cfg, setuptools/command/build.py, setuptools/tests/test_build.py
In order to override distutils.command.build on downstream projects
it is good to have a setuptools specific command which allows
downstream projects to avoid importing distutils.
Closes 
[PR docs]:
=> Add setuptools.command.build

changelog.d/3368.doc.rst, docs/userguide/ext_modules.rst, docs/userguide/index.rst, setuptools/extension.py
Add documentation on `build_ext` as requested by @jaraco in https://github.com/python/cpython/issues/90539#issuecomment-1153274032
[PR docs]:
=> docs/userguide/ext_modules.rst: New

changelog.d/3372.doc.rst, docs/userguide/distribution.rst, docs/userguide/miscellaneous.rst
The existing section about `sdist` in `userguide/distribution` seems to have duplicated content when compared to another section in `userguide/miscellaneous`. We can combine these two sections and simplify the documentation.
- Consolidate text about `sdist` contents and `MANIFEST.in` into a single place.
- De-emphasize ``distutils`` and the history of ``setuptools`` (new users might not know about it, which would make them less confuse).
Closes 
[PR docs]:
=> [Docs] Consolidate sections about sdist contents and MANIFEST.in into a single document

changelog.d/3374.doc.rst, docs/userguide/distribution.rst
- Add warning about calling setup.py directly and clarify that this is only a transitional way of doing things
- Reorder sections in the document to make it clearer.
Closes 
[PR docs]:
=> [Docs] Improve instructions for dealing with version

changelog.d/3378.doc.rst, docs/conf.py, docs/userguide/quickstart.rst
- Rework ``installation`` to actually reflect the way we expect people to use ``setuptools``.
- Remove references to the history of Python packaging... Beginners don't necessarily know how things used to be and adding this type of content may confuse them.
- Restructure remaining sections as part of "Overview".
- Change `Package discovery` section to better reflect the new auto-discovery mechanism.
Closes 
[PR docs]:
=> Update quickstart to make it more streamline

changelog.d/3347.change.rst, docs/userguide/datafiles.rst, docs/userguide/dependency_management.rst, docs/userguide/entry_point.rst, docs/userguide/package_discovery.rst, docs/userguide/pyproject_config.rst, docs/userguide/quickstart.rst, pytest.ini, setuptools/config/pyprojecttoml.py
As noted in https://github.com/pypa/setuptools/issues/2671#issuecomment-1141905999, it would be good if we clarify which parts of the `pyproject.toml` configuration are considered experimental or not.
It is been a few months since the implementation of PEP 621 support landed in setuptools (after a long period of feedback), and it seems now that support for project metadata in `pyproject.toml` has stabilised. Moreover the existing implementation is backed by a PEP, therefore it makes sense to consider this part of the feature stable.
- Warn about `tool.setuptools` instead of project metadata in `pyproject.toml`
Closes 
[PR docs]: …
=> Add clarifications about `experimental` status for `pyproject.toml` configuration

changelog.d/3380.change.rst, changelog.d/3380.deprecation.rst, pytest.ini, setuptools/build_meta.py, setuptools/command/dist_info.py, setuptools/command/editable_wheel.py, setuptools/tests/test_build_meta.py, setuptools/tests/test_dist_info.py
This PR is a continuation of the work done to implement PEP 660.
The main objective of this PR is to add support for `config_settings` to select which mode is going to be used by the `build_editable` hook.
But since I was already working with it and adding some tests, I ended up fixing other some other items.
- Improvements in terms of the handling of ``config_settings``:
- Allow frontends and installers to select the strict editable mode via the ``config_settings`` argument passed to the PEP 660 hooks.
Now users should be able to run:
```bash
pip install -e . --config-settings editable-mode=strict
```
- Separate config settings given by ``--global-option`` and ``--build-option``. The motivation (and approach) for this change is described in #1928.
When calling setuptools internal …
=> Handle `config_settings` as they would be passed by pip

changelog.d/3385.misc.rst, setuptools/config/_apply_pyprojecttoml.py, setuptools/config/expand.py, setuptools/config/pyprojecttoml.py, setuptools/config/setupcfg.py
Now that we are stating that configurations passed via `pyproject.toml` can be considered stable, we should also clarify that the code used to parse/expand/evaluate them are private (see #3232).
In the future we might rename the entire `setuptools.config` package to `setuptools._config`.
For the time being, I am adding an entry to the changelog and a note on the module's docstring.
Closes 
[PR docs]:
=> Clarify modules used for pyproject.toml parsing are private

docs/userguide/ext_modules.rst
Follow-up on #3368 
@abravalheri 
[PR docs]:
=> docs/userguide/ext_modules.rst: Add more detail on sysconfig/environ vars

changelog.d/3391.change.rst, setuptools/config/expand.py, setuptools/tests/config/test_expand.py
This extends the ast parsing setuptools does to load attributes without evaluating a module to also process simple assignments with type annotations. Those produce a different node `ast.AnnAssign` rather than `ast.Assign` and require slightly different handling since the node has a different attribute `target` vs `targets`.
Since that seemed like it might make the generators more complicated, I reworked things into for loops and made some other tweaks. I'd be happy to take a different approach though.
The existing `ast.Assign` nodes should pass through exactly the same processing. The `AttributeError` that could result should also be the same too, except that it won't be chained with a `StopIteration` if the outer for loop is exhausted (as it would be with the `next()` call).
This doesn't …
=> Add support for type annotations to `attr:` ast parsing

changelog.d/3253.change.rst, docs/userguide/declarative_config.rst, setuptools/config/setupcfg.py, setuptools/tests/config/test_setupcfg.py
As requested and discussed in #1951, this PR enables using `file:` in <del>the various `requires` statements</del> `install_requires` and `extras_require` statements in setup.cfg.
As @jaraco mentioned in https://github.com/pypa/setuptools/issues/1951#issuecomment-574737840, this adds a (small) admonition advising against library packagers pinning their dependencies too tightly with this feature.
Closes #1951
=> Allow file: for requires statements in setup.cfg

changelog.d/3394.doc.rst, docs/userguide/extension.rst
This updates the documentation for the `file_finders` hook so that the logging recommendation aligns with the [suggestion to not use `distutils` directly](https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html#prefer-setuptools).
[PR docs]:
=> Update logging recommendation to not use distutils

changelog.d/3397.doc.rst, docs/references/keywords.rst
- Fix reference for `keywords` to point to the live standard.
Closes #3396
[PR docs]:
=> [Docs] Fix reference for keywords

changelog.d/3392.change.rst, setuptools/command/build_ext.py, setuptools/command/build_py.py, setuptools/extension.py, setuptools/tests/test_build_ext.py, setuptools/tests/test_build_py.py
This is another set of changes targeting PEP 660.
The existing PoC implementation of PEP 660 "persuades" build_py and build_ext to symlink/hardlink files instead of copying, but the problem with this approach is that we don't have any visibility of what is happening.
In this PR I am proposing to expose `get_output_mapping` (together with the existing `get_outputs`). This will probably be the basis of the "protocol" `editable_wheel` will use for handling `build` subcommands.
``get_output_mapping`` should a mapping between destination files as they would be produced by the build (dict keys) into the respective existing (source) files (dict values).
Existing (source) files should be represented as strings relative to the project root directory.
Destination files should be strings in the form …
=> Add `get_output_mapping` to `build_py` and `build_ext`

changelog.d/3402.doc.rst, docs/userguide/development_mode.rst, docs/userguide/index.rst
Reorganized the User Guide's Table of Contents
This mostly follows the scheme given [here](https://github.com/pypa/setuptools/discussions/3400#discussioncomment-3003334), with the following exceptions:
- "Controlling files in the distribution" is kept not immediately after the "Package Discovery" page, but rather towards the end, because a lot of the material in that page overlaps with material given in the "Package Discovery" and "Data Files" pages. Therefore, it seems to me that this page should be read _after_ the other two pages have been
read.
- "Development Mode" is kept not towards the end but introduced close to the beginning, because readers might want to start using it early on in their projects.
- "Building Extension Modules" is kept immediately after the "Entry Points" and …
=> Reordering of User Guide's Table of Contents

setuptools/_path.py, setuptools/build_meta.py, setuptools/command/dist_info.py, setuptools/config/expand.py, setuptools/tests/test_dist_info.py
Motivation: ``build_py`` needs `egg_info` to be able to list the output files (via ``get_outputs()``).
In a follow up PR, we can re-use the existing `egg_info` dir in ``editable_wheel`` when collecting the files in `get_outputs()`.
- Add an *internal* option to `dist_info` to keep the egg_info around
- Refactor `build_meta` to not remove the `egg_info` directory after the `prepare_*` hook.
Closes 
[PR docs]:
=> Allow `dist_info` command to leave the `egg_info` directory to be used by other steps of the build

setuptools/__init__.py, setuptools/command/build.py, setuptools/command/build_ext.py, setuptools/command/build_py.py, setuptools/command/editable_wheel.py, setuptools/tests/test_editable_install.py
This is a follow up on the previous PRs:
- Instead of forcing ``build_py`` and ``build_ext`` to link files instead of copying, the logic of the ``editable_wheel`` command was changes to rely on the updated ``get_outputs()`` and ``get_output_mapping()`` commands.
- ``editable_wheel`` will also run all ``build`` subcommands now instead of old ``build_py`` and ``build_ext``, this increases compatibility with customisations relying on subcommands.
- API added to support subcommands.
Closes 
[PR docs]:
=> Update editable install to use `get_output_mapping`

changelog.d/3412.change.rst, setuptools/command/build.py, setuptools/command/sdist.py, setuptools/tests/test_sdist.py
- Expand the API defined for custom sub-commands by documenting `get_source_files()`
- This function is already defined for all existing `build_*` subcommands. We are just asking custom implementations to also honour this interface.
- Add the return value of ``get_source_files()`` to the file list created in ``sdist``.
Closes 
[PR docs]:
=> sdist: Add files from build subcommands (`get_source_files`)

changelog.d/3414.change.rst, changelog.d/3414.doc.rst, docs/userguide/development_mode.rst, docs/userguide/entry_point.rst, docs/userguide/extension.rst, setuptools/__init__.py, setuptools/build_meta.py, setuptools/command/build.py, setuptools/command/editable_wheel.py, setuptools/tests/test_build_meta.py
- Test symlinks in the target directory instead of temp dir
- Update development mode docs
- Allow users to specify `SETUPTOOLS_ENABLE_FEATURE=legacy-editable`
Closes 
[PR docs]:
=> Improve docs and behavior of editable installs

docs/userguide/package_discovery.rst
This is a follow up on https://github.com/pypa/setuptools/discussions/3403.
- Change the examples to make it more obvious that both `include` and `exclude` are optional for `find_packages()/find_namespace_packages()/...`
Closes 
[PR docs]:
=> Attempt to clarify include/exclude in docs about package discovery.

docs/userguide/development_mode.rst
As suggested in [this thread](https://discuss.python.org/t/help-testing-pep-660-support-in-setuptools/16904/11?u=abravalheri), a warning was added to tell users about the `build` directory being used to create the link tree.
Closes 
[PR docs]:
=> Document strict editable installs use the `build` directory

changelog.d/3430.change.rst, setuptools/_distutils/command/_framework_compat.py, setuptools/_distutils/command/build_py.py, setuptools/_distutils/command/install.py, setuptools/_distutils/cygwinccompiler.py, setuptools/_distutils/tests/test_build_py.py, setuptools/_distutils/tests/test_cygwinccompiler.py
- Improve handling if runtime_library_dirs is set with cygwin/mingw
- Add test capturing expectations
- Remove warnings on namespace packages
- Add support for Homebrew on Python 3.9 instead of relying on distutils.cfg as found in the stdlib. Fixes pypa/distutils#152.
Closes 
[PR docs]:
=> Merge with pypa/distutils@152c13d

docs/userguide/extension.rst, setuptools/command/build.py
Probably this section of the docs needs some reorganizing to be more clear. But for the time being it is better than nothing...
- Add `:members:` to `setuptools.command.build.SubCommand` to ensure `get_output_mapping()` is displayed in the docs.
Closes 
[PR docs]:
=> [Doc] Ensure members of the build subcommand protocol are listed by autodoc

setuptools/config/__init__.py
Points to deprecation itself in setuptools, `/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/config/__init__.py`:
```
================================================================== warnings summary ==================================================================
pyroma/tests.py::RatingsTest::test_only_config
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/config/__init__.py:28: SetuptoolsDeprecationWarning: As setuptools moves its configuration towards `pyproject.toml`,
`setuptools.config.read_configuration` became deprecated.
For the time being, you can use the `setuptools.config.setupcfg` module
to access a backward compatible API, but this module is provisional
and might be removed in the …
```
=> Deprecation: Add stacklevel=2 to make calling code clear

pyproject.toml
This is a follow up on https://github.com/pypa/setuptools/commit/120d9270c50a07caad0c697ca1f4b865226dde99.
Change the `[pytest.enabler.xdist]` config to `[tool.pytest-enabler.xdist]` in `pyproject.toml`.
Closes 
[PR docs]:
=> Use the new `pytest-enabler` config section for xdist

docs/userguide/quickstart.rst
I believe the correct `setup.cfg` packaging option is `find_namespace:`, not `find_namespaces:`
I can't find any other references to `find_namespaces` in the docs or repository.
Using `find_namespaces:` causes packaging to fail. Example to reproduce:
```
.
├── pyproject.toml
├── setup.cfg
└── src
├── pkg1
│   └── namespace
│       └── __init__.py
└── pkg2
└── __init__.py
```
Contents of `pyproject.toml`:
```
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
```
Contents of `setup.cfg`:
```
[metadata]
name = pkg_test
[options]
packages = find_namespaces:
package_dir =
=src
[options.packages.find]
where = src
```
```
$ pip install .
> ...
> error: package directory 'src/find_namespaces:' does not exist
> ...
```
Closes 
_(See [documentation][PR docs] for …
=> Fix typo `find_namespaces:` to `find_namespace:`

changelog.d/3443.doc.rst, docs/conf.py, setup.cfg
I'm suggesting installing the Sphinx extension [`sphinx-hoverxref`](https://github.com/readthedocs/sphinx-hoverxref/) to enable tooltips when hovering internal and external references (via intersphinx).
I set up a testing project on Read the Docs to show what it looks like in a live preview. Check it out at https://humitos-setuptools.readthedocs.io/en/docs-tooltips/userguide/quickstart.html
Let me know if this is something you like and if you want me to do any changes for the PR to be approved.
Here is a small GIF showing it in action and internal reference.
Another GIF showing an external reference pointing to twine:
----
[PR docs]: …
=> Docs: enable tooltips on documentation

setuptools/build_meta.py, setuptools/tests/test_build_py.py
(*Another PR related to the PEP 660 implementation, carried out in the `feature/pep660` branch*)
- Adds `prepare_metadata_for_build_editable` to `build_meta.__all__` (this was noted as missing in
https://github.com/pypa/setuptools/pull/3265#discussion_r935208205).
- (Unrelated) replace list comparison with set comparison in test (to address test failure).
Closes 
[PR docs]:
=> Add `prepare_metadata_for_build_editable` to `build_meta.__all__`

setuptools/tests/test_build_meta.py
*(Another PR related to the PEP 660 implementation, carried out in the feature/pep660 branch)*
- Use `venv` to prevent breaking test isolation.
Closes 
[PR docs]:
=> Use `venv` to isolate `test_legacy_editable_install`

changelog.d/2971.change.rst, setuptools/command/upload_docs.py
This reverts commit 995d309317c6895a123c03df28bc8f51f6ead5f5.
Ref #2971.
Closes 
[PR docs]:
=> Deprecate upload_docs command

changelog.d/3482.misc.rst, setuptools/_distutils/command/bdist.py
- Revert "Remove compatibility shims for Setuptools."
- Mark use of format_commands.append as deprecated. Ref anxuae/setuptools-cythonize#8.
Closes 
[PR docs]:
=> Merge with pypa/distutils@274758f1c02048

setuptools/tests/test_editable_install.py
*(Another PR related to the PEP 660 implementation, carried out in the feature/pep660 branch)*
- Now that pip supports `--config-settings` for editable installs setting the environment var `SETUPTOOLS_EDITABLE` is no longer necessary, and the tests should not rely on it.
Closes 
[PR docs]:
=> Avoid using `SETUPTOOLS_EDITABLE` env var in test

CHANGES.rst
Fix wrong syntax usage on `CHANGES.rst`.
Closes 
[PR docs]:
=> docs: Fix wrong syntax usage on CHANGES.rst

changelog.d/3265.change.rst, changelog.d/3484.change.rst, setuptools/build_meta.py, setuptools/command/editable_wheel.py, setuptools/tests/test_build_meta.py, setuptools/tests/test_editable_install.py
*(Another PR related to the PEP 660 implementation, carried out in the feature/pep660 branch)*
- Add a temporary `compat` mode that will try (best effort) to emulate the same "static `.pth`" file produced by `python setup.py develop`.
This was originally suggested in https://discuss.python.org/t/help-testing-pep-660-support-in-setuptools/16904
Closes 
[PR docs]:
=> PEP 660: Add transitional `compat` editable install mode

docs/userguide/development_mode.rst
*(Another PR related to the PEP 660 implementation, carried out in the feature/pep660 branch)*
Follow up on https://github.com/pypa/setuptools/pull/3484 and the discussion in https://discuss.python.org/t/help-testing-pep-660-support-in-setuptools/16904
Update docs on the `userguide/development_mode` page to mention:
- `compat` mode
- limitations in terms of accessing files outside of the package directory.
- limitations in terms of `__file__` and `__path__` exact values.
- implementation mechanisms
Closes 
[PR docs]:
=> PEP660: Update editable docs to mention `compat` mode, implementation, and other limitations.

setuptools/extension.py
Mentions the DistutilsPlatformException introduced by pypa/distutils#150 in the documentation for `Extension`.
May want a closer match to the exception message to make it easier to search, but this should help.
Inspired by #3450.
- [NA] News fragment added in [`changelog.d/`].
[PR docs]:
=> DOC: Mention that Extension(..., runtime_library_dirs) raises on Windows

docs/userguide/pyproject_config.rst
It looks like that[PEP 660](https://peps.python.org/pep-0660/)  is implemented in pip 21.3 (see https://pip.pypa.io/en/stable/news/#v21-3).
Or isn't it still recommended to do `pip install -e` without `setup.py`? 🤔
=> [Docs] Add two footnotes about PEP 660 support

docs/userguide/extension.rst
Looks like the name of an exception from the distutils made into the doc. Small formatting update on top.
=> docs: Fix reference to old exception name

setuptools/config/setupcfg.py, setuptools/tests/config/test_setupcfg.py
Fixes: https://github.com/pypa/setuptools/issues/3467
See the linked issue, all details are there.
Closes https://github.com/pypa/setuptools/issues/3467
[PR docs]:
=> Add warning for potential extras_require misconfiguration

changelog.d/3487.misc.rst, setuptools/config/pyprojecttoml.py, setuptools/tests/config/test_pyprojecttoml.py
Based on the following discussions:
- https://github.com/pypa/packaging.python.org/pull/1031#issuecomment-1127214128
- https://github.com/pypa/packaging-problems/issues/604
it seems that people are having a hard time finding information about validation error due to the long traceback and debug info.
- Make the most relevant information to fix a `pyproject.toml` error easier to spot:
- Add the error summary to the exception message itself (this way it is shown at the bottom of the traceback)
- Avoid displaying debugging information in the case the whole `project` table is considered invalid (too verbose, and probably the error is just a missing/misnamed field).
- Modify the tests to reflect the changes listed above.
Closes  …
=> Improve `pyproject.toml` validation messages

docs/userguide/pyproject_config.rst, docs/userguide/quickstart.rst
- Update notes regarding `setup.py` and editable installs
- Remove comment about link files in the development mode
- Update comment that implicitly suggests that either `setup.py` or `setup.cfg` is required in a project.
Closes 
[PR docs]:
=> Update docs to better reflect the implementation of PEP 660

docs/userguide/dependency_management.rst
This PR adds a section on direct URL dependencies (AKA direct reference dependencies) to Setuptools' dependency management docs.
It also pulls some information out of an "attention" box at the top which I felt was more appropriate for the text's main body and moves the actual "attention" part into the newly added section where it (IMHO) belongs.
Closes #3489 
[PR docs]:
=> Add docs section on direct URL dependencies

setup.cfg, setuptools/build_meta.py, setuptools/command/editable_wheel.py
The beginning of copying the old `dholth/setuptools_pep660` implementation into the tree.
Run `python setup.py egg_info` then `python setup.py editable_wheel -d /tmp/` to see the output editable wheel.
[PR docs]:
=> include pep660 proof of concept

changelog.d/3503.misc.rst, setuptools/command/build_py.py, setuptools/tests/test_editable_install.py
In #3500, it seems that `pbr` is automatically trying to add `.egg_info/SOURCES.txt` into the default list of data files.
However `editable_wheel` uses a `.egg_info` directory that is external to the project root, which may cause errors with the `pbr` approach.
- Filter external `.egg-info` files when analysing manifest in `build_py`.
Closes #3500
[PR docs]:
=> Prevent errors in editable install when plugins include `.egg_info/SOURCES.txt`

docs/userguide/development_mode.rst
`PATHONPATH` --> `PYTHONPATH`
Fixed a typo
Closes #3507
- N/A ?
- Seems unnecessary ?
[PR docs]:
=> Typo in user guide: development mode

CHANGES.rst, changelog.d/3506.misc.rst, setuptools/command/build.py, setuptools/command/editable_wheel.py, setuptools/tests/test_editable_install.py
The #3501 issue seems to represent a class of problems with plugins assuming that `build_py` don't run during editable installs (as it was the case with the `develop` command), or that `build_py` will always copy the files for the temporary build folder.
The idea of this PR is to prevent this class of problems from causing disruption in the environment.
- When running `build_py` during editable installs, capture errors and use a warning to indicate what is the most appropriate migration path.
Closes #3501
[PR docs]:
=> Avoid crashing on `build_py` errors during editable installs

changelog.d/3512.misc.rst, setuptools/command/editable_wheel.py, setuptools/tests/test_editable_install.py
- Allow editable installs for flat-layouts to handle configurations that result in an accidental namespace package as explained in https://github.com/pypa/setuptools/issues/3504#issuecomment-1213031579.
- The idea here is to emulate the behaviour of a regular installation.
Closes #3504
[PR docs]:
=> Handle accidental virtual namespaces in editable install

docs/userguide/development_mode.rst
The heading "How editable installations work?" either contains a typo (the question mark should be omitted), or else the heading as written is ungrammatical because it is missing a word ("How **do** editable installations work?").
Other headings in this section are not written as questions, so this commit removes the question mark, based on the assumption that the question mark is extraneous.
- <s>[ ] Changes have tests.</s> Not relevant.
This is such a small typo that it does not seem to warrant a changelog.d file.
=> Remove extraneous question mark in section heading

changelog.d/3515.misc.rst, setuptools/command/build_ext.py, setuptools/tests/test_build_ext.py
- Don't try to copy the files of an optional extension if its build has failed.
Closes #3510
[PR docs]:
=> Prevent optional extensions from crashing editable builds

changelog.d/3517.misc.1.rst, changelog.d/3517.misc.2.rst, setuptools/command/build_py.py, setuptools/command/editable_wheel.py, setuptools/tests/test_editable_install.py
Motivated by `pyca/cryptography` use case.
1. Ensure commands are finalized, to ensure `plat_name` is set.
2. Filter out temporary source files and prevent `setuptools` for attempting to consider them as part of the data_files/package_data list
Closes #3513
[PR docs]:
=> Fix other problems with editable installs

changelog.d/3519.doc.rst, docs/references/keywords.rst
Updates the keywords note about editable installations requiring a minimal `setup.py` file after the release of `64.0.0`
[Link to Keywords docs section with PR docs](https://setuptools--3519.org.readthedocs.build/en/3519/references/keywords.html)
[PR docs]:
=> Update keywords note on editable installs

changelog.d/3526.misc.rst, setuptools/command/editable_wheel.py, setuptools/tests/test_editable_install.py
- Set the `inplace` flag during editable installs if the build subcommand has this attribute.
Closes #3522
[PR docs]:
=> Ensure `build_ext` inheriting directly from `distutils` run an in-place build during editable install

changelog.d/3528.misc.rst, setuptools/build_meta.py, setuptools/tests/test_build_meta.py, setuptools/tests/test_editable_install.py
PEP 517 does not guarantee that `metadata_directory` is not used to store other `.dist-info` directories.
- Replace globing with directory walk when looking for `.dist-info`/`.egg-info` directories.
Closes #3523
[PR docs]:
=> Fix `build_meta` when `metadata_directory=='.'`

docs/pkg_resources.rst
- Change paragraph about `pkg_resources` replacement to admonition, to make it more visible.
Closes 
[PR docs]:
=> Make `pkg_resources` warning more visible

CHANGES.rst, changelog.d/3538.doc.rst, docs/userguide/development_mode.rst
PR #3414 added support for disabling the new PEP660 editable install hooks. However the documentation and changelog mentions didn't match the implementation.
Before:
- The implementation used: `SETUPTOOLS_ENABLE_FEATURES`
- The changelog said to use: `SETUPTOOLS_ENABLE_FEATURE` (notice the missing "S")
- The docs said to use: `SETUPTOOLS_USE_FEATURE`
This caused confusion in #3535, since the testcase there used the form mentioned in the changelog, which doesn't do anything.
Now, the changelog and docs both say to use `SETUPTOOLS_ENABLE_FEATURES`.
=> Correct docs on how to use the `legacy-editable` mode

changelog.d/3551.misc.rst, setuptools/command/editable_wheel.py, setuptools/tests/test_editable_install.py
- Ensure that the finder will not result in circular imports when a missing module coincidentally has the same name as its parent module.
Closes #3550.
[PR docs]:
=> Editable finder: Avoid recursion when missing module has the same name as parent

changelog.d/3553.change.rst, pytest.ini, setuptools/_distutils/_msvccompiler.py, setuptools/_distutils/bcppcompiler.py, setuptools/_distutils/ccompiler.py, setuptools/_distutils/cygwinccompiler.py, setuptools/_distutils/sysconfig.py
- Suppress warnings in deprecated msvc compilers
- Fix, again, finding headers during cross compiling
- Rename _mangle_base to _make_relative and add documentation about its purpose. Ref pypa/distutils#169.
- In _make_relative, remove deprecation warning. Ref pypa/distutils#169.
- Extract method for _make_out_path.
- In _msvccompiler, only override _make_out_path
- In _msvccompiler, re-use _make_relative.
- Extract property for mapping src extensions to out extensions.
- Extract property for out_extensions in _msvccompiler
- Deprecate bcppcompiler. Support for Borland C++ compiler was dropped for compiling Python in python/cpython#66782 (2014) and the borlandc.org web site no longer references a compiler. Best I can tell, this compiler hasn't been released for 22 years. Surely no one is …
=> Merge with pypa/distutils@22b9bcf

changelog.d/3561.misc.rst, setuptools/command/editable_wheel.py, setuptools/tests/test_editable_install.py
- Change matching condition in editable hook.
Closes #3561
[PR docs]:
=> Prevent accidental partial name matching in editable hooks

changelog.d/3547.change.rst, setuptools/config/pyprojecttoml.py, setuptools/discovery.py, setuptools/tests/test_config_discovery.py
The `name` attribute of a `Distribution` object is used by the command-line processing system and is not intended to hold the name of the distribution itself. Setting it to the name will cause the command-line processing system to have a bad time.
Fixes #3545
=> Remove inadvertent splatting of the name attribute

changelog.d/README.rst
The link to towncrier philosophy section displays a 404 error. So this patch updates the broken URL to the correct one.
I think no news are necessary but I can add one if you want.
=> Fix towncrier URL

changelog.d/3609.change.rst, docs/deprecated/distutils/configfile.rst, setuptools/_distutils/dist.py, setuptools/_distutils/tests/test_dist.py, setuptools/_distutils/tests/test_util.py, setuptools/_distutils/util.py
- Revert "Exclude Python 3.11 on macOS due to lack of wheels. Ref pypa/distutils#165."
- Restore metadata tests (not discovered due to class name).
- Add DISTUTILS_EXTRA_CONFIG option for passing setup.cfg overrides during build
- Fix name in test
- Prefer monkeypatch for setting environment variable
- Use tmp_path and jaraco.path.build to build files.
- Use functools.lru_cache to memoize check_environ.
- Use pathlib for generating paths and generate the paths in a separate function, consolidating 'is_file' check.
- Update docs to reference environment variable.
- Rename environment variable to DIST_EXTRA_CONFIG, decoupling it from the name of the implementation.
- Simplify logic in test_custom_pydistutils
- Inline variables used once
- Remove meaningless dot from config files
- Extract a …
=> Merge with distutils@d82d926

changelog.d/3617.misc.rst, setuptools/_distutils/dist.py, setuptools/_distutils/sysconfig.py, setuptools/_distutils/tests/py37compat.py, setuptools/_distutils/tests/py38compat.py, setuptools/_distutils/tests/test_archive_util.py, setuptools/_distutils/tests/test_build_ext.py, setuptools/_distutils/tests/test_core.py, setuptools/_distutils/tests/test_dist.py, setuptools/_distutils/tests/test_filelist.py, setuptools/_distutils/tests/test_spawn.py, setuptools/_distutils/tests/test_sysconfig.py
- Use path.Path for changing the cwd temporarily.
- Remove needless assert renderings. Any decent test runner will provide this detail.
- Remove reference to duplicate issue.
- Refactor _is_python_source_dir using pathlib.
- Use 'samefile' to check for same file, because they may not be the same path. Fixes #180.
- Split test into two tests.
- Use pathlib
- Remove special case for TestCore.write_setup.
- Replace TESTFN with temp_file fixture.
- Remove 'cleanup_testfn', unused.
- Remove distracting comments
- In test_sysconfig, prefer fixtures to TESTFN.
- Remove cleanup_testfn, no longer used.
- Replace TESTFN with fixture.
- Remove empty logic branch.
- Use path.Path for changing the cwd temporarily.
- Remove reliance on TESTFN in test_dist
- Remove TESTFN from py38compat, no longer …
=> Merge with pypa/distutils@6852b20

changelog.d/3613.misc.rst, setuptools/config/expand.py, setuptools/tests/config/test_expand.py
Closes #3612
I was able to run my test before/after the patch to ensure it test it.
[PR docs]:
=> expand: Give bytes to ast.parse to let it discover encoding cookie.

setuptools/logging.py, setuptools/tests/test_build_ext.py, setuptools/tests/test_distutils_adoption.py, setuptools/tests/test_manifest.py
=> Improve compatibility with distutils proper logging

changelog.d/3419.doc.rst, docs/userguide/distribution.rst
Updated example versions on the [Specifying Your Project’s Version]() page to be PEP440-compliant.
I used the `is_canonical` function from [PEP-440 Appendix B](https://peps.python.org/pep-0440/#appendix-b-parsing-version-strings-with-regular-expressions) to verify that new version strings are compliant.
Closes #3419.
[PR docs]:
=> Update user guide's example versions to be PEP440-compliant

setuptools/command/test.py, setuptools/monkey.py
setuptools does not support python2 anymore.
This PR removes two cases where the code checks if python release is version 2.
I runned `tox` and get one error before and after this patch.
I don't think news are useful because it does not affect end-users.
=> Remove python2 cases

setuptools/config/expand.py, setuptools/tests/config/test_expand.py
Using `str.startswith()` for sandboxing file access has an edge case where someone can access files outside the root directory. For example, consider the case where the root directory is "/home/user/my-package" but some secrets are stored in "/home/user/my-package-secrets". Evaluating a check that "/home/user/my-package-secrets".startswith("/home/user/my-package") will return True, but the statement's intention is that no file outside of "/home/user/my-package" can be accessed.
Using `pathlib.Path.resolve()` and `pathlib.Path.parents` eliminates this edge case.
See https://salvatoresecurity.com/preventing-directory-traversal-vulnerabilities-in-python/ for more details.
1. If there is an infinite loop in the directory structure, `pathlib.Path.resolve()` will raise a `RuntimeError`.
2. …
=> Catch an edge case in expand._assert_local()

changelog.d/3624.change.rst, setuptools/command/editable_wheel.py
- Modify the logic deciding if the package has a simple layout to support projects composed only by top-level modules (no packages).
Closes #3624
[PR docs]:
=> Fix layout detection for projects with no packages.

setuptools/tests/test_distutils_adoption.py
This is an imperfect way to make the tests pass on Python 3.12.
Long-term goal is to deprecate the stdlib option,
see https://github.com/pypa/setuptools/issues/3625
=> Skip stdlib distutils tests on Python 3.12

changelog.d/3638.misc.rst, pkg_resources/tests/test_markers.py, pkg_resources/tests/test_pkg_resources.py, setup.cfg, setuptools/tests/test_bdist_deprecations.py, setuptools/tests/test_build_clib.py, setuptools/tests/test_easy_install.py, setuptools/tests/test_packageindex.py, setuptools/tests/test_register.py, setuptools/tests/test_upload.py
Consistently use unittest.mock in tests
- Some tests used unittest.mock from the standard library
- Some tests used mock from PyPI
- Some tests tried to import unittest.mock with a fallback to mock (the import never fails on Python 3.7+, older Pythons are not supported)
[PR docs]:
=> Consistently use unittest.mock in tests

CHANGES.rst, changelog.d/3569.misc.rst, docs/userguide/development_mode.rst, setuptools/build_meta.py, setuptools/command/editable_wheel.py
This was initially motivated by #3557.
- Added warning about CWD interfering with editable installs
- Listed CWD entries overshadowing installation, as a limitation in the editable installation docs.
- Fixed existing RST syntax on changelog.
- Fixed warning about `install` command during editable install.
[PR docs]:
=> Improve warnings in editable install

.github/workflows/main.yml
I noticed that the way the `check` job is integrated is not what's recommended. It should serve as a single status that can tell people whether all the required tests have passed or not.
So in this patch, I improve the dependency graph to do just that, while preserving the expectation that the integration tests must be allowed to be skipped.
https://github.com/marketplace/actions/alls-green#why
=> Make the `check` job a central gate in the CI

setuptools/tests/config/test_apply_pyprojecttoml.py
- Adds tests to ensure setuptools PEP 621 support handles UTF-8 names for maintainers (related: #3663)
Closes 
[PR docs]:
=> Ensure `pyproject.toml` accepts UTF-8 in maintainers

docs/userguide/declarative_config.rst, docs/userguide/pyproject_config.rst
Motivated by https://github.com/pypa/setuptools/issues/1951#issuecomment-1302465693
- Highlight in docs: 'attr' directive needs MANIFEST.in config / SCM plugin to work properly
Closes 
[PR docs]:
=> Highlight in docs: 'attr' directive needs MANIFEST.in config / SCM plugin

setuptools/tests/config/test_apply_pyprojecttoml.py
This is a follow-up for PR #3666.
The current `email.headerregistry.Address` implementation only allows RFC 5322 but the world is slowly moving towards supporting the international emails too. This patch adds a test case that is currently expected to fail but hopefully should pass once the support for RFC 6532 is implemented in the standard library.
Refs:
* https://datatracker.ietf.org/doc/html/rfc6532
* https://en.wikipedia.org/wiki/International_email
[PR docs]:
=> Add a test for maintainers w/ international emails

.github/workflows/main.yml
This ensures that the actual job env details are included as Codecov flags. It uses the exact Python patch version instead of the job matrix definition factors which may not be compatible with the acceptable flag syntax sometimes (like `~3.11.0-0` wouldn't be).
[PR docs]:
=> Upload accurate coverage flags from unit tests job

setuptools/tests/test_manifest.py
Currently some tests in test_manifest only run for `SETUPTOOLS_USE_DISTUTILS=stdlib` because they rely on the old logging infrastructure.
In https://github.com/pypa/distutils/pull/192 I also noticed that if `distutils.log.Log` is reinstated for backward compatibility, these tests will fail.
- This PR "modernizes" test_manifest a little bit to not rely on the old logging infrastructure.
Closes 
[PR docs]:
=> Modernize `test_manifest` to use new log infra

changelog.d/3693.bugfix.rst, setuptools/_distutils/log.py
Fixes #3693.
- Add distutils.log.Log back for compatibility
- Ignore deprecation warning in tests
Closes 
[PR docs]:
=> Merge pypa/distutils@3e9d47e with fix for distutils.log.

.github/workflows/main.yml
- Update versions of:
- `actions/checkout`
- `actions/setup-python`
- `cygwin/cygwin-install-action`
Closes 
[PR docs]:
=> Update versions of outdated GHA

changelog.d/3678.change.rst, setuptools/command/build_clib.py, setuptools/tests/test_build_clib.py
Sort sources in `build_clib` command.
Closes https://github.com/pypa/setuptools/issues/3678
=> Make clib build reproducible by sorting sources

setuptools/_entry_points.py, setuptools/tests/test_egg_info.py
- Wrap exception in `setuptools._entry_points.ensure_valid` to display a message that is easier to understand.
Closes #3682 
[PR docs]:
=> Improve exception/traceback when invalid entry-points are specified

docs/deprecated/distutils-legacy.rst
- With the move to `setuptools/_distutils` people might be confused why their `distutilts/distutils.cfg` does not work.
- This PR adds clarification about that to the docs.
Closes #3681 
[PR docs]:
=> Add note about global `distutils.cfg`

setuptools/dist.py
Those changes fix the issue reported in #1631. From a simple test case, the command `bdist_wheel` displayed error messages:
```
Traceback (most recent call last):
File "C:\dev\Python311\Lib\logging\__init__.py", line 1113, in emit
stream.write(msg + self.terminator)
ValueError: underlying buffer has been detached
```
Python 3.7 offers a good alternative to change the encoding of the standard output: io.TextIOWrapper.reconfigure (). This alternative solves the error messages.
[PR docs]:
=> Fix logging errors: 'underlying buffer has been detached' (pypa#1631)

docs/userguide/development_mode.rst, launcher.c, setuptools/tests/test_build_meta.py
Fix typos found by [codespell](https://github.com/codespell-project/codespell) in documentation, code comments, and name of a variable that is actually not used.
[PR docs]:
=> Fix typos found by codespell

docs/conf.py, setuptools/command/upload_docs.py, setuptools/dist.py, setuptools/tests/script-with-bom.py, setuptools/tests/test_manifest.py, setuptools/tests/test_msvc14.py, setuptools/tests/test_wheel.py
Python 3 assumes the encoding is UTF-8 by default, and so do or should do tools such as text editors when opening Python files.
No need to explicitly set `*- coding: utf-8 -*-`.
=> The default encoding of Python sources is UTF-8

docs/build_meta.rst, docs/deprecated/distutils/commandref.rst, docs/deprecated/distutils/configfile.rst, docs/deprecated/distutils/extending.rst, docs/deprecated/zip_safe.rst, docs/userguide/entry_point.rst, docs/userguide/quickstart.rst, launcher.c
Remove trailing spaces at end of line, and empty lines at end of file.
[PR docs]:
=> Get rid of trailing spaces, mainly in docs

docs/userguide/development_mode.rst
The last character of `virtualenᴠ` is not an ASCII `v`, but the Unicode homglyph "Latin Letter Small Capital V" (U+1D20) `ᴠ`:
```python
>>> 'ᴠ'.encode("unicode_escape")
b'\\u1d20'
>>> 
>>> 'v'.encode("unicode_escape")
b'v'
>>> 
```
[PR docs]:
=> Fix non-ASCII homoglyph of `v`

docs/build_meta.rst
Right now tabs and spaces are mixed:
Closes 
[PR docs]:
=> Fix spacing (mixed spaces and tabs) in build_meta.rst

setuptools/build_meta.py, setuptools/tests/test_config_discovery.py
- Modify temporary directory name to be hidden from auto-discovery
Closes #3692
[PR docs]:
=> Avoid interfering with auto-discovery when creating temporary directories

changelog.d/3709.misc.rst, setuptools/logging.py, setuptools/tests/test_logging.py
As `distutils.log.Log` was backfilled for compatibility we no longer can use this as a condition.
- Replace protection condition.
Closes #3707 
[PR docs]:
=> Replace condition to patch `distutils.dist.log`

docs/build_meta.rst
I followed the documentation on dynamic build dependencies, which is apparently incorrect. See https://github.com/maxbachmann/RapidFuzz/issues/303. This fixes the passage in the documentation.
[PR docs]:
=> fix documentation for dynamic build dependencies

setuptools/tests/test_editable_install.py
It seems that the latest version of `pip_run` can no longer handle `str` objects in `inject_sitecustomize` (see
`https://github.com/jaraco/pip-run/commit/30c62a0eadd5af422709e75993ff19a39fe69733`).
- Avoid converting argument of `pip_run.launch.inject_sitecustomize` into `str`
Examples of previously failing tests: https://github.com/pypa/setuptools/actions/runs/3855567261/jobs/6570754102
[PR docs]:
=> Update failing test due to latest versions of `pip_run`

docs/userguide/pyproject_config.rst
=> Docs: Modify table for tool.setuptools.dynamic to mention content-type

docs/userguide/ext_modules.rst
The first instance of `LDFLAGS` is removed instead of the second to match the ordering style of the preceding environment variables (`CC`, `CPP`, `CXX`, `LDSHARED`). This repeat was introduced in PR https://github.com/pypa/setuptools/pull/3368 in what seems like a very easy to make copy and paste typo.
- [N/A] Changes have tests
- [N/A] News fragment added in [`changelog.d/`].
_(See [documentation][PR docs] for details)_ (Skipping this as I don't think you want typo corrections in the CHANGELOG, but I can add if desired.)
[PR docs]:
=> docs: Remove repeated mention of LDFLAGS environment variable

docs/userguide/declarative_config.rst
This fixes an error that I had submitted in #3712 to move `python_requires` to the `[options]` section in the `setup.cfg` example.
=> DOC: fix section for python_requires in setup.cfg

changelog.d/3779.change.rst, docs/userguide/declarative_config.rst, docs/userguide/pyproject_config.rst, setuptools/command/egg_info.py, setuptools/config/_apply_pyprojecttoml.py, setuptools/config/pyprojecttoml.py, setuptools/config/setupcfg.py, setuptools/dist.py, setuptools/tests/test_sdist.py
This PR is an alternative to #3771. Both solve the same problem, but use different implementations...
- Add a "protected" attribute to the Distribution class: `_referenced_files`
- During config expansion, populate this attribute when the file directive is used
- Use the same approach for `pyproject.toml`'s `project.readme` and `project.license.file`.
Closes #2821 #3570
[PR docs]:
=> Automatically add files referenced by configuration to sdist

changelog.d/3685.change.rst, pkg_resources/__init__.py
- In Python 3.3+ `importlib.machinery.FileFinder` is always present, therefore we no longer need to keep the conditional
- In Python 3.12+ `pkgutil.ImpImporter` is removed, so we need a conditional to avoid using it directly.
(Potentially) closes #3631
- `pkg_resources` uses `pkgutil.get_importer` to find out which importer is responsible for importing an specific file.
- I don't know if there is a situation in `Python >= 3.7, < 3.12` where this function can return an instance of `pkgutil.ImpImporter`.
- In the case `pkgutil.get_importer` never returns `pkgutil.ImpImporter`, I believe we could simply remove `pkgutil.ImpImporter` from the namespace handler and finder registries in `pkg_resources` (but don't quote me on that 😅).
- Issue #3631 also indicates that the `find_module` will be …
=> `pkg_resources`: Flip import conditionals around `pkgutil.ImpImporter` and `importlib.machinery.FileFinder`

docs/artwork.rst, docs/build_meta.rst, docs/deprecated/easy_install.rst, docs/userguide/package_discovery.rst
Use the Sphinx `:pep:` role to link to PEPs in docs:
https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-pep
This means they'll link directly to their new home at https://peps.python.org/ rather than going via redirect at the old https://www.python.org/dev/peps/
And update the non-docs links to the new home.
- [n/a?] News fragment added in [`changelog.d/`].
[PR docs]:
Is a changelog needed for this?
=> Docs: Link directly to PEPs

changelog.d/3782.misc.rst, setuptools/config/pyprojecttoml.py, setuptools/tests/test_sdist.py
- Transform simple strings into lists before passing it on to other functions.
Closes #3781
[PR docs]:
=> Account for file directive with single string (instead of list) in `tool.setuptools.dynamic` (`pyproject.toml`)

setuptools/tests/test_dist_info.py
Fix the install_requires used in test_dist_info to use the dangling syntax, in order to correctly handle markers.  This fixes syntax error when parsed by packaging-22.0+, as well as setuptools warning:
```
UserWarning: One of the parsed requirements in `install_requires` looks like a valid environment marker: \'sys_platform != "linux"\'
Make sure that the config is correct and check https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#opt-2
warnings.warn(msg, UserWarning)\n'
```
[PR docs]:
=> Fix dependency syntax error in test_dist_info

setuptools/tests/config/test_setupcfg.py
Fix the two "marker"-alike cases (for package `python_version`) for test_nowarn_accidental_env_marker_misconfig to use `<3` rather than `<'3'`.  The latter maps to the version `'3'` which is not a valid version and therefore causes an error with packaging-22.0+.
See the discussion at
https://github.com/pypa/setuptools/commit/506e7e7e1cac6a5d534184d35a20a73e9dd58045#r97577660
[PR docs]:
=> Fix version syntax in test_nowarn_accidental_env_marker_misconfig

changelog.d/3741.breaking.rst, setuptools/monkey.py, setuptools/msvc.py
Remove the msvc hack that was applied if numpy.distutils were loaded prior to Numpy 1.11.2.  These versions date back to June 2016 and no longer build with Python 3.7.  At the same time, the hack relies on packaging.version.LegacyVersion that is removed in packaging 22.0.
[PR docs]:
=> Remove msvc hack for Numpy < 1.11.2

changelog.d/3822.misc.1.rst, changelog.d/3822.misc.2.rst, docs/userguide/development_mode.rst, setuptools/command/dist_info.py, setuptools/command/editable_wheel.py, setuptools/tests/test_editable_install.py
`pip` no longer fallback to `setup.py develop` which makes setting `SETUPTOOLS_ENABLE_FEATURES="legacy-editable"` useless.
Moreover it is been a while that the PEP 660 implementation landed, so the main problems are already known.
I think it is time to allow the build errors to propagate (instead of having a "catch all" approach), but instead provide up-to-date debugging advice.
- Don't catch all the errors inside `editable_wheel`. Instead provide advice on how to debug it.
- Test code path with the advice.
Closes 
[PR docs]:
=> Improve `editable_wheel` debugging tips.

changelog.d/3434.deprecation.rst, docs/references/keywords.rst, pkg_resources/__init__.py, pkg_resources/tests/test_resources.py, pytest.ini, setuptools/dist.py
I think it makes sense to add a warning recommending the migration to PEP 420. `pkg_resources` is in its majority "discouraged", isn't it?
- Add a `DeprecationWarning` to `pkg_resources.declare_namespace`.
- By default, Python will not show `DeprecationWarning` to the final user (unless they opt-in for something more strict, in which case they should be familiar with more complex warning filters), so this approach should be OK. 
Closes 
[PR docs]:
=> Should we add a `DeprecationWarning` to `pkg_resources.declare_namespace`?

pytest.ini, setuptools/_normalization.py, setuptools/_path.py, setuptools/_reqs.py, setuptools/command/bdist_egg.py, setuptools/command/develop.py, setuptools/command/dist_info.py, setuptools/command/editable_wheel.py, setuptools/command/egg_info.py, setuptools/command/install_egg_info.py, setuptools/command/install_scripts.py, setuptools/dist.py, setuptools/installer.py, setuptools/version.py, setuptools/wheel.py
This is an attempt to reduce the usage of `pkg_resources` (and in some places to delay the associated import[^1]).
The approaches used are:
- Whenever possible use `packaging` and `importlib.metadata`
- Create suitable replacements in the modules `_normalization`, `_path`
- Centralize the import/usage of `pkg_resources` to as few modules as possible (ideally only the ones that inevitably have to traverse deprecated code paths).
- Delay importing `pkg_resources` in an attempt saving the import cost when the module is not necessary.
---
* 60506348 - Replace `pkg_resources` in `version.py`
* ec238c4a - Extract normalization functions from `editable_wheel` and `dist_info` into `_normalization`
* 3c48e7c1 - Prefer `_normalization` to `pkg_resources` in `develop.py`
* daadc5af - Prefer …
=> Reduce usage of `pkg_resources`

changelog.d/3823.misc.rst, setuptools/command/egg_info.py
- Fixes error in https://github.com/pypa/setuptools/actions/runs/4167744594/jobs/7214043564
Closes 
[PR docs]:
=> Fix error when integrating with pip

docs/userguide/development_mode.rst
- Document limitation of editable installs on docs.
Closes 
[PR docs]:
=> Mention limitation in editable docs

docs/userguide/extension.rst
This PR fixes a typo in `docs/userguide/extension.rst` that actually changes the meaning of this paragraph in an important way. Had me wondering a bit about this part's meaning when reading the docs :)
=> Fix typo in docs/userguide/extension.rst

changelog.d/3843.change.rst, docs/pkg_resources.rst, pkg_resources/__init__.py, pytest.ini, setuptools/tests/contexts.py
=> Officially deprecate pkg_resources

changelog.d/3594.change.rst, changelog.d/3836.misc.rst, setuptools/discovery.py, setuptools/tests/test_find_packages.py
Added htmlcov to FlatLayoutPackageFinder.DEFAULT_EXCLUDE.
Closes https://github.com/pypa/setuptools/issues/3594
#3715 still remains issue:
<details>
<summary>The command: `pip install --editable` still fails:</summary>
```console
Obtaining file:///workspace
Installing build dependencies ... done
Checking if build backend supports build_editable ... done
Getting requirements to build editable ... error
error: subprocess-exited-with-error
× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> [16 lines of output]
/tmp/pip-build-env-fyn78agv/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
warnings.warn(msg, _BetaConfiguration)
error: Multiple …
```
=> Hotfix add htmlcov to flat layout package finder.default exclude

pkg_resources/__init__.py
In `#3772` we learned that some users have been finding trouble to install packages that follow PEP 440 if another package that does not follow PEP 440 is already installed. This is caused by `pkg_resources` automatically "activating" an environment with all the installed distributions and trying to sort them when `setup.py install` or `setup.py develop` is invoked[^1].
[^1]: So far those were the circumstances I could identify, but there might be others.
- When calculating the `hashcmp` string in `pkg_resources`, use a fallback sanitized version in the case of parsing errors.
I tested this is working based on the reproducer provided in a [commend in #3772](https://github.com/pypa/setuptools/issues/3772#issuecomment-1429496548):
```bash
> docker run --rm -e DEBIAN_FRONTEND=noninteractive …
```
=> Make `pkg_resources` more forgiving of non-compliant versions

docs/pkg_resources.rst
Just fixed a link so it takes you to the correct page, not the `importlib` docs homepage.
=> Docs: Fix link to importlib.resources in the docs

changelog.d/3804.change.rst, setuptools/tests/test_wheel.py, setuptools/wheel.py
In `wheel.py:Wheel.is_compatible` we called `sys_tags` each time to get the list of supported tags. Now we call this once, and cache the result in a simple variable. This drastically speeds up checking the compatibility of hundreds of wheels.
Closes #3804
[PR docs]:
=> Cache supported tags for wheels.

changelog.d/3846.misc.rst, setuptools/discovery.py
- Add pruning heuristics to `PackageFinder` based on exclude.
This is an optimisation to avoid traversing the file system when a large amount of files is present.
Closes (partially) #3845
[PR docs]:
=> Add pruning heuristics to `PackageFinder` based on exclude

docs/userguide/entry_point.rst
Configured indicates that the function code's itself would be configured, not that it is used by an external party. Switch verb to "used" to be clearer as to how the function is being used.
=> Clarify language re: function arguments

changelog.d/3893.doc.rst, docs/build_meta.rst
Before this patch, the documentation suggested the package authors to declare a fixed set of hooks inherited from setuptools. But this approach turned out non-future proof. Over time, as `setuptools` added support for editable installs, it introduced new hooks per PEP 660. But if one were to follow the outlined example, they'd end up with an in-tree build backend that does not support editable installs, nor would it re-export any hooks that might be added in future versions of setuptools, implementing any new standards that may emerge over time.
This change demonstrates an approach that would allow the thin wrapper authors to get the new hooks that setuptools may add over time.
Ref: https://github.com/ansible/ansible/pull/79606#discussion_r1080753862
_(See [documentation][PR docs] for …
=> 🎨📝 Fix in-tree PEP 517 backend wrapper example

changelog.d/3859.doc.rst, docs/userguide/quickstart.rst
Add a note explaining that the `wheel` requirement that used to be historically used in documentation was incorrect.  This also explains why it can frequently be found in existing projects, and what problems it causes.  I find myself repeatedly explaining it, so I think having a single official source would be better.
[PR docs]:
=> docs: Add a note about historical `wheel` use in `requires`

changelog.d/3915.misc.rst, setuptools/tests/fixtures.py, setuptools/tests/test_virtualenv.py, setuptools/version.py
Since version v20.23.0, `virtualenv` will no longer include `wheel` and `setuptools` in the created folders.
Some tests in the setuptools test suite assume that these packages are always present. So we need to adequate these tests.
**EDIT**: Apparently we are also having problems with `__version__`. It seems that the code path triggered in the "unhappy path" that results in `__version__ = "unknown"`.
Since `unknown` is not a valid PEP 440, it causes problem. I changed this fallback to be PEP 440-compliant.
This problem might be related to the race conditions between `importlib.metadata` (used by pytest and plugins) and `egg_info` (that writes `setuptools.egg-info/PKG-INFO`).
Closes  …
=> Adequate venv fixtures to the latest change in virtualenv for Python 3.12

setup.cfg
Workaround for #3921.
CC @lazka : Would you be willing to look into what it will take to make a rust compiler available in the test_cygwin?
=> Disable cygwin for now

setuptools/tests/test_easy_install.py
Python 3.12, and earlier via security backports now issue an DeprecationWarning when calling tarfile.extractall without an extraction filter set. Since the only place we've called extractall is literally right after we've created the archive, use a fully trusted filter. This can be replaced with a filter argument to extractall in future.
=> tests: Add extraction_filter for tarfile

setuptools/command/easy_install.py, setuptools/command/install.py
`pypa/build` is mentioned twice in one sentence.
@abravalheri from #3849
=> Avoid duplication in warning text

docs/userguide/package_discovery.rst
This PR adjusts inconsistent wording in the package discovery documentation. See the referenced issue 
Closes #3954
=> fixes spelling mod->module

setup.cfg, tox.ini
Originally, I just pushed this commit to main before I realized it causes failures on Python 3.8 when something attempts to construct a requirement, but creates the wrong syntax:
```
File "/home/runner/work/setuptools/setuptools/.tox/py/lib/python3.8/site-packages/packaging/requirements.py", line 37, in __init__
raise InvalidRequirement(str(e)) from e
packaging.requirements.InvalidRequirement: Expected end or semicolon (after URL and whitespace)
execnet@ git+https://github.com/jaraco/execnet@bugfix/195-encodingwarning; extra == "testing"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```
The error message is misleading. The problem is that [PEP 508](https://peps.python.org/pep-0508/) specifies `url_req` as
```
url_req       = name wsp* extras? wsp* urlspec wsp+ …
```
=> Bypass encoding warnings in execnet

setup.cfg, setuptools/tests/test_editable_install.py, setuptools/tests/test_logging.py, tox.ini
In #3976 it was identified that an indirect dependency on `pydantic-core` was causing `pip` to fail when installing `setuptools[testing]`. This is due to the fact that `pydantic-core` uses Rust and does not publish pre-built wheels for all platforms (see pydantic/pydantic-core#773).
The following changes were implemented:
- Remove `pip-run` as dependency of `setuptools[testing]`.
This PR builds on top of #3976 as an attempt to fix the errors in the test suite.
Closes 
[PR docs]:
=> Remove test dependency on `pip-run` for Cygwin

tox.ini
The fix was just included in a release, and the branch this was installing from has been deleted, so it was causing CI failures.
=> Remove execnet workaround

docs/deprecated/commands.rst, docs/pkg_resources.rst, docs/userguide/distribution.rst, tox.ini
This PR extracts the parts contributed in #3995 that target fixing docs
(it seems that new versions of the linter got more strict).
I also added a workaround for the problem involving `towncrier`, `sphinxcontrib-towncrier` and `importlib_resources` (see `twisted/towncrier#528`).
Once a new version of `towncrier` is published, we can remove the workaround.
Closes 
[PR docs]:
=> Fix docs issues

docs/userguide/datafiles.rst
this was true in < [58.3.0](https://github.com/abravalheri/experiment-setuptools-package-data#previous-results-setuptools5830) but is no longer the case in [60.6.0+](https://github.com/abravalheri/experiment-setuptools-package-data#results-for-setuptools6060)
Closes 
[PR docs]:
=> docs: remove include_package_data and package_data interaction note

setuptools/tests/test_build_meta.py
pypa/wheel changed recently how `Requires-Dist` is written to the METADATA file.
This change adds a little pre-processing to side-step these differences when using assertions in the setuptools tests.
Closes 
[PR docs]:
=> Adequate tests to the latest changes in wheel 0.41.1

newsfragments/4001.misc.rst, setup.cfg, setuptools/discovery.py
In a Debian package build, there is going to be a top-level `debian` directory. Exclude this from `namespace_package` searches by default.
[PR docs]:
=> Exclude debian dir

setuptools/build_meta.py, setuptools/tests/test_build_meta.py
Since `setup.py` is an arbitrary Python script legacy scripts my be complex and may use `sys.exit`.
To adhere to PEP 517 handle `SystemExit` exception by ignoring it with exit code `0` and converting it to `CalledProcessError(exit_code, 'setup.py')` in case of non-zero exit code.
fixes #3973
=> Handle `setup.py` possibly using `sys.exit`

newsfragments/3995.bugfix.rst, setuptools/command/editable_wheel.py, setuptools/tests/test_editable_install.py
This updates the `_EditableFinder` that is added to `sys.meta_path` for certain editable installations to respect filename case on case-insensitive (but case-preserving) filesystems. I believe this behavior better matches normal installations and [PEP 235](https://peps.python.org/pep-0235/).
The way the change works is by checking the path is in the directory listing (which returns proper case) in addition to checking if the file exists (which is generally case-insensitive if the filesystem is). I believe this is pretty much how it is done in the `FileFinder` in the standard library (see [here](https://github.com/python/cpython/blob/983305268e2291b0a7835621b81bf40cba7c27f3/Lib/importlib/_bootstrap_external.py#L1637C28-L1637C28) and …
=> Make _EditableFinder case-sensitive on case-insensitive filesystems (for certain editable installations)

newsfragments/4007.misc.rst, setup.cfg, setuptools/discovery.py
- Add entries to `options.packages.find exclude` in `setup.py`
- I also take this opportunity to add `newsfragments` as a common directory to be ignored by auto-discovery
Closes #4006
[PR docs]:
=> Ignore `newsfragments` and `launcher` directories in `setuptools` project itself.

newsfragments/4009.misc.rst, setuptools/command/editable_wheel.py, setuptools/tests/test_editable_install.py
This is an attempt to follow the suggestions in [python/cpython#77102](https://github.com/python/cpython/issues/77102#issuecomment-1670160349) about how to handle `.pth` files.
The difference is that instead of using a `open(path, 'w')`, I emulated it with `io.TextIOWrapper` (to do the operation in memory instead of writing in the file system).
Closes #3937 
[PR docs]:
=> Use default encoding when creating .pth files in `editable_wheel`

newsfragments/4012.bugfix.rst, setuptools/config/_apply_pyprojecttoml.py, setuptools/tests/config/test_apply_pyprojecttoml.py
=> Complain about (gui-)scripts that are not listed in `pyproject.toml`'s `dynamic`

docs/userguide/package_discovery.rst
`find_packages()` only finds the folder which contains `__init__.py`.
=> Remove double negative in package_discovery.rst

docs/conf.py, newsfragments/4020.bugfix.rst, setup.cfg, setuptools/command/editable_wheel.py, setuptools/tests/test_editable_install.py
- Only handle 1 level of nesting (necessary for the namespace packages to work properly)
- Rely on the `importlib.machinery` to find other levels of nested packages to find the correct files based on the parent path.
Closes #4019
[PR docs]:
=> Fix editable install finder handling of nested packages

newsfragments/4023.misc.rst, setup.cfg, setuptools/__init__.py, setuptools/depends.py, setuptools/dist.py, setuptools/monkey.py, setuptools/tests/test_setuptools.py
The latest version of `sphinx` started failing in https://github.com/pypa/setuptools/pull/4020#issuecomment-1683535358 due to circular imports.
Examples of the error messages are:
```python
ImportError: cannot import name 'Distribution' from partially initialized module 'setuptools.dist'
AttributeError: partially initialized module 'setuptools' has no attribute 'version' (most likely due to a circular import)
Failed to import class 'Command' from module 'setuptools'
```
In this PR, I am attempting to address this problem.
The approach I used was:
- Rewrite the imports in `setuptools/__init__.py`, `setuptools/monkey.py`  and `setuptools/dist.py` to avoid circular imports.
- I also took this chance to try to tide up a bit (e.g. sorting them, separating `import ...` and `from ... import ...` …
=> Address circular imports complaints by Sphinx 7.2+

.github/workflows/main.yml, newsfragments/4027.misc.1.rst, newsfragments/4027.misc.2.rst, setuptools/tests/integration/test_pip_install_sdist.py
It seems that `pandas` also moved away from `setuptools`, so it does not make sense to keep them in the integration tests.
Instead we can add other prominent packages from https://hugovk.github.io/top-pypi-packages/.
- Removed `pandas` from integration tests
- Added `pyyaml`, `charset-normalizer` and `protobuf` to integration tests.
Closes 
[PR docs]:
=> Update integration tests

setuptools/command/_requirestxt.py, setuptools/command/egg_info.py, setuptools/config/_apply_pyprojecttoml.py, setuptools/dist.py, setuptools/tests/config/test_apply_pyprojecttoml.py
- Extract the logic for writing `requires.txt` from the ``egg_info`` module into ``_requirestxt.py``.
- Extract `egg_info`-specific processing of requirements from `dist.py` to `_requitestxt.py`.
- Avoid direct modifications of `install_requires` and `extra_requires`.
Instead only process them on demand, when the `requires.txt` file is needed for creating `.egg-info` directories.
This ensures `dist.install_requires` and `dist.extra_requires` remains compatible with core metadata and allow future changes to generate `Requires-Dist` in METADATA files (which are not compatible with `requires.txt`).
---
This is part of a series of PRs:
- #3903
- #3904
- #3905
- #3906
- #3907
- #3908
The motivation for this series of PRs is the following:
- Logic for generating `.egg-info` and `.dist-info` …
=> Avoid modification of `install_requires` and `extra_requires` that deviates from core metadata

docs/conf.py, setup.cfg
- Bump version (the compatibility issues with Sphinx>7.5 have been solved in `sphinx-notfound-page==1.0.0`
Closes 
[PR docs]:
=> Reactivate `sphinx-notfound-page`

setuptools/command/editable_wheel.py, setuptools/namespaces.py, setuptools/tests/namespaces.py, setuptools/tests/test_editable_install.py
- Fix the name given to the `*-nspkg.pth` files in editable installs, ensuring they are unique per distribution.
- Workaround limitations on `pkg_resources`-style legacy namespaces in editable installations.
Closes #4039 
[PR docs]:
=> Fix ` *-nspkg.pth` files and imports for `pkg_resources`-style legacy namespaces in editable installs.

newsfragments/4043.bugfix.rst, setuptools/_core_metadata.py, setuptools/_reqs.py, setuptools/command/_requirestxt.py, setuptools/config/_apply_pyprojecttoml.py, setuptools/dist.py
- Avoid using `_normalized_install_requires` and `_normalized_extras_require` in dist.metadata
- Add `functools.lru_cache` to requirement parsing
Closes #4042
[PR docs]:
=> Avoid using cached normalised requirement lists in metadata for compatibility with plugins

newsfragments/4045.misc.rst, setup.cfg, setuptools/tests/_packaging_compat.py, setuptools/tests/config/test_apply_pyprojecttoml.py, setuptools/tests/test_core_metadata.py, tox.ini
- Update test dependency on `build==1.0.3`
- Add fallback for `packaging==23.1`
Closes 
[PR docs]:
=> Update test deps

newsfragments/4048.bugfix.rst, setuptools/config/_apply_pyprojecttoml.py, setuptools/tests/config/test_apply_pyprojecttoml.py
=> Improve backwards compatibility with deprecated CLI practices

docs/conf.py, setup.cfg
This change attempts to address an usability problem in the docs, that arise from the use of `sphinx-hoverxref`.
The approach used is to simply remove it, since it is not fundamental for the website.
Closes #4064.
Closes 
[PR docs]:
=> Remove `sphinx-hoverxref` to improve usability

docs/conf.py, tox.ini
- Unify `passenv` with `pass_env` in `tox.ini` so we don't have trouble with `TOX_OVERRIDE`
- Use Python 3.11 inventory to avoid errors with distutils references
Fix https://github.com/pypa/setuptools/commit/fbe0d7962822c2a1fdde8dd179f2f8b8c8bf8892#commitcomment-129798103
[PR docs]:
=> Fix failing CI jobs

docs/setuptools.rst, docs/userguide/datafiles.rst, docs/userguide/miscellaneous.rst, docs/userguide/quickstart.rst
The Packaging User Guide has a [page](https://packaging.python.org/en/latest/guides/using-manifest-in/) on using `MANIFEST.in` to control the data files in a distribution. This is very setuptools-specific since other build backends do not use `MANIFEST.in` files. Thus, I think it is better for this information to live in the setuptools documentation.
After this is merged, I will open a PR on the PUG to make https://packaging.python.org/en/latest/guides/using-manifest-in/ a redirect.
=> Import PUG guide to MANIFEST.in

docs/userguide/pyproject_config.rst
The PUG now has a pyproject.toml guide, meant for users, distinct from the specification, meant for tool developers.
=> Link to the new pyproject.toml guide the PUG

.github/workflows/main.yml, newsfragments/4066.removal.1.rst, newsfragments/4066.removal.2.rst, newsfragments/4066.removal.3.rst, newsfragments/4066.removal.4.rst, newsfragments/4066.removal.5.rst, newsfragments/4066.removal.6.rst, setuptools/_normalization.py, setuptools/build_meta.py, setuptools/command/dist_info.py, setuptools/command/egg_info.py, setuptools/config/_apply_pyprojecttoml.py, setuptools/config/pyprojecttoml.py, setuptools/config/setupcfg.py, setuptools/dist.py, setuptools/errors.py, setuptools/tests/config/test_apply_pyprojecttoml.py, setuptools/tests/config/test_pyprojecttoml.py, setuptools/tests/config/test_setupcfg.py, setuptools/tests/test_bdist_deprecations.py, setuptools/tests/test_build_meta.py, tox.ini
Some deprecation warnings have been marked as due. Note that they were announced as deprecated at least a year ago (likely more than 1).
- Post-pone deprecations for fields in `setup.cfg` that have hyphens instead of underscores or are upper-cased.
- I did not feel confident that this would be a smooth transition in terms of backwards compatibility with old `sdists` published to PyPI so I postponed this change for another year...
- Remove deprecation warnings for invalid versions.
- Let the exception to be handled by the user.
- In some scenarios `setuptools._normalization.best_effort_version` can be used internally (this function will try very hard to sanitise the given version string).
- Remove `egg_base` option from `dist_info`.
- `dist_info` is kind of an internal command that was …
=> Handle wave of overdue deprecations

newsfragments/4079.removal.rst, setuptools/build_meta.py, setuptools/tests/test_build_meta.py
In https://github.com/pypa/setuptools/issues/2491#issuecomment-1742859314 the discussion seems to lead to the idea that it is better for now to avoid passing any `--build-option` for commands that are not `bdist_wheel` in `setuptools.build_meta`.
- Only pass `config_settings["--build-option"]` to `bdist_wheel` in `setuptools.build_meta`
- Remove no longer valid tests for `config_settings["--build-option"]` and `config_settings["--global-option"]` and editable installs
[PR docs]:
=> Only pass `--build-option` to `bdist_wheel` in build_meta

setuptools/depends.py
Don't hardcode opcode numbers, look them up instead.
Fixes https://github.com/pypa/setuptools/issues/4090
[PR docs]:
=> Fix setuptools.depends:get_module_constant() on Python 3.13.0a1

setuptools/tests/test_logging.py
It seems that the monkeypatching of `distutils.dist.log` started to be flaky on PyPy again: 
https://github.com/pypa/setuptools/actions/runs/6932122543/job/18855355764.
(Original discussion of the problem in #3707, #3709)
[PR docs]:
=> Mark flaky test on  PyPy with `xfail`

newsfragments/4126.bugfix.rst, setuptools/dep_util.py
=> Allow imports of `setuptools.dep_util.newer_group` with deprecation warning

newsfragments/4131.bugfix.rst, setuptools/dep_util.py
- Improve warning visibility with due date and reference url.
Closes #4131
Closes #4128
[PR docs]:
=> Add missing estimated date for removing `setuptools.dep_util`

NEWS.rst
The entry referenced PEP 612 (Parameter Specification Variables), but it should have referenced PEP 621 (Storing project metadata in pyproject.toml) instead.
=> Fix incorrect PEP reference in news entry for 69.0.0

newsfragments/+d4a9206f.bugfix.rst, setuptools/_normalization.py
Closes #2522.
Closes 
[PR docs]:
=> Retain valid names with underscores in egg_info.

pkg_resources/__init__.py, pkg_resources/tests/test_pkg_resources.py
This function has been deprecated since Python 3.4, replaced by `plistlib.load()`.
See https://github.com/python/cpython/pull/15615.
Fixes https://github.com/pypa/setuptools/pull/4168#discussion_r1440965290.
[PR docs]:
=> `plistlib.readPlist()` is missing from Python ≥ 3.9

ruff.toml
There is no such thing as `extend-include`, at least in ruff 0.1.11:
````
ruff failed
Cause: Failed to parse /path/to/ruff.toml
Cause: TOML parse error at line 1, column 1
|
1 | [lint]
| ^^^^^^
unknown field `extend-exclude`
````
[PR docs]:
=> ruff: extend-exclude → exclude

setuptools/build_meta.py
- Apparently `gettattr(tokenize, 'open', open)` is [causing problems for some users](https://github.com/pypa/setuptools/issues/4152#issuecomment-1848851990). Somehow 🤷‍♂️
- The good news is tath `tokenize.open` is available on Python 3.2+, so we should be able to safely remove this `getattr` call.
Closes #4152.
[PR docs]:
=> Remove unnecessary `getattr` for `tokenize.open`

setuptools/config/pyprojecttoml.py
Although tomli is vendored and always available, it is more clean to avoid using the backport on python 3.11. This makes it easier to automatically drop outdated branches in the future, and is a micro-optimization when user code imports a toml library in the same process space.
Additionally, setuptools.extern.VendorImporter explicitly supports removing vendored modules as long as they are globally installed and available. For distributors that rely on this, importing tomllib first permits those distributors to avoid packaging tomli on versions of python that already have tomllib.
=> Use the stdlib toml library on sufficiently new python

setuptools/config/pyprojecttoml.py, setuptools/py311compat.py
This approach follows pre-existing practices in the setuptools repository.
It makes it easier in the future to recognise code that can be updated and fallbacks that can be removed.
Closes 
[PR docs]:
=> Move `tomllib` import to `py311compat`

setuptools/config/_apply_pyprojecttoml.py
=> Default optional-dependencies to dict if missing in pyproject, fixes #3801

setuptools/config/_apply_pyprojecttoml.py
The previous link, https://packaging.python.org/en/latest/specifications/declaring-project-metadata/, ends with 404.
Update the link to point to the actual documentation
=> Point to a live documentation

newsfragments/4072.bugfix.rst, setup.cfg, setuptools/tests/test_packageindex.py
=> Rely on pytest-home for the alternate home directory.

docs/userguide/declarative_config.rst, docs/userguide/quickstart.rst, newsfragments/4200.doc.rst
[Preview](https://setuptools--4204.org.readthedocs.build/en/4204/userguide/quickstart.html#transitioning-from-setup-py-to-declarative-config).
- Update the section about transitioning from ``setup.py`` to declarative config - so that it not only has `setup.cfg` but also `pyproject.toml`, and gives important context to the new users who are learning about these files for the first time.
- Extract useful information about these files from GitHub comments to the docs. The new description conforms to the comments:
- [quote](https://github.com/pypa/setuptools/issues/3214#issue-1181816465)
> the approach `setuptools` would like to take is to eventually use a single declarative format (pyproject.toml) instead of maintaining 2 (`pyproject.toml` / `setup.cfg`).
- …
=> [Docs] Quickstart - add `pyproject.toml` info to the declarative config section

docs/userguide/quickstart.rst, newsfragments/4198.doc.rst
[Preview](https://setuptools--4201.org.readthedocs.build/en/4201/userguide/quickstart.html#development-mode)
Partially solves #4198 - describes this behavior in the docs
- is helpful for newcomers: acknowledges this - now creation of these files is not a surprise
- and a quick suggestion what to do with these auto-generated files (add to gitignore)
=> [Docs] Acknowledge the files created as side effects after running commands

_distutils_hack/__init__.py, pkg_resources/__init__.py, setuptools/command/bdist_egg.py, setuptools/command/bdist_rpm.py, setuptools/command/build_ext.py, setuptools/command/develop.py, setuptools/command/easy_install.py, setuptools/command/install.py, setuptools/depends.py, setuptools/discovery.py, setuptools/dist.py, setuptools/installer.py, setuptools/msvc.py, setuptools/package_index.py, setuptools/sandbox.py, setuptools/tests/config/test_setupcfg.py, setuptools/tests/server.py, setuptools/tests/test_build_ext.py, setuptools/tests/test_core_metadata.py, setuptools/tests/test_distutils_adoption.py, setuptools/unicode_utils.py
Fix [flake8-return](https://pypi.org/project/flake8-return/) issues reported by [ruff](https://docs.astral.sh/ruff/rules/#flake8-return-ret) 0.1.9.
[PR docs]:
=> Fix flake8-return warnings

docs/references/keywords.rst
fix data_files kwarg documentation. Setting data_files to a list of str results in a warning being printed: https://github.com/pypa/setuptools/blob/259af91d90cc1259634e01c334caad3507ec9ad2/docs/deprecated/distutils/setupscript.rst#L549-L551
Closes 
[PR docs]:
=> fix data_files kwarg documentation

docs/references/keywords.rst
remove claim that data_files does not work with wheels, it does work with wheels, the data goes into the `distribution-1.0.data/data` dir which then gets copied into the installation prefix. What doesn't work is: "Distutils allows directory to be an absolute installation path, but this is discouraged since it is incompatible with the wheel packaging format"
[PR docs]:
=> remove claim that data_files does not work with wheels

.coveragerc, .readthedocs.yaml, README.rst, ruff.toml, setup.cfg, setuptools/depends.py, setuptools/py311compat.py, setuptools/tests/integration/helpers.py, setuptools/tests/server.py, setuptools/tests/test_bdist_deprecations.py, setuptools/tests/test_bdist_egg.py, setuptools/tests/test_develop.py, setuptools/tests/test_dist_info.py, setuptools/tests/test_easy_install.py, setuptools/tests/test_install_scripts.py, setuptools/tests/test_packageindex.py, setuptools/tests/test_sandbox.py, setuptools/tests/test_wheel.py
- Bump year on badge
- Remove build and dist from excludes. It appears they are not needed and their presence blocks the names of packages like 'builder' and 'distutils'. Ref pypa/distutils#224.
- Exclude docs and tests directories properly per Setuptools behavior.
- Rely on default discovery for good heuristics for finding packages.
- Enable preview to enable preserving quotes.
- Tweak coverage configuration for type checking (jaraco/skeleton#97)
- Use latest versions in RTD boilerplate.
Closes 
[PR docs]:
=> Merge latest skeleton

docs/deprecated/python_eggs.rst, newsfragments/4167.bugfix.rst, setuptools/_normalization.py, setuptools/command/develop.py, setuptools/tests/test_develop.py
- Restore expectation that egg-link files will be named with dashes and not underscores for compatibility with older pips.
- Replace the incorrect phrase about 'unescaping' and instead clarify that the transformations are irreversible.
- Rearrange escaping functions to describe them in the order they should be used.
- Document the incorrect behavior revealed by #4167.
- Add a test capturing the desired expectation, marked as xfail for now.
Ref #4167
[PR docs]:
=> Restore egg link names with dashes for now

newsfragments/4217.bugfix.rst, setuptools/build_meta.py, setuptools/tests/test_build_meta.py
Restore original argument append behavior which was changed in #4079.
Fixes:
```
error: option --dist-dir not recognized
ERROR Backend subprocess exited when trying to invoke build_wheel
```
[PR docs]:
=> Append arbitrary args instead of prepending.

newsfragments/4241.misc.rst, setuptools/_normalization.py, setuptools/_path.py, setuptools/command/editable_wheel.py, setuptools/config/_apply_pyprojecttoml.py, setuptools/config/expand.py, setuptools/config/pyprojecttoml.py, setuptools/config/setupcfg.py, setuptools/discovery.py, setuptools/tests/config/test_pyprojecttoml.py, setuptools/tests/test_config_discovery.py, tools/generate_validation_code.py
Brought all aliases `_Path` and unions `str | Path` and `str | PathLike` closer to typeshed's `StrPath` and centralized the TypeAlias in `setuptools._path`.
Works towards #2345 
[PR docs]:
=> Standardize and centralize `StrPath` TypeAlias

newsfragments/4238.misc.rst, ruff.toml, setup.cfg, setuptools/tests/test_core_metadata.py
Replaced `Flake8-2020` by Ruff's https://docs.astral.sh/ruff/rules/#flake8-2020-ytt . This also essentially removes dependency on Flake8 as a whole.
I've also updated a test to be a bit more relevant (both from the fact that setuptools now only has references to flake8 in vendored code, and that the mentioned issue isn't relevant to setuptools)
[PR docs]:
=> Replace Flake8-2020 by Ruff

newsfragments/4237.misc.rst, pkg_resources/tests/test_find_distributions.py, setup.cfg
`py` was only installed as a dependency of `pytest-fork` which was only installed as a dependency of `pytest-xdist`. This also removes another untyped import for #2345  / #3979 / #4192 
I could've bumped it to >=1.9.0 (first typed version: https://py.readthedocs.io/en/latest/changelog.html#id3) but I figured may as well just stop using it since: https://pypi.org/project/py/
> **NOTE**: this library is in **maintenance mode** and should not be used in new code.
> The py lib is a Python development support library featuring the following tools and modules:
> **py.path**: uniform local and svn path objects -> please use pathlib/pathlib2 instead
[PR docs]: …
=> Use `pathlib` instead of `py`

newsfragments/4244.bugfix.rst, pkg_resources/__init__.py
Subclasses of are expected to return a `list`. There's no mention of this method potentially returning `None` in the docstring. If this is intended, then the docstring should be updated, and the return type be `Optional[list[str]]`
Work towards #2345 and merging `pkg_resources`
[PR docs]:
=> Return an empty `list` by default in `pkg_resources.ResourceManager.cleanup_resources`

pkg_resources/__init__.py
Prevent `pkg_resources._find_adapter` from ever returning `None`, whilst keeping the exact same public API behaviour (the message of the error changes, but the error will be the same).
Doesn't immediately fix anything, but will be necessary to type-check `pkg_resources` w/o errors, which will be needed to validate annotations from merging typeshed stubs.
[PR docs]:
=> Prevent `pkg_resources._find_adapter` from ever returning `None`

.gitignore
According to https://github.com/pypa/setuptools/pull/3979?notification_referrer_id=NT_kwDOABSbuLI3MDA2MzAwNzU2OjEzNTA1ODQ#discussion_r1499161632 and https://blog.jaraco.com/skeleton/#ignoring-artifacts this probably shouldn't be in there. This PR is a simple cleanup removing `.idea/` to respect that.
As a sidenote, maybe linking to the above documentation *in* the `.gitignore` file would be a good idea?
[PR docs]:
=> Remove IDE-specific folder from `.gitignore`

docs/userguide/datafiles.rst, docs/userguide/miscellaneous.rst
The fact that the `Subdirectory for Data Files` section in `docs/userguide/datafiles.rst` repeat examples for `include_package_data` without mentioning `MANIFEST.in` may be confusing for users that skip previous parts of the document.
This is an alternative solution for #4193. The problem is summarised by the user in https://github.com/pypa/setuptools/pull/4193#discussion_r1491993529.
Closes 
[PR docs]:
=> [Docs] Further clarify `include_package_data`

newsfragments/4254.bugfix.rst, pkg_resources/__init__.py, pkg_resources/tests/test_resources.py
Made `pkg_resoursces.NullProvider`'s `has_metadata` and `metadata_isdir` methods return actual booleans like all other Providers.
This was noticed when attempting to type the `pkg_resources` package for #2345 
xref https://github.com/python/typeshed/pull/11512#discussion_r1508147634
> \# Note: runtime forgets to coerce the return type to boolean,
> \# but we need to specify bool for NullProvider to respect the IResourceProvider protocol
[PR docs]:
=> Made `pkg_resoursces.NullProvider`'s `has_metadata` and `metadata_isdir` methods return actual booleans like all other Providers

newsfragments/4243.bugfix.rst, pkg_resources/__init__.py
Clarify some `pkg_resources` methods return `bytes`, not `str`. Also return an empty `bytes` in `EmptyProvider._get`
Works towards #2345 and merging `pkg_resources` stubs from typeshed
[PR docs]:
=> pkg_resources: Clarify some methods return `bytes`, not `str`

mypy.ini, pyproject.toml, setup.cfg, setuptools/command/build_ext.py, setuptools/command/editable_wheel.py, setuptools/config/_validate_pyproject/fastjsonschema_validations.py
Follow-up to #3979. Extracted from #4192. Enables mypy type-checking in the CI.
Example failure: https://github.com/pypa/setuptools/actions/runs/8158516102/job/22300634747?pr=4257#step:9:69
[PR docs]:
=> Enable mypy on CI

docs/conf.py, newsfragments/4265.feature.rst, setuptools/command/easy_install.py, setuptools/command/editable_wheel.py, setuptools/compat/py39.py, setuptools/namespaces.py
For the time being `.pth` files in UTF-8 cause problems, see python/cpython#77102.
CPython maintainers' recommendation is to use the default encoding of the underlying system.
The motivation of this PR is to help with the encoding warnings.
- Use `"locale"` encoding for `.pth` files.
- Add `TODO` comments as reminders of other parts that may be moved to UTF-8, but there might be a risk.
- Introduce the `setuptools.compat.py39` module. This tries to follow the methodology in https://github.com/pypa/setuptools/pull/4212.
Closes 
[PR docs]:
=> Explicitly use `"locale"` encoding for `.pth` files

mypy.ini, setup.cfg, setuptools/_core_metadata.py, setuptools/command/editable_wheel.py
- pin mypy version so a new version doesn't suddenly cause the CI to fail
- Fix new failures in 1.9
- Explain why we're not running mypy on Python 3.12 in the CI yet
- Ignore `.egg` folder for faster local runs
[PR docs]:
=> Update and pin mypy to 1.9

.github/workflows/main.yml
Update setup-python action to v5
[PR docs]:
=> Update setup-python action to v5

.github/workflows/main.yml
~~Hoping this fixes failing cygwin action. Otherwise it's still~~ updating an outdated action
Edit: From what I understand, https://mirrors.kernel.org/sourceware/cygwin/x86_64/ got updated today and it's missing all the sig files :/
I've opened https://bugzilla.kernel.org/show_bug.cgi?id=218575 
Edit 2: `.sig` files have been added back today
[PR docs]:
=> Update cygwin-install-action to v4

.github/workflows/ci-sage.yml
Update upload-artefact action to v3
sage would need to update their `actions/download-artifact` to v4 for setuptools to update `actions/upload-artifact` to v4 as well.
https://github.com/sagemath/sage/blob/e417e2205be84d6d567b8897527fa6945ad09bdb/.github/workflows/docker.yml#L172-L173
[PR docs]:
=> Update upload-artefact action to v3

MANIFEST.in
This adds `mypy.ini` to `MANIFEST.in` and so to the sdist as well.
Fixes #4287
=> Add mypy.ini to MANIFEST.in

NEWS.rst
I thought some releases were missing, but I guess they were added in chronological order rather than numerical.
Let's keep numerical, especially as no dates are shown.
- [n/a] News fragment added in [`newsfragments/`].
[PR docs]:
=> NEWS: Put releases in numerical order

conftest.py, mypy.ini, newsfragments/4282.misc.rst, setup.cfg, tox.ini
In https://github.com/pypa/setuptools/pull/4257#discussion_r1514754970, @abravalheri mentioned that:
> [...] I think we just remove the `testing-integration` and use `testing` everywhere...
> 
> Although it might add a bit of overhead for the integration tests, it will simplify and streamline the setup... This way we reduce the divergence with `skeleton`. The additional overhead in the integration tests should not be too much, and the integration tests just run before the releases anyway.
This PR is doing just that.
Accepting this closes #4282 , which was my original idea.
[PR docs]:
https://setuptools.pypa.io/en/latest/development/developer-guide.html#making-a-pull …
=> Deduplicate testing dependencies by dropping `[testing-integration]`

NEWS.rst
Previously, the orphaned filename was used, making the current Sphinx setup link a non-existing issue: https://github.com/pypa/setuptools/commit/f07b037161c9640e4518c5f71e78af49a478d5b2#commitcomment-141024072.
=> Fix the 608de826 commit reference in changelog

newsfragments/4280.misc.rst, setuptools/sandbox.py
This was noticed in typeshed:
https://github.com/python/typeshed/blob/449f70f1f1bc787eb56699a5ce153c3efbfe2f4f/stubs/setuptools/%40tests/stubtest_allowlist.txt#L40-L41
Before:
```py
>>> from setuptools.sandbox import AbstractSandbox
>>> AbstractSandbox.name
'tmpnam'
```
After:
```py
>>> from setuptools.sandbox import AbstractSandbox
>>> AbstractSandbox.name
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: type object 'AbstractSandbox' has no attribute 'name'
```
[PR docs]:
=> Avoid leaking "name" variable in `AbstractSandbox`

setup.cfg, setuptools/tests/config/test_apply_pyprojecttoml.py
- Replace `Translator` with `LiteTranslator` from `ini2toml[lite]>=0.14`
Closes #4315
[PR docs]:
=> Make `test_apply_pyprojecttoml` more deterministic with new version of `ini2toml`

newsfragments/4308.misc.rst, setuptools/tests/fixtures.py
Based on the test introduced in https://github.com/pypa/setuptools/commit/b4d3e83f0764e0c38ed57d688c301624ef08d1ea, we can see that when none of `PRE_BUILT_SETUPTOOLS_SDIST` or `PRE_BUILT_SETUPTOOLS_WHEEL` is set, the `setuptools_wheel` fixture keeps recursively creating `build/lib/build/lib/...` directories which slows down the tests and creates a huge amount of unnecessary files.
This change tries to avoid that by building simultaneously `sdist`/`wheel`.
Closes 
[PR docs]:
=> Fix `setuptools_wheel` fixture

newsfragments/4278.bugfix.rst, setuptools/command/editable_wheel.py, setuptools/tests/test_editable_install.py
It seems that the import machinery skips `PathEntryFinder` when trying to locate nested namespaces, if the `sys.path_hook` item corresponding to the finder cannot be located in the submodule locations of the parent namespace.
We should (probably) add the `PATH_PLACEHOLDER` to the namespace spec , so that the `PathEntryFinder` is triggered.
This PR also add some type hints to the template, because it helped to debug some type errors.
Closes #4248 (likely)
[PR docs]:
=> Fix `PathEntryFinder` / `MetaPathFinder` in `editable_wheel`

NEWS.rst
Fix a changelog rendering issue due to a missing backtick noticed here: https://github.com/pypa/setuptools/pull/4182#discussion_r1572904553
I don't think this deserves a newsfragment.
[PR docs]:
=> Fix missing backtick in changelog

newsfragments/4309.removal.rst, pkg_resources/__init__.py, setuptools/_imp.py, setuptools/command/bdist_egg.py, setuptools/command/build_ext.py, setuptools/command/develop.py, setuptools/command/easy_install.py, setuptools/command/install_scripts.py, setuptools/command/setopt.py, setuptools/dist.py, setuptools/package_index.py, setuptools/tests/environment.py, setuptools/tests/test_build_meta.py, setuptools/tests/test_easy_install.py, setuptools/tests/test_editable_install.py, setuptools/tests/test_integration.py, setuptools/unicode_utils.py, setuptools/wheel.py
Previously, changes regarding UTF-8 avoided touching complicated parts of the code where it could cause incompatibility.
This PR is a bit more aggressive, but still try to maintain backwards compatibility:
- When reading files, first try to read them as UTF-8, then we fallback to the `locale` encoding.
- When writing files, use UTF-8.
In my opinion the highest risk here are in the `easy_install/install_scripts` commands, because it might be the case some scripts are not meant to be UTF-8... But hopefully that risk would be minimal[^1].
[^1]: Once file contents are encoded as Python strings they are already encoded as UTF-8, so it should be OK to write them directly to files. Moreover, most popular scripting languages nowadays support UTF-8.
Closes 
_(See [documentation][PR docs] for …
=> Adopt more UTF-8

README.rst, newsfragments/4312.doc.rst
It might be some update to Github's RST renderer caused badges to display in multiple lines. uses RST substitution to put badges in 1 line.
Before the change
After the change
[PR docs]:
=> Uses RST substitution to put badges in 1 line

.github/workflows/main.yml, setuptools/tests/test_editable_install.py
Recently `macos-latest` on Github Actions started failing for Python 3.8 and Python 3.9.
This is due to https://github.com/actions/setup-python/issues/850, https://github.com/actions/setup-python/issues/696#issuecomment-1637587760.
The changes implemented here follow the same approach as in https://github.com/python/peps/pull/3763.
(I just want to get the tests running for now, we can change to a proper fix later)
Closes 
[PR docs]:
=> [CI Workaround] Avoid errors on Python 3.8 macos-latest as GitHub CI has dropped support

newsfragments/4255.misc.rst, pytest.ini, setuptools/command/editable_wheel.py, setuptools/tests/__init__.py, setuptools/tests/test_build_meta.py, setuptools/tests/test_build_py.py, setuptools/tests/test_windows_wrappers.py
Attempt at supeerseding https://github.com/pypa/setuptools/pull/4234#discussion_r1511342695 w/o any potential breaking change
Essentially a band-aid for #3810 to make reading failed tests results more bearable.
[PR docs]:
=> Turn `EncodingWarning` into errors and cleanup `pytest.ini`

newsfragments/4332.feature.rst, setup.cfg, setuptools/package_index.py, setuptools/tests/test_packageindex.py
- **Remove pop_prefix parameter, unused.**
- **Add a test capturing the basic expectation.**
- **Update _vcs_split_rev_from_url to use modern constructs.**
- **package-index: Extract fall-through methods _download_vcs and _download_other.**
- **Extract _resolve_vcs for resolving a VCS from a URL.**
- **Consolidated all _download_vcs methods into one.**
- **Replace os.system calls with subprocess calls.**
- **Prefer tmp_path fixture.**
Closes 
[PR docs]:
=> Modernize package_index VCS handling

setuptools/dist.py
- Don't call `setuptools.extern.importlib_metadata.EntryPoints.names`, instead just iterate over `entry_points` (this is the [same underlying implementation](https://github.com/python/importlib_metadata/blob/v7.1.0/importlib_metadata/__init__.py#L286-L290), but it is backwards compatible).
Closes #4338 
[PR docs]:
=> Don't call `setuptools.extern.importlib_metadata.EntryPoints.names` for better backwards compatibility.

newsfragments/4322.removal.1.rst, newsfragments/4322.removal.2.rst, setuptools/__init__.py, setuptools/command/build.py, setuptools/tests/test_build.py, setuptools/tests/test_setuptools.py, tox.ini
- Remove ``setuptools.convert_path``
- Remove fallback for customisations of ``distutils``' ``build.sub_command``
- Re-enable enforcement via `tox` so that the maintainers of `setuptools` are "notified" when the next deprecation comes[^1]
The deprecation warnings have been issued for almost 2 years for these features.
Closes 
[PR docs]:
[^1]: By "notified", I mean the CI builds will start to fail and require manual intervention...
=> Remove deprecated code after warnings have been issued for a long period.

pkg_resources/__init__.py
After playing around with previous PRs with whether `_distribution_finders`, `_namespace_handlers` and `_namespace_packages` definitions should be moved closer to declarations, I noticed that, since we have to define the variables for other reasons anyway, there's no point to `_declare_state`'s global namespace shenanigans. This PR makes it work for static analysis and, after #4246 is merged, will reduce changes in #4242
[PR docs]:
=> Type `pkg_resources._declare_state` and make it work statically

pkg_resources/__init__.py
Simplified `pkg_resources._declare_state`. As per @abravalheri 's suggestion in https://github.com/pypa/setuptools/pull/4258#discussion_r1518185927
[PR docs]:
=> Simplified `pkg_resources._declare_state`

mypy.ini, newsfragments/4348.bugfix.rst, newsfragments/4348.misc.rst, pkg_resources/__init__.py, pkg_resources/tests/test_resources.py
Update dynamic module imports in `pkg_resources` to direct static imports as per https://github.com/pypa/setuptools/pull/4330/files#r1582361952
This also fixes an attribute error that was spotted thanks to the mypy config change.
[PR docs]:
=> Update dynamic module imports in `pkg_resources` to direct static imports & fix attribute error

newsfragments/4150.feature.rst, setuptools/config/pyprojecttoml.py, setuptools/tests/config/test_pyprojecttoml.py, setuptools/tests/test_build_py.py
This changeset adds a warning when the invalid `[tools.setuptools]` table is detected in `pyproject.toml` metadata, as a hint to users that any data they've declared there is being ignored by `setuptools`.
Closes #4150.
- I have not added a test because the `_ExperimentalConfiguration` warning in the affected module is also not tested. I'd be happy to write one if the maintainers would like one.
[PR docs]:
=> Emit warning for invalid [tools.setuptools] table

pkg_resources/extern/__init__.py, setuptools/extern/__init__.py, tools/vendored.py, tox.ini
Currently, the cog script may miss packages that are not listed in `vendored.txt` but get installed by `pip` (transitive dependencies).
This change simply scans the vendored directories looking for both packages and modules that got installed.
The name was changed because it also consider `modules` (in opposition to `packages`).
The alphabetical reordering is a consequence of the way directories are listed in Python/OSs.
Closes 
[PR docs]:
=> Fix potential problem with cog script for `vendored`

pkg_resources/__init__.py
Explicitly disallow resource paths starting with single backslash
Previously, such paths were disallowed implicitly
as they were treated as Windows absolute paths.
Since Python 3.13, paths starting with a single backslash are not considered Windows-absolute, so we treat them specially.
This change makes the existing doctest pass with Python 3.13.
Partially fixes https://github.com/pypa/setuptools/issues/4196
[PR docs]:
=> Explicitly disallow resource paths starting with single backslash

setuptools/_entry_points.py
The exception in importlib.metadata has changed.
See https://github.com/python/importlib_metadata/issues/488
This makes an existing test pass with Python 3.13.
Partially fixes https://github.com/pypa/setuptools/issues/4196
[PR docs]:
=> Make the validation test for entry-points work with Python 3.13+

tools/generate_validation_code.py
=> Replace call to deprecated `validate_pyproject` command

tools/vendored.py
Closes https://github.com/pypa/setuptools/pull/4369/files#r1606421897
[PR docs]:
=> Prevent `bin` folders to be taken as extern packages when vendoring

pkg_resources/__init__.py
*Review and merge after https://github.com/pypa/setuptools/pull/4246*
This is an immediate follow-up but with more precise and complex typing.
works towards step 3.2 of https://github.com/pypa/setuptools/issues/2345#issuecomment-1627561833
Once this #4391 and #4390 are merged, `pkg_setuptools` will be on par with Typeshed
[PR docs]:
=> Generic typing for register methods in `pkg_resources`

newsfragments/4403.bugfix.rst, pyproject.toml, setuptools/tests/compat/py39.py, setuptools/tests/test_find_packages.py, setuptools/tests/test_find_py_modules.py
Closes #4403
Closes 
[PR docs]:
=> Replace use of mktemp with can_symlink from the stdlib test suite.

newsfragments/4382.bugfix.rst, setuptools/compat/py311.py
Noticed while adding pyright checks to setuptools (https://github.com/pypa/setuptools/pull/4192)
Also typed `shutil_rmtree` (xref https://github.com/python/typeshed/pull/12002 )
[PR docs]:
=> Prevent a `TypeError` in `compat.py311.shutil_rmtree`

setuptools/command/bdist_egg.py, setuptools/tests/test_find_packages.py
ISC001 Implicitly concatenated string literals on one line
ISC003 Explicitly concatenated string should be implicitly concatenated
[PR docs]:
=> Enforce ruff/flake8-implicit-str-concat rules (ISC)

.pre-commit-config.yaml
The latest changes in https://github.com/pypa/setuptools/pull/4388/files#diff-e3d3d454fa3a072c9f46f8affa27513892fbc2d245e87f57a5927a7be851de05R2468-R2500 may lead to formatting errors for old versions of Ruff.
Code updated with `pre-commit autoupdate`.
[PR docs]:
=> Bump Ruff to avoid "unstable" configuration in `pre-commit` hook

pkg_resources/__init__.py
Checked all public methods (`def ([^_]|__)`) in `pkg_resources` for their implied return type using pyright/pylance. Updated annotations for those that seemed incorrect or returned a partial `Any` even after #4390 .
Step 3.3 of https://github.com/pypa/setuptools/issues/2345#issuecomment-1627561833
Once this #4355 and #4390 are merged, `pkg_setuptools` will be on par with Typeshed
[PR docs]:
=> pkg_resources: fix incorrect implicit return types

setuptools/command/bdist_wheel.py
`distutils.log` does not seem to define the `warning` function.
Instead it uses `warn`.
Closes 
[PR docs]:
=> Fix undefined `log.warning` function in `bdist_wheel`

pyproject.toml
Implements approach discussed in https://github.com/pypa/setuptools/pull/4389/files#r1613314607
This approach assumes that the probability of a new top-level package being added/removed from setuptools is lower than the probability/frequency of folders and files being added/removed in package root.
If this assumption holds, this PR not only solves #4394 but also simplifies maintenance.
If this assumption does not hold, this PR still solves #4394 but increases churn[^1].
Closes #4394 
[^1]: Although if the overall probability/frequency of these events happening is still low the churn increase is neglectable.
[PR docs]: …
=> Simplify setuptools own `tool.setuptools.packages.find` by using include rule

pkg_resources/__init__.py, setuptools/command/easy_install.py, setuptools/package_index.py, setuptools/tests/test_dist_info.py
Extracted from #4366 to only include internal values.
[PR docs]:
=> Use set instead of True-only dict for non-public names

mypy.ini, pkg_resources/__init__.py, ruff.toml
Step 3.2 of https://github.com/pypa/setuptools/issues/2345#issuecomment-1627561833
Once this #4355 and #4391 are merged, `pkg_setuptools` will be on par with Typeshed
[PR docs]:
=> pkg_resources: Merge `@overload` and `TypeVar` annotations from typeshed

.github/workflows/main.yml
Ref: https://github.com/codecov/feedback/issues/84.
=> Let codecov-action autodetect the coverage report

pkg_resources/__init__.py, setuptools/command/easy_install.py, setuptools/tests/test_sandbox.py
```
RSE102 Unnecessary parentheses on raised exception
```
[PR docs]:
=> Apply ruff/flake8-raise rules (RSE)

setuptools/command/bdist_egg.py, setuptools/command/easy_install.py
```
PERF401 Use a list comprehension to create a transformed list
```
[PR docs]:
=> Apply ruff/Perflint rule PERF401

pkg_resources/extern/__init__.py, ruff.toml, setuptools/__init__.py, setuptools/command/easy_install.py, setuptools/config/_validate_pyproject/formats.py, setuptools/depends.py, setuptools/extension.py, setuptools/extern/__init__.py, setuptools/tests/test_sdist.py
```
TRY300 Consider moving this statement to an `else` block
```
[PR docs]:
=> Enforce ruff/tryceratops rule TRY300

setuptools/command/bdist_wheel.py, setuptools/command/dist_info.py, setuptools/command/egg_info.py
The goal is to standardize the format of the help text printed by commands. It is not easy to choose between brackets `[]` and parentheses `()`. I went for the [docopt](http://docopt.org/) style, which is the closest to a standard I could find:
> [...] and whether that argument has a default value ([default: 10]).
This change has already been applied to distutils (https://github.com/pypa/distutils/pull/262).
Closes  #4421
[PR docs]:
=> Use brackets for the default value of option arguments

ruff.toml
```
TRY003 Avoid specifying long messages outside the exception class
```
Applying this rule would mean creating lots of specialised exception classes. Not sure this would improve readability and maintainability in this context.
Addresses https://github.com/pypa/setuptools/pull/4450#issuecomment-2200583235.
[PR docs]:
=> Ignore ruff/tryceratops rule TRY003

setuptools/tests/test_sdist.py
Restore the previous functionality, where the function did not return explicitly in case of exceptions, and hence returned `None`.
Addresses https://github.com/pypa/setuptools/pull/4450#discussion_r1671240089.
[PR docs]:
=> Fix 92989c2i / #4450

pyproject.toml
- **Move workaround for #3921 to the local section, restoring upstream to match upstream.**
- **Exclude pytest-ruff (and thus ruff), which cannot build on cygwin.**
Closes 
[PR docs]:
=> Move project-specific pins out of upstream.

setuptools/command/editable_wheel.py
This commit rename the `find_spec` arguments in _EditableFinder and _EditableNamespaceFinder to be compliant of the standard `importlib.abc.MetaPathFinder` interface.
https://docs.python.org/3/library/importlib.html#importlib.machinery.PathFinder.find_spec https://github.com/abravalheri/typeshed/blob/eecac02ef7fdbe82b9dc57fa3ca4bb9d341116d7/stdlib/_typeshed/importlib.pyi
The `find_module` arguments were not renamed because the method `find_module` is deprecated starting from Pyhton3.10 and has been removed in Pyhton3.12
https://docs.python.org/3/reference/import.html#the-meta-path
Closes 
[PR docs]:
https://setuptools.pypa.io/en/latest/development/developer-guide.ht …
=> Rename arguments on _EditableFinder and _EditableNamespaceFinder

newsfragments/4475.bugfix.rst, pyproject.toml, setuptools/tests/config/test_apply_pyprojecttoml.py, setuptools/tests/test_setuptools.py
- **Revert "Ensure that package data from vendored packages gets installed."**
- **Revert "Disable inclusion of package data as it causes 'tests' to be included as data. Fixes #2505."**
- **Add test asserting cli scripts are included in wheel.**
- **Remove test as it's redundant to the check in test_its_own_wheel_does_not_contain_tests.**
- **Mark the file as xfail for now.**
Closes #4475
[PR docs]:
=> Install all the files

newsfragments/4476.bugfix.rst, pkg_resources/__init__.py, ruff.toml, setuptools/__init__.py
Closes #4476
Closes 
[PR docs]:
=> Reset the backports module when enabling vendored packages.

newsfragments/4489.bugfix.rst, setuptools/command/egg_info.py, setuptools/dist.py
- **Revert "Fix error when integrating with pip (#3823)"**
- **Removed lingering unused code around Distribution._patched_dist.**
Closes #4489
[PR docs]:
=> Remove _patched_dist

mypy.ini, pyproject.toml, setuptools/command/editable_wheel.py, setuptools/command/install.py, setuptools/command/install_lib.py, setuptools/command/upload_docs.py, setuptools/tests/test_wheel.py
- Update mypy to 1.11
- Slightly relax version lock to allow automatic point releases
- Updated `follow_imports = silent` comment to be more generalized / future-proof
- As per https://github.com/pypa/setuptools/issues/4473#issuecomment-2234155911 , indicate myself as owner of the mypy pin, until the removal of `types-setuptools` from typeshed. Right now a CI failure is expected almost every version, especially as more annotations are added to setuptools, and fixes upstreamed to typeshed. Which would require a lock, then unlock PRs everytime (more churn than just locking and updating when ready), or non-obvious fixes (mainly due to distutils subtyping). Once `types-setuptools` is obsoleted, things should be more stable. @jaraco 
Goes towards unblocking #4352
Closes #4432
_(See …
=> Update mypy to 1.11

newsfragments/4492.misc.rst, pyproject.toml
Add Python version specifiers to importlib_metadata, importlib_resources and tomli dependencies, to require them only on Python versions on which they are actually used.
[PR docs]:
=> Add Python version specifiers to [core] dependencies

docs/userguide/quickstart.rst
In an attempt to lessen the burden of #4483, guide users installing setuptools to install the required dependencies.
This docs update attempts to honor the intent of https://github.com/pypa/setuptools/pull/4457#discussion_r1668814513, namely to expose the dependencies for incidental use but discourage it for use in `build-requires`.
Ref #4483
[PR docs]:
=> Add guidance on core dependencies

newsfragments/4520.feature.rst, setuptools/command/test.py, setuptools/tests/integration/test_pip_install_sdist.py
As suggested by @hauntsaninja, add a deprecation warning to access of `setuptools.command.test` and raise an error when running the command.
This approach provides a gentler offboarding for projects still reliant on the presence of the module or the command. Currently, it gives 3 months for projects to cut new releases in response to the change. This deadline can be extended if deemed necessary.
Closes #4520; Closes #4519.
[PR docs]:
=> Restore the tests command and deprecate access to the module.

MANIFEST.in, setup.py, setuptools/config/NOTICE, setuptools/config/_validate_pyproject/NOTICE, setuptools/config/_validate_pyproject/fastjsonschema_validations.py, setuptools/config/_validate_pyproject/formats.py, setuptools/config/distutils.schema.json, setuptools/config/setuptools.schema.json, tools/generate_validation_code.py, tox.ini
This facilitates adding/removing options without having to release a whole new version of `validate-pyproject`.
In general it should help to improve the developer experience when dealing with `pyproject.toml` validations.
Closes 
[PR docs]:
=> Use local schemas to define validation for `pyproject.toml`

newsfragments/4534.misc.rst, setuptools/windows_support.py
The issue https://github.com/python/cpython/issues/61140 referenced in https://github.com/pypa/setuptools/commit/1fab75aaec4ada030ca2777e26edbf5eb76d9802, has been resolved in Python 3.8.7 https://docs.python.org/3.8/whatsnew/changelog.html#python-3-8-7-release-candidate-1
Even then, the decoractor added in https://github.com/pypa/setuptools/commit/81b4d929152eb7119f89a06294e2b656d36c3484 ensures that this wouldn't be run on non-windows machines anyway.
Resolves a few mypy `attr-defined` and pyright `reportAttributeAccessIssue` for #2345 
[PR docs]:
=> Changed the import of `ctypes.wintypes` from `__import__` to a regular `import` statement

pyproject.toml, setuptools/tests/test_build_meta.py
It seems that the [error in `macOS`](https://github.com/pypa/setuptools/actions/runs/10302537702/job/28519161406#step:9:939) happens due to the normalisation of quotes in the Requirement string:
```python
assert "Requires-Dist: tomli >=1 ; extra == 'all'" in """
Metadata-Version: 2.1
Name: foo
Version: 0.1
Summary: This is a Python package
License: MIT
Project-URL: Homepage, http://github.com/
Classifier: Development Status :: 5 - Production/Stable
Classifier: Intended Audience :: Developers
Description-Content-Type: text/x-rst
License-File: LICENSE.txt
Requires-Dist: appdirs
Provides-Extra: all
Requires-Dist: tomli>=1; extra == "all"
Requires-Dist: pyscaffold<5,>=4; extra == "all"
Requires-Dist: importlib; python_version == "2.6" and extra == "all"
This is a ``README``
"""
```
Closes …
=> Fix failures of CI on macOS due to requirement normalisation inconsistency.

newsfragments/4505.feature.rst, setuptools/command/build_ext.py, setuptools/command/easy_install.py, setuptools/command/editable_wheel.py, setuptools/dist.py, setuptools/extension.py
Extracted from https://github.com/pypa/setuptools/pull/4504
These are the runtime changes that should be reviewed more carefully.
Works towards #2345 
[PR docs]:
=> Runtime changes for typeshed parameter annotations merge

docs/development/developer-guide.rst
Add Type annotations developer guideline
CC @abravalheri feel free to wordsmith. I figured these things are probably better documented with sources than left in PR discussions.
[PR docs]:
=> Add Type annotations developer guideline

mypy.ini, setuptools/command/build_ext.py, setuptools/command/build_py.py, setuptools/command/editable_wheel.py, setuptools/command/egg_info.py, setuptools/command/install.py, setuptools/command/install_lib.py, setuptools/command/install_scripts.py, setuptools/command/sdist.py, setuptools/command/upload.py, setuptools/config/pyprojecttoml.py, setuptools/dist.py, setuptools/extension.py, setuptools/tests/__init__.py, setuptools/tests/test_build_ext.py
Fix most mypy `attr-defined` & pyright `reportAttributeAccessIssue` for #2345 by explicitly defining attributes on classes
I have some ideas on how to address the last `attr-defined` cause by `DistributionMetadatalicense_files` `DistributionMetadata.license_file`, but that's out of scope for this PR.
`get_finalized_command`, `get_command_obj` and `get_command_class` still require casting, but that should be fixed in typeshed.
[PR docs]:
=> Fix most mypy `attr-defined` & pyright `reportAttributeAccessIssue` by explicitly defining attributes on classes

setuptools/command/setopt.py
@abravalheri I noticed this abstractmethod was redundant (doesn't break anything) by marking the class as `ABC` after https://github.com/pypa/setuptools/pull/4503 was merged
[PR docs]:
=> Redundant abstractmethod run in `setuptools.command.setopt.option_base`

newsfragments/4554.misc.rst, setuptools/sandbox.py
If I'm not mistaken, this looks like support for Python 2's https://docs.python.org/2.7/library/functions.html#file that never got cleaned up. Where `_file` should always be `None` nowadays.
[PR docs]:
=> Remove `sandbox`'s Python 2 `builtins.file` support

newsfragments/4559.misc.rst, setuptools/config/_apply_pyprojecttoml.py
Ignore deprecated entrypoint from wheel and avoid warning pypa/wheel#631 when validating experimental options from `pyproject.toml`.
Closes 
[PR docs]:
=> Prevent accidental warning from deprecated entrypoint in `pypa/wheel#631`

newsfragments/4565.misc.rst, setuptools/tests/integration/test_pip_install_sdist.py
In integration test:
- Replace `pip install -I` with `pip install --force-reinstall`
- Do not install `wheel` as it is no longer a build dependency (it also no longer gets automatically installed in the build env in regular workflows).
Closes #4564 
[PR docs]:
=> Use `--force-reinstall` in integration test and skip wheel

newsfragments/4420.bugfix.rst, setuptools/command/bdist_wheel.py
=> Prevent abi3 from being used with no-GIL interpreter

newsfragments/+61911d95.bugfix.rst, setuptools/_distutils/_modified.py, setuptools/_distutils/dist.py, setuptools/_distutils/tests/test_modified.py
- **Let _show_help() use commands instead of self.commands**
- **Enforce flake8-bugbear (B) and isort (I) ruff rules**
- **Add test capturing missed expectation.**
- **Ensure a missing target is still indicated as 'sources are newer' even when there are no sources.**
Style changes plus pypa/distutils#276 and pypa/distutils#284.
[PR docs]:
=> Sync with distutils@30b7331

setuptools/command/bdist_rpm.py, setuptools/command/build.py, setuptools/command/build_clib.py, setuptools/command/egg_info.py, setuptools/command/register.py
This was already done here and there for various commands as needed as they came up from type-checking more code. Figured I may as well go ahead and make it complete.
[PR docs]:
=> Override distribution attribute type in all distutils-based commands

newsfragments/4579.bugfix.rst, pkg_resources/__init__.py, setuptools/__init__.py, setuptools/command/setopt.py, setuptools/sandbox.py
Closes #4579
#4503 had an unintended consequence of causing potential metaclass subclassing strictess issues. The goal was only to give additional information for static type-checking.
[PR docs]:
=> Remove `ABCMeta` metaclass, keep `abstractmethod`s

mypy.ini, setuptools/__init__.py, setuptools/build_meta.py, setuptools/command/build_ext.py, setuptools/command/sdist.py, setuptools/config/setupcfg.py, setuptools/dist.py, setuptools/errors.py, setuptools/extension.py
Actually type-check targeting all Python versions in CI, including 3.12 & 3.13
I'd rather if it was possible for the CI to tell mypy which python version to target to override `python_version` config.
[PR docs]:
=> Type-check on all Python versions

pyproject.toml
=> Pin Ruff to a lower bound rather than pinning pytest-ruff to an upper bound

pyproject.toml, setuptools/tests/integration/test_pip_install_sdist.py
https://github.com/pypa/setuptools/commit/0588af036a2b38318c99b39a3549d587b6eb1b4b added extras specific for type-checking and "checkers" (lint+format). I think other dependencies that are only specified for these tests should also be moved there ?
[PR docs]:
=> Move static-checkers-only dependencies into their dedicated extras

setuptools/command/build_ext.py, setuptools/tests/test_build_ext.py
When `Cython.Distutils.build_ext` is not installed, `_build_ext` is `Any` which trickles down issues. Like being an invalid type to subclass, missing attributes, always matching the first overload, etc.
[PR docs]:
=> Avoid type issues with `_build_ext` being `Any`

newsfragments/4592.misc.rst, setuptools/command/build_ext.py
Extracted from https://github.com/pypa/setuptools/pull/4192/ . Fixes mypy and pyright errors when `get_ext_filename` is annotated
[PR docs]:
=> Make `command.build_ext.get_ext_filename` typesafe

docs/userguide/pyproject_config.rst
In the example for dynamic specifying a version from a package attribute, change `VERSION` to `__version__`.
`__version__` is the most common convention, I think it's better to have the example reflect that.
See the discussion in:
https://github.com/pypa/packaging.python.org/pull/1580
and many other discussions --
=> change VERSION to __version__ in the example

newsfragments/4585.feature.rst, setuptools/package_index.py
Docstring said "like a namedtuple", but I don't see why it can't be simplified to a `NamedTuple`
Contributes to #2345 and my batches of dunder typing (this was the only untyped `__iter__` outside tests)
One potential difference is the repr:
`'<setuptools.package_index.Credential object at 0x000001D0C827AD90>'`
`Credential(username='a', password='b')`
(but `__str__` already printed the values)
[PR docs]:
=> Made `setuptools.package_index.Credential` a `NamedTuple`

pkg_resources/__init__.py, setuptools/command/build_py.py, setuptools/command/develop.py, setuptools/command/test.py, setuptools/config/expand.py, setuptools/config/setupcfg.py, setuptools/tests/test_build_meta.py
Work towards #2345 
Reduce changes in #4504
I typed all `__getstate__`, `__setstate__`, `__setitem__` , `__getitem__` and  `__getattr__` dunders (didn't find any `__setattr__`)
[PR docs]:
=> Type all get/set dunders

pkg_resources/__init__.py
Work towards #2345 
I typed all `__ne__`, `__eq__`, `__ge__`, `__gt__`, `__le__`, `__lt__`, `__hash__`, `__bool__`, `__add__`, and `__iadd__`
[PR docs]:
=> Type all comparison/operators dunders

_distutils_hack/__init__.py, setuptools/command/editable_wheel.py, setuptools/config/expand.py, setuptools/config/pyprojecttoml.py, setuptools/sandbox.py
Work towards #2345
Reduce changes in #4192 and #4504
I typed all `__enter__` and `__exit__` (didn't find any `__aenter__` or `__aexit__`)
Note here that `object` param type stands for "Unused even in subclass" and `object` return type in a protocol stands for "callable return value unused/unchecked". I can use `_typeshed.Unused` instead if that's clearer.
[PR docs]:
=> Type all context manager dunders

mypy.ini
As requested here: https://github.com/jaraco/skeleton/pull/136#discussion_r1714057809
[PR docs]:
=> Link to issues in mypy.ini for non py.typed dependencies

MANIFEST.in, setuptools/command/egg_info.py, setuptools/command/sdist.py, setuptools/tests/test_sdist.py
This is a follow up on #4602: instead of doing an ad-hoc exclusion rule for setuptools' own `MANIFEST.in`, this PR proposes to always ["prune"](https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html#using-manifest-in) the `.tox`, `.nox` and `.venv` top-level directories.
This is done by extending the `sdist.prune_file_list` method from distutils using the same technique that the original method already uses to exclude directories like `.git` or `.svn`.
I am only excluding top-level `.tox|.nox|.venv` directories to be conservative and minimise Hyrum's law [unexpected consequences](https://xkcd.com/1172/).
This PR also removes the custom implementation on `setuptools.command.egg_info:manifest_maker.prune_file_list` and instead let the class just access the  parent's class …
=> Exclude top-level `.tox|.nox|.venv` from sdist

newsfragments/4548.feature.rst, setuptools/command/easy_install.py, setuptools/tests/test_easy_install.py
Follow-up to https://github.com/pypa/setuptools/pull/4505#discussion_r1709867572 
As mentioned in that comment, let's include this PR in a major update since, although an edge case, isn't backwards compatible.
Changed the type of error raised by `setuptools.command.easy_install.CommandSpec.from_param` on unsupported argument from `AttributeError` to `TypeError`.
[PR docs]:
=> Raise `TypeError` in `easy_install.CommandSpec.from_param`

setuptools/command/easy_install.py, setuptools/command/editable_wheel.py, setuptools/compat/py312.py, setuptools/namespaces.py
We should wait until a compatible version of Python3.13 is released (probably a beta).
- Use UTF-8 to write `.pth` files on Python 3.13
- When reading `.pth` on Python 3.13 tries first UTF-8 and then fallback to locale (this is done to avoid errors caused by mixing installations created by different versions of `setuptools` in the same environment)
See reasoning in https://github.com/python/cpython/issues/77102
Closes 
[PR docs]:
=> Adopt UTF-8 for  `.pth` files on Python 3.13

docs/development/developer-guide.rst
I created these paragraphs based on the comment in https://github.com/pypa/setuptools/pull/4212. The idea is to document to setuptools developers how the `compat/pyXX` convention works.
Closes 
[PR docs]:
=> Document contributors convention to respect skeleton and distutils

.github/workflows/pyright.yml, pyrightconfig.json
Config-only changes to make comments more up to date
[PR docs]:
=> Update pyright configs comments

newsfragments/1902.bugfix.rst, setuptools/msvc.py
- **Prefer generator expression in VCRuntimeRedist**
- **In return_env, avoid checking `isfile`.**
- **Add type annotation for VCRuntimeRedist and update the docstring to reflect the behavior.**
Closes 
[PR docs]:
=> Fix TypeError in VCRuntimeRedist

newsfragments/4615.bugfix.rst, setuptools/_distutils/_msvccompiler.py, setuptools/_distutils/command/sdist.py, setuptools/_distutils/tests/test_msvccompiler.py, setuptools/tests/test_sdist.py
- **In sdist.prune_file_list, support build.build_base as a pathlib.Path.**
- **Add test capturing missed expectation.**
- **Enable the test**
- **Add news fragment.**
Merges incidental changes in distutils:
- **Use monkeypatch to monkeypatch.**
- **Disable TRY400 so it doesn't cause problems in other branches. Disable RUF100 to prevent it from failing in this branch. Ref pypa/distutils#292**
Closes #4615
[PR docs]:
=> Restore support for pathlib paths in build_base

docs/development/developer-guide.rst, mypy.ini, setuptools/command/easy_install.py
=> Fix a couple typos found by codespell

newsfragments/4617.feature.rst, setuptools/command/bdist_wheel.py, setuptools/tests/test_bdist_wheel.py, setuptools/tests/test_build_meta.py
=> Deprecate `bdist_wheel.universal`

newsfragments/1825.bugfix.rst, setuptools/build_meta.py, setuptools/command/bdist_wheel.py, setuptools/tests/test_bdist_wheel.py
Allow ``dist-info-dir`` to be passed to `bdist_wheel`.
More importantly, fixes the `build_wheel` PEP-517 interface to treat the given metadata as per the spec. 
With this change, I was able to verify that I could:
```
python setup.py dist_info
touch setuptools-74.1.2.post20240913.dist-info/FOO
python setup.py bdist_wheel --dist-info-dir setuptools-74.1.2.post20240913.dist-info/
```
And the resulting wheel contained my desired metadata file. My personal goal is to support this behaviour in PEP-517 build backends, and to write a setuptools build backend wrapper which injects such metadata (I need to do something like `setuptools-ext` does). Presently, the functionality does not exist, you end up having to post-process the built wheel (hence the [complexity that exists in …
=> Support the metadata directory (as per PEP-517) for build_wheel

docs/conf.py
As per https://github.com/pypa/setuptools/pull/4643#issuecomment-2359893642, it seems that `sphinx` simply append a `/` even if it already exists when creating intersphinx links, and that result in some redirection notifications when building the docs.
This PR removes the trailing `/`, so that these verbose notifications are no longer present.
Closes 
[PR docs]:
=> Remove trailing / from `interspinx_mapping` to avoid verbose logs

.github/workflows/main.yml, pyproject.toml, setuptools/dist.py
Extracted from #4670 (mostly)
Temporary workaround for #4672, while a final decision is not made.
Closes 
[PR docs]:
=> Temporary workaround for disruptive due deprecations

.github/workflows/main.yml, newsfragments/4680.bugfix.rst, pyproject.toml, setuptools/command/egg_info.py
Alternative to https://github.com/pypa/setuptools/pull/4670
This is a much more minimal and surgical change than the originally proposed in #4670, so less controversial (which hopefully minimises the risks in merging it).
Note however that without the other changes in #4670, setuptools will keep to "temporarily" add empty `.egg-info` directories in `sys.path`... What this PR does is to simply avoid iterating over entry-points while the directory is empty.
Closes #4670
[PR docs]:
=> Avoid iterating over entry-points while an empty `.egg-info` exists in `sys.path`

newsfragments/4578.bugfix.rst, newsfragments/4578.feature.rst, setuptools/dist.py, setuptools/tests/test_dist.py
Split from https://github.com/pypa/setuptools/pull/4575
Fixes a `TypeError` when a ``Distribution``'s old included attribute was a `tuple`.
Note that I'm purposefully avoiding using `Iterable`, `Sequence` or `Container` because `str` matches all those. And I didn't wanna complicate the checks to allow "any iterable except str" (maybe in a future PR)
[PR docs]:
=> Type sequence checks in setuptools/dist.py

newsfragments/4684.bugfix.rst, setuptools/build_meta.py
This is a workaround identified in https://github.com/pypa/setuptools/pull/4647#issuecomment-2395672359
We should be able to see the integration tests failing or passing for PyYAML in https://github.com/pypa/setuptools/actions/runs/11353165220
Closes #4683 
[PR docs]:
=> Workaround for `bdist_wheel.dist_info_dir` problems

mypy.ini, pkg_resources/__init__.py, pyproject.toml, setuptools/build_meta.py, setuptools/config/expand.py, setuptools/config/pyprojecttoml.py, setuptools/config/setupcfg.py, setuptools/msvc.py, setuptools/tests/config/test_setupcfg.py, setuptools/tests/test_build_ext.py, setuptools/tests/test_editable_install.py
Ref https://github.com/jaraco/skeleton/issues/143
[PR docs]:
=> Re-enable mypy and sync mypy.ini from skeleton

.github/workflows/pyright.yml, mypy.ini, pkg_resources/__init__.py, pyproject.toml, setuptools/_path.py, setuptools/command/__init__.py, setuptools/command/sdist.py
Bump mypy to 1.12 and pyright to 1.1.385
Closes #4678
[PR docs]:
=> Bump mypy to 1.12 and pyright to 1.1.385

ruff.toml, setuptools/package_index.py, setuptools/tests/test_egg_info.py
In https://github.com/astral-sh/ruff/issues/12754 it was found that the original pyupgrade rule `unpacked-list-comprehension (UP027)` is based on lacks justification and is actually slower in cases relevant to unpacking (ie: small sizes). The rule is deprecated in https://github.com/astral-sh/ruff/pull/12843 for Ruff 0.6
This PR disables the rule now before there's any usage of it. I also searched for `,.*? = \(` to find any code that would've triggered it and revert.
[PR docs]:
=> Disable and revert `unpacked-list-comprehension (UP027)`

newsfragments/4560.misc.rst, pyproject.toml
Closes #4461
The vendored version was already 4.2.2, so this change is only to help platforms lacking `ctypes` support install setuptools seamlessly.
[PR docs]:
=> Bump declared platformdirs dependency to >= 4.2.2

newsfragments/4575.feature.rst, setuptools/command/_requirestxt.py, setuptools/command/egg_info.py, setuptools/dist.py, setuptools/tests/test_core_metadata.py, setuptools/tests/test_dist.py
Allows using `dict` as an ordered type in ``setuptools.dist.check_requirements``
https://github.com/pypa/setuptools/pull/4574 Gave me the idea for this PR
[PR docs]:
=> Using `dict` as an `OrderedDict` and allowed using `dict` as an ordered type in `setuptools.dist.check_requirements`

newsfragments/4696.bugfix.rst, setuptools/config/_apply_pyprojecttoml.py, setuptools/tests/config/test_pyprojecttoml_dynamic_deps.py
This is reminiscent of https://github.com/pypa/setuptools/pull/3306.
It is another situation where PEP 621 does not allow mixing dynamic and static configurations.
Without explicitly listing `optional-dependencies` in `dynamic` users cannot rely on `setup.py` to specify `extras_require` -- in turn, when `optional-dependencies` *is present* in `dynamic`, then it cannot be listed as an static configuration.
Therefore, the only valid situation according to PEP 621, is that static `optional-dependencies` are honoured exactly as provided, without modifications (this means ignoring any `extras_require` previously set)..
Closes https://github.com/pypa/setuptools/issues/3300
[`newsfragments/`]: …
=> Fix "residual" invalid dynamic behaviour of `optional-dependencies`

newsfragments/4567.bugfix.rst, setuptools/command/build_clib.py, setuptools/modified.py, setuptools/tests/test_distutils_adoption.py
The following code should now work as expected in all cases:
```py
from setuptools.modified import newer_pairwise_group
from distutils.error import DistutilsError
try:
newer_pairwise_group(...)
except DistutilsError:
pass
```
I'm not entirely certain my test is correct. Hopefully it should be.
[PR docs]:
=> Ensured all methods in `setuptools.modified` raise a consistant `distutils.error.DistutilsError` type

mypy.ini, pyproject.toml
Works towards #2345
I split out wheel and distutils sections in mypy config since those are not actionable.
[PR docs]:
=> Bump jaraco.test to py.typed version 5.5 in test extra

ruff.toml, setuptools/command/easy_install.py, setuptools/tests/test_manifest.py
Setuptools conforms to all the Ruff-implemented Pyflakes and Perflint rules except `PERF203` and a single instance of `PERF102`. So we can be less picky about their selection.
`PERF203` is worth looking at, but is often a micro-optimisation with false-positives, let's not block the CI on that. I applied it on some tests.
[PR docs]:
=> Ruff: enable all pyflakes and perf rules

.pre-commit-config.yaml, setuptools/command/alias.py, setuptools/command/bdist_wheel.py, setuptools/command/install.py, setuptools/tests/config/test_setupcfg.py, setuptools/tests/test_build_py.py, setuptools/tests/test_easy_install.py
See https://github.com/jaraco/skeleton/issues/149.
- Bump version of `ruff` hook in `.pre-commit-hooks.yaml`
- Run `ruff` autoformat.
Hopefully this will not have merge conflicts when we merge `skeleton` next time 🤞 (https://github.com/jaraco/skeleton/pull/150). 
This PR is just to keep things working and prevent the CI from failing in unrelated PRs. We can change the approach in a follow up.
[PR docs]:
=> Workaround for clash between `ruff` in `pre-commit` hook and `pytest-ruff`

newsfragments/4674.bugfix.rst, setuptools/command/bdist_wheel.py, setuptools/tests/test_bdist_wheel.py
When creating a wheel using the debug version of Python 3.13 on Windows, ensure that the `"d"` flag is in the ABI tag.
Closes #4674
[PR docs]:
=> Fix wheel ABI tag for debug Python 3.13 on Windows

.github/workflows/main.yml, .github/workflows/pyright.yml, mypy.ini, pyrightconfig.json, ruff.toml, setuptools/tests/test_easy_install.py
Since https://github.com/pypa/setuptools/commit/e47994c81ce3e97502f761bdef60b20fe72bf02a we are having problems with 3.8.
This PR updates the versions to support the oldest and newest supported stable Python versions.
Closes #4717
[PR docs]:
/cc @Avasam for `pyright` GHA.
=> Bump min Python version for GHA (and fix spurious CI error)

pkg_resources/__init__.py, pkg_resources/tests/test_resources.py, setuptools/command/bdist_wheel.py, setuptools/command/easy_install.py, setuptools/command/egg_info.py, setuptools/package_index.py, setuptools/tests/test_easy_install.py, setuptools/tests/test_egg_info.py
Granted this may be a matter of preference, but I do believe it helps in clarity and "explicit > implicit".
[PR docs]:
=> Consistently using `sys.version_info` as a `NamedTuple`

pkg_resources/__init__.py
I commented `[lint.flake8-annotations] ignore-fully-untyped = true` in `ruff.toml` then ran `ruff check pkg_resources --select=ANN2 --fix --unsafe-fixes`.
I removed 3 `-> None` that were revealing hidden mypy issues to keep the changes here completely automated.
[PR docs]:
=> pkg_resources ANN2 autofixes for fully untyped functions

setuptools/package_index.py
Implements @Avasam's suggestion in https://github.com/pypa/setuptools/pull/4718#issuecomment-2448304407.
Closes 
[PR docs]:
=> Add comment explaining the origin of workaround for `_splituser`

setuptools/_path.py
Implement @Avasam suggestions from https://github.com/pypa/setuptools/pull/4718#issuecomment-2448099867:
> You can move `setuptools._path.StrPat` out of the `TYPE_CHECKING` check
Closes 
[PR docs]:
=> Move `setuptools._path.StrPath` out of the `if TYPE_CHECKING` (Python 3.9+)

setuptools/sandbox.py
Follow-up to #4504, works towards #2345
Given that `AbstractSandbox` isn't even public API (afaik) and that the methods are created based on os availability, I figured simply marking it as "having dynamically created methods" was cleaner than trying to duplicate all the methods in a `TYPE_CHECKING` block like https://github.com/python/typeshed/pull/10058/files#diff-f3cbc40d076f82bceeedca2749a2d93fbb40a03e1bb4bc837de6e990823e381fR29-R56 (typeshed doesn't have any of these methods typed anyway)
This trades false-positives if trying to call one of these methods directly, for false-negatives if you try to call an `AbstractSandox` method that doesn't exist.
[PR docs]: …
=> Add fake __getattribute__ to AbstractSandbox to let type-checkers know it has a bunch of dynamic methods

ruff.toml, setuptools/__init__.py, setuptools/_path.py, setuptools/command/bdist_egg.py, setuptools/command/build_ext.py, setuptools/command/build_py.py, setuptools/command/easy_install.py, setuptools/command/egg_info.py, setuptools/command/install_scripts.py, setuptools/depends.py, setuptools/dist.py, setuptools/glob.py, setuptools/installer.py, setuptools/logging.py, setuptools/package_index.py, setuptools/sandbox.py, setuptools/tests/config/downloads/__init__.py, setuptools/tests/test_build_ext.py, setuptools/tests/test_editable_install.py, tools/build_launchers.py
Follow-up to #4504, works towards #2345
I didn't include long/complex overloads in this PR, that may come later
This has some overlap with #4711, but they can be merged in either order.
[PR docs]:
=> Re-enable ANN2 for setuptools

setuptools/command/install.py
@abravalheri for https://github.com/pypa/setuptools/pull/4709#issuecomment-2450555145
As I thought, one PR made `Distribution.get_command_class` no longer return `Any` for mypy, the other made `install.do_egg_install` type-checked. Individually they both passed the CI.
[PR docs]:
=> Fix mypy failure after multiple merges

pkg_resources/__init__.py, setuptools/_reqs.py, setuptools/build_meta.py, setuptools/command/_requirestxt.py, setuptools/command/bdist_wheel.py, setuptools/command/build_ext.py, setuptools/command/build_py.py, setuptools/command/editable_wheel.py, setuptools/config/_apply_pyprojecttoml.py, setuptools/config/expand.py, setuptools/config/pyprojecttoml.py, setuptools/config/setupcfg.py, setuptools/discovery.py, setuptools/dist.py, setuptools/monkey.py, setuptools/warnings.py, setuptools/wheel.py, tools/generate_validation_code.py
Implement @Avasam suggestions from https://github.com/pypa/setuptools/pull/4718#issuecomment-2448099867:
> - functools.lru_cache(maxsize=None) can be replaced by functools.cache
> - Callable, Generator, Iterator, Iterable, Sequence, Mapping, MutableMapping should be imported from collections.abc instead of typing
> - Type, Dict, List, Tuple should be replaced by their builtin variant
> 
The procedure used for the changes is:
1. Modify `ruff.toml` as suggested in https://github.com/pypa/setuptools/pull/4718#issuecomment-2448099867
2. Run `ruff check --fix --unsafe-fixes`
3. Manually add the missing fixes
4. Manually check all files and add improvements as necessary
5. `git restore ruff.toml` (I am leaving this decision for `skeleton` for the time being)
6. `git restore …
=> Automatic updates from Ruff for Python 3.9+

setuptools/command/install.py
numpy 1.8 only supported up to Python 3.3 . I feel like this "numpy support" is long obsolete. Making it a deprecation warning *just in case* someone else still uses it. Idk what's your shortest allowed deprecation period, I used 6 months.
[PR docs]:
=> Deprecation warning for setuptools.command._install

setuptools/command/easy_install.py, setuptools/msvc.py
Follow-up to #4504, works towards #2345
I didn't include TypeDicts for `**kwargs` params as part of this PR. keyword args will be its own thing.
[PR docs]:
=> Merge TypedDicts from typeshed

pkg_resources/tests/test_resources.py, pyproject.toml, ruff.toml, setuptools/command/install_lib.py, setuptools/tests/config/test_apply_pyprojecttoml.py, setuptools/tests/integration/test_pip_install_sdist.py, setuptools/tests/test_bdist_egg.py, setuptools/tests/test_easy_install.py, setuptools/tests/test_packageindex.py, setuptools/tests/test_setuptools.py, setuptools/tests/test_wheel.py
In this PR I've enabled https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt linting in Ruff and configured to the current preferences.
[PR docs]:
=> Ruff: lint pytest

pkg_resources/tests/test_pkg_resources.py, pkg_resources/tests/test_resources.py, ruff.toml, setuptools/tests/config/test_apply_pyprojecttoml.py, setuptools/tests/config/test_expand.py, setuptools/tests/config/test_pyprojecttoml.py, setuptools/tests/integration/test_pip_install_sdist.py, setuptools/tests/test_bdist_wheel.py, setuptools/tests/test_build_meta.py, setuptools/tests/test_config_discovery.py, setuptools/tests/test_core_metadata.py, setuptools/tests/test_dist.py, setuptools/tests/test_dist_info.py, setuptools/tests/test_distutils_adoption.py, setuptools/tests/test_egg_info.py, setuptools/tests/test_glob.py, setuptools/tests/test_logging.py, setuptools/tests/test_wheel.py
Follow-up to https://github.com/pypa/setuptools/pull/4557#discussion_r1824409142
1. Remove the `ruff.lint.flake8-pytest-style.parametrize-names-type` config from `ruff.toml`
2. Run `ruff check --fix --unsafe-fixes`
3. Run `ruff format`
[PR docs]:
=> Set Ruff's pytest's parametrize-names-type to default (tuple)

newsfragments/+f0b61194.bugfix.rst, setuptools/_distutils/dir_util.py, setuptools/_distutils/tests/test_dir_util.py
- **Restore expectation that mkpath returns a list of the items it created.**
- **Remove support for returning the directories created in mkpath, unused.**
- **Add test capturing missed expectation.**
- **Correct the order of operations to ensure that failed attempts aren't cached and are thus retried on subsequent operations.**
- **Add news fragment.**
Closes 
[PR docs]:
=> Merge bugfixes from distutils

_distutils_hack/__init__.py, pkg_resources/tests/test_resources.py, pkg_resources/tests/test_working_set.py, setuptools/__init__.py, setuptools/build_meta.py, setuptools/command/develop.py, setuptools/command/easy_install.py, setuptools/command/editable_wheel.py, setuptools/command/egg_info.py, setuptools/config/expand.py, setuptools/config/pyprojecttoml.py, setuptools/config/setupcfg.py, setuptools/depends.py, setuptools/discovery.py, setuptools/extension.py, setuptools/msvc.py, setuptools/package_index.py, setuptools/sandbox.py, setuptools/wheel.py
Works towards step 6.2 of https://github.com/pypa/setuptools/issues/2345#issuecomment-1627561833
This will reduce changes from adding return types from typeshed
I commented out `ignore-fully-untyped` in `ruff.toml` then ran `ruff check --fix --unsafe-fixes --extend-exclude=setuptools/tests --select=ANN204`.
Then I removed 3 added return types that were revealing hidden mypy issues to keep the changes here completely automated.
[PR docs]:
=> ANN204 (missing return type for special methods) autofixes

pyproject.toml
Adds a minimum requirement to jaraco.functools
Closes #4665
=> Use minimum requirement for jaraco.functools

newsfragments/4611.feature.rst, setuptools/config/pyprojecttoml.py, setuptools/tests/config/test_pyprojecttoml.py
Closes #4459 using the approach mentioned in https://github.com/pypa/setuptools/issues/4459#issuecomment-2269491725.
[PR docs]:
=> Allow user to skip validation of `pyproject.toml` via env var

setuptools/_shutil.py, setuptools/command/bdist_wheel.py, setuptools/command/dist_info.py, setuptools/command/easy_install.py, setuptools/command/editable_wheel.py, setuptools/command/rotate.py, setuptools/tests/test_bdist_wheel.py, setuptools/tests/test_shutil_wrapper.py
I noticed that there are at least 2 implementations of `shutil.rmtree` callbacks in setuptools: one for `easy_install` and one for `bdist_wheel`. There is also other places in setuptools that we don't have those callbacks (so potentially still subject to errors on Windows?).
So this PR tries to unify these 2 separated implementations.
I have chosen to extract the implementation from `easy_install`.
One notable difference though is that `bdist_wheel`'s implementation always try to apply the `chmod` callback when it fails, while the `easy_install` implementation is more conservative and only applies the callback on Windows (similar to the suggestion in `https://github.com/python/cpython/issues/87823#issuecomment-1093908280`)... So that might generate a bit of change in behaviour, but with a …
=> Refactor/unify/extract `shutil.rmtree` callbacks (and avoid repetition)

newsfragments/4746.feature.rst, setuptools/config/pyprojecttoml.py, setuptools/tests/config/test_pyprojecttoml.py
This reverts commit 913d50a130b3c92636978b1d0e0ace8c60c23a8e.
Related to the discussions in #4459. 
[PR docs]:
=> Revert "Allow user to skip validation of pyproject.toml via env var"

MANIFEST.in, pyproject.toml
https://github.com/pypa/setuptools/blob/main/setuptools/_vendor/ruff.toml is currently being included in wheels, which is probably unintended since it's only relevant to maintainers.
=> Omit ruff config from wheel distributions

docs/userguide/quickstart.rst
The original reference pointed to python generic [namespace](https://docs.python.org/3.11/glossary.html#term-namespace),  in the python glossary, which is wrong. What it want to point to is [package namespace](https://docs.python.org/3.11/glossary.html#term-namespace-package).
I don't think it needs an entry in the changelog.
=> correct 'namespace' term to 'namespace-package' in quickstart doc

setuptools/tests/test_build_ext.py
https://github.com/pypa/setuptools/pull/4776#issuecomment-2565999938 CC @jaraco 
[PR docs]:
=> Fix `test_build_ext.py` on Python 3.9

pkg_resources/__init__.py, setuptools/command/_requirestxt.py, setuptools/command/bdist_wheel.py, setuptools/command/editable_wheel.py, setuptools/config/pyprojecttoml.py, setuptools/config/setupcfg.py, setuptools/dist.py, setuptools/msvc.py, setuptools/tests/test_wheel.py
Simplified some typed assignements with redundant annotations thanks to dropping Python 3.8 support. Or where the inferred type was the same as the explicit one.
[PR docs]:
=> Simplified typed assignments

.github/workflows/main.yml
I identified some recent problems in the CI:
```
creating virtual environment...
installing build...
* Creating isolated environment: venv+pip...
* Getting build dependencies for sdist...
/home/runner/work/setuptools/setuptools/_distutils_hack/__init__.py:53: UserWarning: Reliance on distutils from stdlib is deprecated. Users must rely on setuptools to provide the distutils module. Avoid importing distutils or import setuptools first, and avoid setting SETUPTOOLS_USE_DISTUTILS=stdlib. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
warnings.warn(
Traceback (most recent call last):
File "/opt/pipx/.cache/98ab2ca9c43e098/lib/python3.12/site-packages/pyproject_hooks/_impl.py", line 402, in _call_hook
raise BackendUnavailable( …
```
=> Explicit pass the Python path to pipx in CI step

newsfragments/4830.feature.rst, setuptools/_core_metadata.py, setuptools/tests/config/test_apply_pyprojecttoml.py, setuptools/tests/test_egg_info.py
Should be rebased after #4706 is merged into `feature/pep639`.
- Bump core metadata version to `2.4`
- Add `License-Expression` to core metadata
Refs:
- https://github.com/pypa/setuptools/issues/4629
- https://github.com/pypa/setuptools/pull/4829
=> Bump core metadata version to 2.4

setuptools/config/_apply_pyprojecttoml.py
Not sure why the tests where not failing, but I think this is the way we ensure `dist.metadata.license_expression` gets set instead of `dist.license_expression`.
(I guess the test `hasattr(dist.metadata, field)` is true? Is it always true? If not when it is false?)
[PR docs]:
=> Ensure `_apply_pyproject` sets field on `dist.metadata` object not on `dist`

newsfragments/4706.feature.rst, newsfragments/4728.feature.rst
It seems that `sphinx` do not like something in the docs:
This is an attempt to handle that.
Closes 
[PR docs]:
=> Attempt to comply with `sphinx` warning when building docs

docs/userguide/miscellaneous.rst, docs/userguide/pyproject_config.rst, newsfragments/4837.feature.rst, setuptools/config/_apply_pyprojecttoml.py, setuptools/tests/config/test_apply_pyprojecttoml.py, setuptools/tests/test_build_meta.py
Deprecate `tools.setuptools.license-files` in favor of `project.license-files`.
Ref #4829
/CC @abravalheri
=> Deprecate tools.setuptools.license-files

newsfragments/4840.feature.rst, setuptools/config/_apply_pyprojecttoml.py, setuptools/tests/config/test_apply_pyprojecttoml.py, setuptools/tests/test_build_meta.py, setuptools/tests/test_sdist.py
Alongside with https://github.com/pypa/setuptools/pull/4838, the objective of this PR is to introduce more deprecation warnings and prepare for an eventual feature removal in the spirit of PEP 639.
I am assuming that if a project is using `pyproject.toml` with `setuptools` it is relatively new and the maintainers are likely to be around.
Also the best is to introduce the warning as soon as possible, so that the clock starts ticking for the removal.
/cc @cdce8p 
[PR docs]:
=> Add warning for deprecated `project.license` as TOML table (PEP 639-related)

setuptools/_core_metadata.py, setuptools/config/_apply_pyprojecttoml.py, setuptools/dist.py, setuptools/tests/config/test_apply_pyprojecttoml.py, setuptools/tests/test_core_metadata.py
This PR improves the ongoing implementation of PEP 639 so that it plays nicely with all the restrictions regarding PEP 643 and `dynamic` in `pyproject.toml`...
Ref: https://github.com/pypa/setuptools/pull/4829#issuecomment-2666587077
/cc @cdce8p 
[PR docs]:
=> Improve interop between `Dynamic` (`METADATA`) and `dynamic` (`pyproject.toml`) with `license`/`license_expression`/`license_files`

newsfragments/4856.bugfix.rst, pkg_resources/__init__.py, pkg_resources/tests/test_pkg_resources.py
Alternative to https://github.com/pypa/setuptools/pull/4855
Closes #4853.
/cc @di: We wore working kind of in parallel on this. What are your thoughts? I don't have any strong preference regarding the 2 proposed approaches (either #4855 or #4856 are fine to me).
[PR docs]:
=> Update `WorkingSet.find` to consider standardised `.dist-info` directory names.

docs/conf.py
I was under the wrong impression that the template was automatically adding the button.
This PR contains the configurations to do so.
The idea is to facilitate contributions in the docs.
Ref: https://pradyunsg.me/furo/customisation/top-of-page-buttons/
Closes 
[PR docs]:
=> Enable 'edit this page' button in the docs

newsfragments/4838.feature.rst, setuptools/dist.py, setuptools/tests/config/test_apply_pyprojecttoml.py, setuptools/tests/test_core_metadata.py
>  The PEP specifies that tools should reject any patterns which contain not-approved chars.
Furthermore, it should be an error if a pattern doesn't match any files.
Ref: https://github.com/pypa/setuptools/pull/4829#issuecomment-2663706134
This by no means introduces an exhaustive check, just the low hanging fruits.
I intentionally do not analyse each pattern individually here to avoid wreaking too much havoc (imagine e.g. project templates that adds a very general catch all list of patterns in `setup.cfg`).
Regarding the `glob` patterns, I am keeping loose for the time being, would like to avoid adding a regex for each pattern if possible, but open to it...
/cc @cdce8p 
[`newsfragments/`]: …
=> Add initial warnings regarding `license-files` glob patterns.

newsfragments/4866.bugfix.rst, setuptools/_distutils/ccompiler.py, setuptools/_distutils/command/config.py
Closes pypa/setuptools#4866
Closes 
[PR docs]:
=> In config command, move to eager imports. Restore LinkError to ccompilers module.

ruff.toml
These configs are now repeated with skeleton upstream and can be removed.
- [N/A] Changes have tests
- [N/A] News fragment added in [`newsfragments/`].
[PR docs]:
=> Reduce Ruff configs that duplicates upstream after skeleton merge

.bumpversion.cfg, NEWS.rst, pyproject.toml
- **Merge pull request #4766 from di/fix/3777**
- **Repoint the news fragment.**
- **Bump version: 75.3.0 → 75.3.1**
Closes #4877
[PR docs]:
=> Backport bugfix for wheel naming for Python 3.8

newsfragments/4899.bugfix.rst, setuptools/config/_apply_pyprojecttoml.py
Instead we defer to the follow-up deprecation warning.
Rationale in https://github.com/pypa/setuptools/pull/4837#discussion_r2004983349
[PR docs]:
=> Avoid raising exception when license-files is defined outside of `pyproject.toml`

newsfragments/4898.bugfix.rst, pyproject.toml, setuptools/_normalization.py, setuptools/dist.py
Motivated by a well-known limitation of the vendoring system.
Closes #4894
[PR docs]:
=> Defer import error for `packaging.licenses` in environments with `packaging<24.2`

newsfragments/4870.removal.rst, setuptools/dist.py, setuptools/tests/config/test_setupcfg.py
@jaraco, this is a possible approach for #4864, if we are feeling brave.
But it can break packages that have not addressed the warning. 
Closes #4864
[PR docs]:
=> Disallow deprecated dash-separated and uppercase options in setup.cfg

newsfragments/4909.misc.rst, setuptools/tests/integration/test_pip_install_sdist.py
Requests contain an invalid `setup.cfg` and will fail with the removal of deprecated support for dash-separated fields in `setup.cfg`.
This removes it from the integration tests until it is handled upstream: https://github.com/psf/requests/pull/6920.
Closes 
[PR docs]:
=> Temporarily remove `requests` from integration tests

.github/workflows/main.yml, newsfragments/4911.bugfix.rst, setuptools/dist.py, setuptools/tests/config/test_setupcfg.py
=> Revert removals introduced in `v78.0.0`

NEWS.rst
Fix typo at https://setuptools.pypa.io/en/stable/history.html#v77-0-0
- [n/a] News fragment added in [`newsfragments/`].
[PR docs]:
---
Thank you for adding PEP 639 support!
=> Fix typo: `pyproject.license` -> `project.license`

newsfragments/4946.bugfix.rst, setuptools/package_index.py
- **Extract _resolve_download_filename with test.**
- **Add a check to ensure the name resolves relative to the tmpdir.**
- **Extract _sanitize method for sanitizing the filename.**
- **Rely on re.sub to perform the decision in one expression.**
- **Add news fragment.**
Closes 
[PR docs]:
=> More fully sanitize the filename in PackageIndex._download_url

docs/userguide/development_mode.rst, newsfragments/917.removal.rst, setuptools/build_meta.py, setuptools/tests/test_build_meta.py
According to [the docs](https://github.com/pypa/setuptools/blob/8e4868a036b7fae3208d16cb4e5fe6d63c3752df/docs/userguide/development_mode.rst#legacy-behavior), pip no longer relies on this feature and that notice has been there for over two years.
Removal of this feature is required to eliminate reliance on the `develop` command, which is required to eliminate reliance on the `easy_install` command (#917).
Closes 
[PR docs]:
=> Removed support for the 'legacy-editable' feature.

newsfragments/+67050cd5.bugfix.rst, setuptools/_distutils/command/config.py, setuptools/_distutils/compilers/C/tests/test_unix.py, setuptools/_distutils/compilers/C/unix.py
- **Remove latent comment.**
- **Respect CXX when parsing linker parameters for UNIX c++ targets**
- **Add test for argument parsing for CXX targets on UNIX**
- **Fix new test case**
- **Add news fragment.**
Closes 
[PR docs]:
=> Apply distutils fix for parsing linker parameters

newsfragments/4961.bugfix.rst, setuptools/_entry_points.py, setuptools/tests/test_egg_info.py
Fixes #4961
Closes 
[PR docs]:
=> Update test to honor new behavior in importlib_metadata 8.7

.github/pull_request_template.md
Tiny nit fix: `master`->`main` in PR template
[PR docs]:
=> Tiny nit fix: `master`->`main` in PR template

newsfragments/4976.bugfix.rst, setuptools/command/easy_install.py, setuptools/tests/fixtures.py, setuptools/tests/integration/test_pbr.py, setuptools/tests/test_editable_install.py
- **Moved pbr setup into a fixture.**
- **Add a failing integration test. Ref #4976**
- **Restore ScriptWriter and sys_executable properties.**
- **Render the attributes dynamically.**
- **Add the deprecation warning to attribute access.**
Closes #4976
[PR docs]:
=> Restore pbr compatibility

docs/userguide/development_mode.rst, newsfragments/4984.feature.rst, setuptools/command/editable_wheel.py, setuptools/compat/py310.py, setuptools/tests/test_editable_install.py
Fixes #4984
Closes 
[PR docs]:
=> By default, provide a much more concise error message.

newsfragments/4982.misc.rst, setuptools/tests/integration/test_pbr.py, setuptools/tests/test_develop.py, setuptools/tests/test_editable_install.py
Mark a few new tests that try to install stuff from PyPI via `pip` as `uses_network`.
To reproduce:
```
tox -e py313
sudo unshare -n sudo -u $USER sh -c '. .tox/py313/bin/activate && pytest -m "not uses_network"'
```
[PR docs]:
=> Mark new tests as `uses_network`

docs/conf.py, docs/userguide/index.rst, docs/userguide/interfaces.rst
=> Add documentation describing which interfaces are supported.

newsfragments/3085.feature.rst, pkg_resources/__init__.py, setuptools/_scripts.py, setuptools/command/bdist_egg.py, setuptools/command/build_ext.py, setuptools/command/egg_info.py, setuptools/command/install_scripts.py, setuptools/tests/contexts.py, setuptools/tests/test_dist_info.py, setuptools/tests/test_windows_wrappers.py
Removes the remaining references to pkg_resources in the Setuptools codebase.
All that remains in the setuptools package relying on pkg_resources are tests for pkg_resources-style namespace packages.
- **Remove comment referring to pkg_resources.**
- **In bdist_egg, remove reliance on pkg_resources.**
- **Convert stub into a single string for easier human parsing.**
- **In build_ext, remove reliance on pkg_resources.**
- **Converted install_scripts and _scripts to prefer importlib.metadata over pkg_resources.**
- **Add a compatibility shim and warning for legacy use on ScriptWriter.get_args**
- **Prefer importlib.resources in _scripts.**
- **Remove unused context manager.**
- **Adapt test_distinfo to test_version and migrate to use importlib.metadata.**
- **Removed test_version and …
=> Remove more reliance on pkg_resources

newsfragments/4995.misc.rst, setuptools/tests/test_windows_wrappers.py
Fix the error in https://github.com/pypa/setuptools/actions/runs/14977076299/job/42072003260?pr=4994#step:11:155
([test (3.13, windows-latest)](https://github.com/pypa/setuptools/actions/runs/14977076299/job/42072003260?pr=4994#logs))
[PR docs]:
=> Fix `no attribute 'join_path'` error in Windows test

setuptools/installer.py
In `setuptools/installer` accidentally the import of `pkg_resources` was made eager when sorting out type annotations. This PR restores the previous behaviour (introduced in https://github.com/pypa/setuptools/pull/3792).
Fix https://github.com/pypa/setuptools/commit/f160c700762fcf0eef7a75ff4aa58ba262473c60#r156839662
[PR docs]:
=> Restore "delayed" aspect of existing import of `pkg_resources` in `setuptools/installer.py`

newsfragments/4996.misc.rst, setuptools/__init__.py
There are [2 methods](https://github.com/pypa/setuptools/blob/v80.5.0/setuptools/__init__.py#L178-L212) defined for `setuptools.Command` that just look like copies of the ones defined in `distutils.cmd.Command` (except for formatting, rust auto-fixes). They seem to have been introduced in #1180.
https://www.diffchecker.com/w6na9oHI/
I am struggling to see the reason why we need to re-define them, unless the code was there just for backward compatibility with old Python versions (i.e. fixes were backported into `distutils`).
I can see however that this code exists since before Python 3.6...
It definetelly exists in the stdlib in 3.9 (minimum version supported by setuptools):
https://github.com/python/cpython/blob/3.9/Lib/distutils/cmd.py#L207-L215 …
=> Remove almost identical copies of methods already defined in `distutils`

newsfragments/4997.feature.rst, setuptools/_normalization.py, setuptools/_path.py, setuptools/_reqs.py, setuptools/dist.py, setuptools/installer.py, setuptools/tests/test_dist.py
- **Remove comments referring to pkg_resources and inline a compatibility behavior with its explanation.**
- **Set the due date for installer removal (same as easy_install and package_index).**
- **Rely on importlib.metadata to detect presence of wheel.**
- **Replace pkg_resources with packaging.requirements.**
- **Migrated installer to avoid pkg_resources.**
Ref #3085 
[PR docs]:
=> Remove pkg_resources usage from installer (and more)

newsfragments/5003.feature.rst, pyproject.toml
With the changes introduced in ae480ff7c2b40442dc97fff712312549a9ed76e6, the dependency on `coherent.licensed` is unused, so I think it would be good to remove it for clean-up purposes[^1].
The approach I took here was to simply comment out the line, because I notice that is the approach previously used in #4975, but I can also simply remove all the `requires` and put an empty array if that is preferred.
[^1]: The removal should speed up build and facilitate for downstream consumers building from git repos instead of sdists.
I understand that in the long run it would be nice to have a solution for the cycles, but for now because we are not using the dependency, there is not much point in keep it around.
Closes #5002 
[`newsfragments/`]: …
=> Remove unused dependency on `coherent.licensed`

newsfragments/3085.feature.1.rst, pkg_resources/__init__.py, pytest.ini
As discussed in #5007.
Converts the warning from a DeprecationWarning to UserWarning (to increase the visibility) and adds a deadline to the messaging.
Ref #3085
[PR docs]:
=> Set a deadline for pkg_resources removal

setuptools/dist.py
The intention of the change is to provide detailed explanation for the deprecations by linking against https://github.com/pypa/setuptools/discussions/5011.
[PR docs]:
=> Add URL with detailed rationale/clarifications in deprecation warning

setuptools/msvc.py
Extracted from #4744 with additional fixes
[PR docs]:
=> Type setuptools/msvc.py dir methods and properties

ruff.toml, setuptools/command/build_py.py, setuptools/command/editable_wheel.py, setuptools/config/expand.py, setuptools/discovery.py, setuptools/tests/integration/helpers.py, setuptools/tests/test_bdist_wheel.py, setuptools/tests/test_build_meta.py, setuptools/tests/test_wheel.py
I set `[lint.flake8-annotations] ignore-fully-untyped = false` then ran `ruff check --select=ANN204 --fix --unsafe-fixes`
Step 6.3 of https://github.com/pypa/setuptools/issues/2345#issuecomment-1627561833
Some slight overlaps with https://github.com/pypa/setuptools/pull/4744
[PR docs]:
=> Ran autofixes for `missing-return-type-special-method (ANN204)` with `ignore-fully-untyped = false`

docs/userguide/interfaces.rst
Trivial change as a test to understand why Windows tests are failing on:
* #5033
Closes 
[PR docs]:
=> interfaces.rst: Fix typo discovered by codespell

docs/userguide/interfaces.rst
Some users consider adding warnings as breaking change.
That is not a universal understanding, but I think it is useful to clarify Setuptools position on the docs.
Closes #5024. 
Closes 
[PR docs]:
=> [Docs] Add note about `setuptools` not defining the introduction of warnings as a breaking change

.pre-commit-config.yaml, ruff.toml, setuptools/tests/config/test_pyprojecttoml_dynamic_deps.py, setuptools/tests/test_build_py.py
This should avoid the CI failing on unrelated changes.
Closes 
[PR docs]:
=> Adequate to newly introduced Ruff checks
