pypa/setuptools

- pkg_resources/_vendor/packaging/__about__.py
- pkg_resources/_vendor/packaging/markers.py
- pkg_resources/_vendor/vendored.txt
Update the vendored packaging to 16.6 to add support for PEP 345 environment markers.
Closes #503
> Update vendored packaging to 16.6

- pkg_resources/tests/test_resources.py
When _assertIn was removed from test_resources, the safe_repr
function was not dropped, leaving it with no callers, so drop it.
> Drop unused safe_repr function

- pkg_resources/__init__.py
- pkg_resources/tests/test_resources.py
- setuptools/tests/test_egg_info.py
Correctly deal with parsed requirements that include extras as a
marker inside WorkingSet that are populated from METADATA inside
wheels, like we get from pip>=7.
This partially reverts commit 04d10ff025e1cbef7ec93a2008c930e856045c8a.
Closes: #523
> Restore evaluating environment markers in WorkingSet

- pkg_resources/__init__.py
- pkg_resources/tests/test_resources.py
Thanks to @jaraco refactoring the marker evaluation in WorkingSet.resolve(), we can test it directly to show that the [''] guard is required.
> Reinstate the or guard in WorkingSet._markers_pass

- pkg_resources/tests/test_resources.py
In Python 3, the default order of iterables can not determined,
so comparing the repr of objects that include tuples is not static
like it is under Python 2. Compare the attributes of EntryPoint
instead, making sure to sort .attrs and .extras.
Closes: #526
> Stop comparing repr()'s in TestEntryPoint

- pkg_resources/__init__.py
Checking hundreds of possibly installed packages manually should NOT be expected of the user ;)
> This helps finding packages with bad utf

- docs/setuptools.txt
Importing from a zip file no longer significantly reduces the number
of stat calls during import, and may even slow imports down if
too many archives are added to sys.path.
The outdated rationale was noted by Thomas Güttler on distutils-sig
> Update rationale for the zip_safe flag

- MANIFEST.in
> remove _markerlib from manifest

- setuptools/command/rotate.py
Handle setuptools roate deletion when egg package is not in file format (zip-save)
but in folder format (not-zip-save).
> Handle not-zip-safe egg (folder) deletion in rotate command

- setuptools/command/setopt.py
- setuptools/tests/test_egg_info.py
egg_info is the dictionary with information that is injected
into setup.cfg. edit_config uses RawConfigParser which uses
collections.OrderedDict for all the data. Since we use a
simple dict(), when we loop through items in edit_config, we
see random behavior as a result the fields
tag_svn_revision/tag_date/tag_build are added to the setup.cfg
randomly. Let's add a OrderedDict to make it more predictable.
> Preserve order of egg_info section in setup.cfg

- pkg_resources/_vendor/packaging/__about__.py
- pkg_resources/_vendor/packaging/markers.py
- pkg_resources/_vendor/vendored.txt
This adds support for the deprecated python_implementation marker which was an undocumented setuptools marker prior to 20.2 in addition to the newer markers.
> Update packaging to 16.7

- setuptools/command/upload.py
Resolves #554 
If there is no password in `~/.pypirc`, running the upload command
```
python setup.py sdist upload
```
Will now prompt for the user password in the same manner that
```
python setup.py sdist register
```
does.
---
Let me know if I've missed anything or if there is anything that I could change!
I couldn't find any place to document this functionality (ie, in a readme or anything).
> password prompt on upload command

- ez_setup.py
This change also removes:
sys.meta_path = [importer for importer in sys.meta_path if
importer.__class__.__module__ != 'pkg_resources.extern']
from _unload_pkg_resources.
These lines were removed from the version at: https://bootstrap.pypa.io/ez_setup.py
I don't know why the code there and here differs.
> Fix setuptools url and curl wants --location to follow redirects

- setuptools/command/build_ext.py
otherwise `distutils.sysconfig.customize_compiler` does not configure the OS X compiler for -dynamiclib
See https://github.com/pypa/setuptools/issues/571
> build_ext: always import _CONFIG_VARS from distutils.sysconfig instead of sysconfig

- setuptools/command/easy_install.py
- setuptools/tests/test_easy_install.py
On debian-based systems and inside conda environments site package directories could be different from default one so we need to use information about site-packages directories from `site.py`.
This PR also fixes *VERY* annoying bug:
https://github.com/last-g/setuptools-shadowbug
Fixes: #539
> Get real `site-packages`

- setuptools/command/build_py.py
Problem encountered on Ubuntu 14.04
Fixes #190
If people need to fix this without this patch, they have to wrap their package names in `str()` like so:
```python
#!/usr/bin/env python
from __future__ import absolute_import, print_function, unicode_literals
setup(
package_dir=[
str('package_name'),
]
)
```
> Ensure package name isn't unicode in Python2 distutils

- README.rst
Apparently the documentation as moved to [Read the Docs](http://setuptools.readthedocs.io/en/latest/).
> readme: update links to documentation

- setuptools/command/sdist.py
The universal newlines mode ('U' flag) is deprecated since Python
3.4. It only replaces "\r\n" with "\n", but it doesn't split lines at
"\r" (Mac newline). In practice, the flag was useless, the
sdist.read_manifest() method already uses line.strip() and so removes
newline characters.
Example of warning:
.../setuptools/command/sdist.py:182: DeprecationWarning: 'U' mode is deprecated
manifest = open(self.manifest, 'rbU')
> Don't use deprecated 'U' flag to read manifest

- CHANGES.rst
- setuptools/msvc.py
Fixes : 
- Bad argument name #625
- Better Python 2 compatibility (FileNotFoundError => IOError)
- Python 2 on Linux compatibility #626
Also add new link from Microsoft for Visual C++ 2015 standalone compiler.
Improve Change.rst.
> msvc fixes

- setuptools/command/easy_install.py
- setuptools/command/install_scripts.py
- setuptools/tests/test_easy_install.py
- setuptools/tests/test_install_scripts.py
Fix for issue #398. As I explained there (https://github.com/pypa/setuptools/issues/398#issuecomment-225444249), this is actually a setuptools issue. I added a test to check for the problem as well as the fix itself.
This seems to be only relevant to Windows; according to https://lists.gnu.org/archive/html/bug-bash/2008-05/msg00052.html, "Unix" (whatever that means in the context) doesn't have a way to escape spaces in the interpreter name so I didn't test for that.
> Fix "failed to create process" issue on Windows

- setuptools/tests/test_msvc.py
Fix for #671.
Exception will not raise because MSVC9 is find by new behavior in `setuptools/msvc.py` line 171. 
MSVC9 was found because [there is "Microsoft Windows SDK for Windows 7 and .NET Framework 3.5 SP1" on AppVeyor VM](http://www.appveyor.com/docs/installed-software).
I skipped the raise test in this case. But, it still work if there is no MSVC9 version installed.
> Fix test failure in Appveyor around MSVC support

- setup.py
This fixes a bug introduced by commit https://github.com/pypa/setuptools/commit/5a63f386217cae916c60cc8a89ae1115df9ea7f4, that is using `os.path.chdir` instead of `os.chdir`.
Bumped into this issue after a build failing when trying to install setuptools, as reported in #688 .
> Fix: use os.chdir to change directory (fixes #688)

- pytest.ini
avoids errors in setup.py test if tox has been run
> ignore .tox in pytest

- pkg_resources/__init__.py
in `insert_on(replace=False)`
and set `replace=False` by default in `activate()`
Fixes pkg_resources modifying sys.path for all eggs with SETUPTOOLS_SYS_PATH_TECHINQUE=raw
There's one failing test where setup_requires should be loading a package at higher priority, but the `activate(replace=False)` change means it is showing up at lower priority, rather than higher.
The setup_requires code triggered in this test does indeed have several explicit `replace=True`, `remove_conflicting` flags, but the only one that seems to matter with respect to sys.path is the *implicit* one passed to `.activate()`, which is registered as a zero-argument callback in `self.callbacks`. I'll see if I can figure out a way to pass the same `replace` argument in `.add` to `.activate`.
closes #686
> only insert eggs ahead of parent if not already on path

- setuptools/msvc.py
Fix for #646:
Add `Except OSError` in addition to `Except IOError`.
> Fix for #646 : Wrong error caught in RegistryInfo.lookup

- setuptools/command/easy_install.py
This reverts commit 857949575022946cc60c7cd1d0d088246d3f7540.
As we can see on https://github.com/pypa/setuptools/issues/709,
this breaks many things (easy_install C extensions, all py3.5 tests,
run with LANG=C).
So instead of fixing in a hurry all new bugs due to this, I propose to
revert this commit until all downsides of this change have been
investigated.
Related bug: https://github.com/pypa/setuptools/issues/709
Related bug: https://github.com/pypa/setuptools/issues/710
Related bug: https://github.com/pypa/setuptools/issues/712
> Revert "Ensure that tmpdir is unicode. Fixes #704."

- setuptools/command/bdist_egg.py
- setuptools/package_index.py
Hi. While i was working around setuptools, here is very small clean up about code quality.
In case you take care of it.
Regards
> Fix logging using arguments instead of formatter

- setuptools/extension.py
In 3c047624, we remove the loop, but we miss to convert the tuple
to a string. Because the exception is just ignored, we don't see
that __import__ won't works
> Fix _have_cython

- setuptools/msvc.py
- setuptools/tests/test_msvc.py
#707
Fix Python 2 compatibility, and improve registry lookup (Key may not always be in 64bit registry node).
> #707 MSVC patch and Python 2

- setuptools/msvc.py
rather than before (#715), which should avoid double-quotes if the unpatched function does its own quoting.
I *believe* this closes #722
> quote library_dir_option after calling unpatched version

- setuptools/msvc.py
Revert patch on `distutils._msvccompiler.MSVCCompiler.library_dir_option`.
See comments on #694.
> revert `library_dir_option` patch.

- CHANGES.rst
- LICENSE
The classifier in setup.py should be enough for most auditors, but some
have automated tooling that checks for LICENSE files and reads those.
This helps all auditors (downstream redistributors and users) who can
not just rely on the classifier.
Related to #612
> Add LICENSE file for expectant auditors

- tox.ini
Pythons 3.1, 3.2 are no longer supported, but Python 3.5, Pypy, and
Pypy3 are.
> Update tox.ini envlist to match supported Pythons

- MANIFEST.in
Adds the license file to `MANIFEST.in` to ensure it will be packaged in `sdist`s and similar packagings of `setuptools`.
> Bundle the license

- CHANGES.rst
- setuptools/msvc.py
- Fix compatibility between `numpy.distutils` and `distutils._msvccompiler`. See #728 : Setuptools 24 `msvc.py` improvement import `distutils._msvccompiler` (New Python 3.5 C compiler for MSVC >= 14), but this one is not compatible with `numpy.distutils` (because not patched with `numpy.distutils.ccompiler.gen_lib_options`) and return unquoted libpaths when linking. The problem was patched in Numpy, but need to be patched also in Setuptools for compatibility between older versions of Numpy and `distutils._msvccompiler` (and indirectly Setuptools > 24).
Also some minor changes :
- Replace some residuals `except Exception`.
- PEP8.
- Better history of the problem in Change.rst.
> numpy.distutils and distutils._msvccompiler compatibility

- setuptools/tests/test_manifest.py
I was looking in to finishing #610, but found that there were no tests for `MANIFEST.in` that I could find. As setuptools customises the FileList a little bit, and #610 customises it some more, some tests for this would be sensible.
I wrote some tests that work much like `setuptools/tests/test_sdist.py`, by creating some files and running with various MANIFEST.in files.
I also copied the FileList tests from distutils, modifying them slightly to fit with py.test and the setuptools environment.
This way, it will be easy to verify that any modifications done to setuptools retain compatibility with distutils.
> Add tests for MANIFEST.in

- CHANGES.rst
- setuptools/command/build_ext.py
- setuptools/extension.py
- setuptools/tests/test_build_ext.py
Add an Extension(is_abi3=True) property that can be used to set its filename to something that will be loadable by more than one version of Python 3. An '.abi3.so' extension on Linux, just .pyd on Windows. Tested on Linux so far.
It will still be necessary to `-DPy_LIMITED_API=0x03030000` somewhere for the extension to truly be abi3.
> use abi3 extension if Extension().is_abi3

- setuptools/extension.py
As a side effect, py_limited_api may now only be passed as keyword
argument. I think it is early enough for this feature to change this
and enforce the flag to be passed as a keyword...
> Make Extension accept positional arguments again (fixes #752).

- .travis.yml
- setup.py
- tox.ini
The 3.x series is currently broken. Until py.test works again, 3.x should not be used by anything.
> Install py.test>=2.8,<3

- .travis.yml
- setup.py
- tox.ini
The bug that lead to pin it (pytest-dev/pytest#1888) was fixed in 3.0.2
> Use pytest>=3.0.2

- setuptools/msvc.py
Feeback by @rgommers (https://github.com/pypa/setuptools/pull/739/files/8d1eecaef52a1baf2b9fc6c772880d8c537b562f#r77445452), numpy version can look like "1.11.1rc1+fa248ad" in dev branches.
`StrictVersion` fail to parse this kind of string. One solution is to use `LooseVersion`.
```
In [6]: distutils.version.LooseVersion("1.11.1rc1+fa248ad") < distutils.version.LooseVersion('1.11.2')
Out[6]: True
In [7]: distutils.version.LooseVersion("1.11.3rc1+fa248ad") < distutils.version.LooseVersion('1.11.2')
Out[7]: False
```
> Use LooseVersion instread of StrictVersion

- setuptools/msvc.py
- Also apply the patch for numpy 1.11.2 pre release
> Use LegacyVersion instead of LooseVersion

- setuptools/command/easy_install.py
- setuptools/package_index.py
easy_install has code to handle parsing a requirement, catching the
ValueError and then raising a DistUtilsError. This code was entirely
duplicated in package_index, so I've slightly refactored to remove
the duplication.
> Don't duplicate error case in package_index

- pytest.ini
In Cloud9 a .c9 directory is created. Other IDEs like to add .directories as well.
This PR has pytest ignoring all `.*` instead of just `.tox`
> pytest: ignore all .* directories

- CHANGES.rst
- setuptools/__init__.py
Previously, PackageFinder.find would search the whole directory tree looking for packages, then remove excluded packages from this list. This made building a package very slow under some circumstances where the file tree was large.
In my case, I have a Python project that includes JavaScript and CSS assets. These assets are compiled by a node.js build chain. Every time the Python package is built, `setuptools` searches the whole (rather large) `node_modules` tree for python packages, before rejecting the whole tree because `node_modules/__init__.py` does not exist. As the build process is happening in a Vagrant virtual machine, and VirtualBox shared directories are notoriously slow, this caused the build process for the Python package to take 30+ seconds just to find the packages!
This …
> Do not search excluded directories for packages

- CHANGES.rst
- setuptools/tests/test_find_packages.py
Also add a test for the new behaviour.
> Note find_packages backwards incompatible change

- setuptools/__init__.py
- setuptools/tests/test_find_packages.py
`find_packages(exclude=['pkg'])` should still find and include the `pkg.subpkg` package.
Fixes #808
> Find nested packages with excluded parent

- docs/setuptools.txt
I think it makes sense to offer PEP8 compliant code samples in the docs.
> Follow PEP8 for keyword arguments syntax in setup

- pkg_resources/__init__.py
- pkg_resources/tests/test_resources.py
This is variation of #578 with a more modest goal.
> fix for extra names containing '-'

- setuptools/ssl_support.py
The PR adds SUSE-specific CA bundle location to the list of searched locations.
It also replaces the reliance on certifi's bundle filename with a call to `certifi.where()` (fixing #760)
> improve certificate handling in SUSE Linux

- setuptools/command/egg_info.py
- setuptools/glob.py
- setuptools/tests/test_manifest.py
When building a MANIFEST from a MANIFEST.in, setuptools previously
scanned the whole directory tree in to a list, and then picked matching
files based on MANIFEST.in commands from this list.
Now, files are found using the `glob` library from Python 3.5. This only
explores directories that need to be scanned, resulting in a large speed
improvement for projects with large file trees. A modified `glob`
module has been included. It has been changed to support back to
Python 2.6, and to include `.hidden` files in its matches. The previous
functionality included `.hidden` files in its glob matches. It is
unclear if this behaviour is desired and required, or accidental and not
required, but for strict backwards-compatibility, this behaviour is
kept.
Each command in the MANIFEST.in is now …
> Do not scan whole file tree when making MANIFEST

- pkg_resources/__init__.py
Please consider the following pull request, which addresses real-world issues (and took a while to debug).
1. "Skip empty egg directories, which may be leftover from previous installation" [1b228fa](https://github.com/pypa/setuptools/commit/1b228fa0e3f07c73de0053985565293b795e6e96)
This patch will ignore empty egg directories, which I think is intended.
Some background: When using setup.py install \-\-record option, only the FILES are listed, not the directories. It is common practice, especially from third-party distributions of RPMS to use this "record" option to generate a file list. This creates the side-effect that when the package is upgraded, the old .egg-info directory is left around, and empty. 
Thus, when something like pkg_resources.get_distribution('packageName') is called, it …
> Fix issues with distribution location from eggs

- setuptools/tests/test_manifest.py
Different OS's and file systems return lists of files in different  orders, not always creation order. This caused intermittent test failures.
The file list is now sorted prior to being checked to ensure a consistent order across all systems.
Fixes #816
> Sort manifest file list in tests

- CHANGES.rst
- setuptools/command/install_egg_info.py
- setuptools/namespaces.py
This series of commits extracts the namespace handling functionality for re-use in the `develop` command. Ref #789.
> Add a namespace module.

- conftest.py
- pytest.ini
- tests/test_pypi.py
Following the discussion in #833, I've created a test to verify that we are not breaking the install of the top packages from Pypi.
This test is added at the root test directory as it relies on virtualenv to isolate each package installation. It is disabled by default as it may take a certain amount of time to complete. It is recommended to run it for large scale modification or before each release.
To run on the top 200: `$ python -m pytest tests/test_pypi.py`
To run an arbitrary list of packages: `$ python -m pytest tests/test_pypi.py  --package_name=simplejson --package_name=rcssmin`
> Add test to verify the install of Pypi top packages

- setuptools/command/build_ext.py
In setuptools 27.0+ extension building fails on Python 3.3.0 because the extension suffix is obtained using `SO` and not `EXT_SUFFIX` (which is used in 3.3.1 and above). See: https://hg.python.org/cpython/file/v3.3.0/Lib/distutils/command/build_ext.py#l673
This patch tries `EXT_SUFFIX` and falls back to `SO` if `EXT_SUFFIX` is falsey.
> Support Python 3.3.0 for extension suffix

- ez_setup.py
- test_ez_setup.py
Fixes https://github.com/pypa/setuptools/issues/563.
Is not clear in ez_setup.py that it always uses a setuptools archive if
already downloaded: although useful (and even used as a feature in
buildout-bootstrap.py), it's hard for beginners that may have a
corrupted ez_setup.py.
So we just improve the error message, even showing the full path of the
probably "corrupted" zip.
> Meaningful message if corrupted setuptools.

- setuptools/command/egg_info.py
- setuptools/tests/test_egg_info.py
Replaces #826
Fixes #825
In order to make a test without adding mocks or other monkeys patches, I extracted the check for suppression in a static method.
> Also suppress warning for a single file missing

- setuptools/command/sdist.py
- setuptools/tests/test_sdist.py
Reopening a pull request similar to PR https://github.com/pypa/setuptools/pull/830. I've included unit test for that specific feature.
The only noticeable package that will fail with this patch is [django_compressor](https://github.com/django-compressor/django-compressor) because of dependencies on [rcssmin](https://github.com/ndparker/rcssmin) and [rjsmin](https://github.com/ndparker/rjsmin). The main author has been contacted and is aware of the [issue](https://github.com/ndparker/rcssmin/issues/6). It is best to organise a meaningful timeline with him to fix his issues before merging this PR.
> Remove _add_defaults_data_files override and add unittest

- setuptools/package_index.py
There are already so many exceptions catched, like socket errors (e.g. failure in name resolution) or HTTP errors. Depending on when a timeout occurs, it is either catched (URLError during the SSL handshake) or not (socket.error while getting a HTTP response).
When used by buildout, this fixes random failures when running in newest mode (which is the default case), or when the requested version is available in the download-cache.
> package_index: fix bug not catching some network timeouts

- setuptools/command/egg_info.py
- setuptools/tests/test_manifest.py
After #764, `global-exclude .pyc` no longer excluded `.pyc` files. This fixes that regression, and adds a test for this behaviour.
Fixes #849.
> Fix #849 global-exclude globbing

- docs/pkg_resources.txt
Entrypoint.load() is deprecated and it's recommend to use `require` and
`resolve` separately.
> Make Entrypoint methods docs up to date.

- docs/setuptools.txt
- setuptools/config.py
- setuptools/dist.py
- setuptools/tests/test_config.py
Hi,
It is useful to be able to have metadata and other options declared in configuration files (e.g. `setup.cfg`). That not only allows some automation, but also reduces bolerplate code in some cases.
See also #394. 
This chage allows us to have something like this in our config files:
```
[metadata]
name = some_name
version = attr: some_package.VERSION
description = Some description
long_description = file: README
keywords = one, two
license = BSD 3-Clause License
[metadata.classifiers]
Framework :: Django
Programming Language :: Python :: 3.5
[options]
zip_safe = False
include_package_data = True
packages = find:
scripts = 
bin/one.py
bin/two.py
[options.package_data]
* = *.txt, *.rst
hello = *.msg
[options.extras_require]
pdf = ReportLab>=1.2; RXP
rest = docutils>=0.3; pack ==1.1, …
```
> Metadata and options are now could be set in configuration files

- README.rst
- docs/_templates/indexsidebar.html
- docs/index.txt
Visitors to https://setuptools.readthedocs.io/en/latest/ are currently confronted by a ten-page list of old version numbers before they reach the ToC entry they are probably most interested in:“Building and Distributing Packages with Setuptools”.
When attempting to write this PR, I noticed that the sidebar directs contributors to Bitbucket.
> docs: reorder ToC; update stray Bitbucket links

- CHANGES.rst
- setuptools/command/egg_info.py
- setuptools/tests/test_manifest.py
Reverts #853, which restored old behaviour of implicit wildcard matching in MANIFEST.in patterns. This PR will require package authors to include explicit wildcards in their MANIFEST.in patterns: `global-exclude .foo` will need to be changed to `global-exclude *.foo`, and `recursive-include docs .rst` will need to be changed to `recursive-include docs *.rst`.
See #853, #849, #764, #886.
> Revert #853 implicit wildcards in MANIFEST.in

- setuptools/command/test.py
When test fails, it should not continue to run other commands.
Fixes #891
> Exit on test failure

- README.rst
The URL was incorrect, so it appeared as a broken image when rendered.
> Fix image URL for readthedocs link

- docs/setuptools.txt
This explains gives a basic explanation of how to use environment markers in extras_require (addressing #909).
The changelog for [20.5](https://setuptools.readthedocs.io/en/latest/history.html#id163) seems to indicate that environment markers should be supported in `install_requires`, but I was not able to get that to work. Specifically, the example from [PEP 496](https://www.python.org/dev/peps/pep-0496/#examples) causes an error.
> 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "': sys.pl'"
However, making that work properly would be out of scope for this ticket and require knowledge of the code base, so it is not mentioned in the documentation.
> Document use of environment markers in extras_require

- setuptools/ssl_support.py
Current implementation will not fall back to certifi if `get_win_certfile` fails (e.g. wincertstore is not installed).
> Fix certifi fallback is not used on Windows.

- pkg_resources/__init__.py
When resolving requirements, we now pass the list of extras we're using along to Marker.evaluate, since we want to include the extra's requirements in our list of required packages.
@jaraco, @dstufft: This should fix the issue I was having in #882. I'm not sure what you want for tests though, or if you think I should make further changes. I don't 100% understand the `_ReqExtras` class (specifically the part where things get added to it via the `dict` interface).
> Fix usage of extras when installing via Wheels; resolves #882

- setuptools/command/__init__.py
- setuptools/command/build_clib.py
- setuptools/dep_util.py
- setuptools/tests/test_build_clib.py
- setuptools/tests/test_dep_util.py
`build_clib` is sorely missing one thing in distutils - checking outdated dependencies when compiling. This makes it so that, when building a static c library, **all** objects are always **all** compiled.
The function to create the static library itself *does* implement something of this sort, but since all objects have been recompiled it has no practical effect (everything still runs **every** time).
This is a small patch designed to fix that, with a couple of qol improvements along the way. Two new keys were added to the `build_info` dictionary:
-  obj_deps - Allows specifying extra dependencies for each source so they can be recognized as being newer than the object being compiled. Example:
```
setup(
...
libraries=[(
'examplelib', 
{'sources': 'example.c', 
'obj_deps': {'': …
```
> Add timestamp-based dependency system to build_clib

- bootstrap.py
The --skip-dep-install flag skips installation of setuptools dependencies
using pip, delegating this responsibility to other tools.  This can be used to
install setuptools without the need for pip.
closes #950
> Add --skip-dep-install to boostrap.py script

- docs/conf.py
- docs/pkg_resources.txt
- docs/setuptools.txt
There is another suggestion for how to solve this at #956.
Here I'm using the [Sphinx autosectionlabel extension](http://www.sphinx-doc.org/en/stable/ext/autosectionlabel.html) as suggested in [this answer on Stack Overflow](http://stackoverflow.com/a/40225340/2748899).
I like this approach better than the one in #956, but it does lead to some warnings during doc build about duplicate headings, because every section heading has to be unique if you want to link to it. What would be best is if there was a version of ``sphinx.ext.autosectionlabel`` that concatenates the document and section heading to form a unique heading, but that doesn't seem to exist... Any other ideas?
>  Fix hard link to URLs that should have been internal (method 2: via autosectionlabel Sphinx extension)

- ez_setup.py
This can save some time for people that still use ez_setup.py but don't follow setuptools development or mailing lists.
> Refs for self upgrade/installation deprecation

- pkg_resources/__init__.py
I had a problem when ``pkg_resources.get_distribution()`` didn't work inside executable zip, and I've found that it doesn't work for packages inside zip archives mentioned in ``sys.path``. So this pull request adds support for such cases.
> support dist-info distributions inside zip files

- CHANGES.rst
- setuptools/package_index.py
- setuptools/tests/test_packageindex.py
As per https://www.python.org/dev/peps/pep-0440/#local-version-identifiers:
```
Local version identifiers MUST comply with the following scheme:
<public version identifier>[+<local version label>]
```
But EGG_FRAGMENT's character set does not contain the plus sign, which seems to be a defect.
> A local version label starts with a '+' sign

- setuptools/command/easy_install.py
Apparently, in (at least) python 3.5.2, the function that is called on Windows to remove files is os.unlink and not os.remove. This results in permission errors when trying to clean up after easy_install has been used to install a package from a Git repository.
> Fix for auto_chmod behavior

- CHANGES.rst
- docs/setuptools.txt
- setuptools/config.py
- setuptools/dist.py
- setuptools/tests/test_config.py
Changes:
- copy `self.metadata.python_requires = self.python_requires` patch to `Distribution.parse_config_files`
- add `'py_modules': parse_list` to `ConfigOptionsHandler.parsers` 
- add changes to docs and tests
- fix error message in `dist.check_specifier`
Concerning the last point: `packaging.specifiers.SpecifierSet.__init__` expects a `str` and no `list`. The fixed error is actually not thrown if a `list` is provided, since it fails on trying to call `split(",")` and thus will not throw a `packaging.specifiers.InvalidSpecifier` exception. If this case should be handled properly, it could be done here or rather in `packaging`.
> Fixes #999: support python_requires and py_modules in configuration files

- setuptools/command/egg_info.py
The `egg_info` command reads an existing `.egg-info/SOURCES.txt` before writing the new one. Therefore state is preserved, and files once added to `SOURCES.txt` (e.g. by an include line in `MANIFEST.in`) will remain forever in `SOURCES.txt` even if there is no more reason for inclusion.
The problem described in #436  is due to the fact that `.egg-info/SOURCES.txt` is used for building the list of files in a source distribution (`sdist` command).
This PR is surgical, in the sense that solves the issue by removing 2 lines of code. However after this modification the `setuptools.command.sdist.sdist.read_manifest` method is not called anymore within `setuptools` and its removal could be considered, along with the relevant unit tests.
> addresses #436: Updating MANIFEST.in does not correctly update the package sdist creates

- CHANGES.rst
- setuptools/monkey.py
Jython seems to implement inspect.getmro differently, which causes
any classes with the same name as a class lower in the MRO not to
be returned.
This patch offloads the MRO lookup to a separate function, which
implements different logic for Jython only.
Ref #1024
> Use a different method to lookup base classes on Jython

- .travis.yml
- pytest.ini
- setuptools/tests/__init__.py
- setuptools/tests/test_easy_install.py
- tox.ini
* move pytest report arguments to `pytest.ini`, so running tox with arguments does not loose those
* add xpassed tests to the pytest report
* fix `fail_on_ascii` fixture: correct detection
* mark `test_unicode_filename_in_sdist` with `fail_on_ascii`
* fix Travis ASCII builds: as evidenced by the log, all tests marked with `fail_on_ascii` were not xfailed
~~Note: first commit is a fix for the same issue as #1063, so I'll rebase once this is merged.~~
> Tests releated fixes and tweaks

- setuptools/dist.py
- setuptools/tests/test_egg_info.py
While the [documentation](https://github.com/pypa/setuptools/blob/master/docs/setuptools.txt#L767) now points to using environment markers with `install_requires` for declaring platform dependencies, this result in invalid wheels because those are stripped from the final requirements in the embedded metadata.
E.g, using something like this:
```python
from setuptools import setup
setup(
name='foo',
install_requires='barbazquux; "foobar" in sys_platform',
)
```
result in `foo.egg-info/requires.txt` containing:
```
barbazquux; "foobar" in sys_platform
```
instead of:
```python
import sys
from setuptools import setup
setup(
name='foo',
extras_require={':"foobar" in sys_platform': 'barbazquux'},
)
```
which yields:
```
[:"foobar" in sys_platform]
barbazquux
```
This PR automatically move …
> Fix environment markers handling

- tests/requirements.txt
Python 2.6 support has been official dropped from flake8 for some time, and broken since 3.4.0.
> tests: disable pytest-flake8 on Python 2.6

- .travis.yml
Update to the [future defaults](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming):
* `dist: trusty`
* `sudo: required`
Note:
* include #1090 
* the version of PyPy now being tested is `pypy-5.4`: `PyPy 5.4.0 [Python 2.7.10]` (previously: `PyPy 2.5.0 [Python 2.7.8]`)
* `pypy3-5.4` is also available, should it be added to the matrix?
> update Travis builds

- .travis.yml
Skip the clean-up phase, so the results of `python bootstrap.py` are not undone.
> travis: fix deployment

- .gitignore
- CHANGES.rst
- pkg_resources/__init__.py
- pkg_resources/tests/test_find_distributions.py
- setup.py
- tests/requirements.txt
Do not assume a directory named in `.egg` is an egg, unless it has an
actual egg metadata directory.
Closes #462
Should also close pypa/pip#3028
> Better detect unpacked eggs

- setuptools/monkey.py
- setuptools/msvc.py
The exception is caused by the VCForPython27 monkey patch. It's not needed on mingw built Python. Disable it and avoid the import by using the same function that `distutils` uses to decide it's running on a mingw built Python.
Hopefully this doesn't break in some random old Python version. 😩
Fixes #1118
> Fix exception on mingw built Python 2

- CHANGES.rst
- docs/setuptools.txt
- setuptools/config.py
- setuptools/tests/test_config.py
This basically allows one to include several files into `long_description` via `setup.cfg` in a declarative way.
Sometimes one wants to have their README and CHANGELOG stored as separate files, so that GitHub would only render README contents on a main repo page. But it is nice to [list changes](https://github.com/aio-libs/aiohttp/blob/v2.2.5/setup.py#L90) on PYPI as well.
For such cases I suggest parsing `long_description` config value as a list with possibility to inject static files contents via `file:` directive.
This would've been possible with [RST `.. include::`](https://github.com/aio-libs/aiohttp/blob/master/docs/changes.rst#L3-L5), but setuptools doesn't process RST internally. So it's not an option.
In general, suggested change doesn't break compatibility.
/cc: @jaraco it would …
> Allow combining several files in metadata.long_description

- CHANGES.rst
- setuptools/command/bdist_egg.py
to generate reproducible zip files
that do not differ depending on (random) filesystem order
See https://reproducible-builds.org/ for why this matters.
> Sort file lists

- CHANGES.rst
- docs/setuptools.txt
- setup.py
- setuptools/command/egg_info.py
- setuptools/dist.py
- setuptools/tests/test_egg_info.py
This is a re-opening of #708 which was closed.
Since then, https://github.com/pypa/python-packaging-user-guide/pull/258 has been merged and is now documented here: https://packaging.python.org/specifications/#description-content-type
I've rebased it and amended the commit messages to reflect that https://github.com/pypa/python-packaging-user-guide/pull/258 was accepted.
> Add new long_description_content_type kwarg

- CHANGES.rst
- setuptools/dist.py
- setuptools/tests/test_dist.py
When run in a fresh virtualenv, the following command:
```bash
easy_install pytest-runner pytest
```
will return with no error but only install `pytest-runner`.
This is because after parsing the PyPi index page for `pytest-runner`, easy_install will build a list of inferred distribution (in [interpret_distro_name](https://github.com/pypa/setuptools/blob/master/setuptools/package_index.py#L141)) that looks like this:
Project name | Version 
--- | ---
pytest | runner-2.2.1
pytest-runner | 2.2.1
pytest-runner-2.2.1 |
[...]
pytest | runner-2.11.1
pytest-runner | 2.11.1
pytest-runner-2.11.1 |
Which works fine for finding the best matching distribution for `pytest-runner`, but gets also reused for the next requirement: `pytest`....
Switching the requirements around works fine: `easy_install …
> workaround easy_install bug

- CHANGES.rst
- pkg_resources/__init__.py
- pkg_resources/tests/test_working_set.py
Correctly replace conflicting distributions in sub-requirements if possible (instead of only for top-level requirements passed as arguments).
Fix #1124.
> pkg_resources: improve `WorkingSet.resolve(replace_conflicting=True)`

- CHANGES.rst
- setuptools/command/sdist.py
Markdown is a widely used format to write README files and documentation. 
This patch aims to simplify adding new formats and at the same time adds that one to the list.
> Improve README file list handling and add Markdown to the current list

- CHANGES.rst
- pkg_resources/__init__.py
The current code in find_on_path is doing a lot of stat() calls which are
actually useless and prone to race conditions.
As described in Python documentation
(https://docs.python.org/3/library/os.html#os.access), os.access must not be
used before opening a file. Same goes for a directory.
This patch removes those checks by handling exceptions correctly when using
os.listdir() instead, which improves pkg_resources import time.
> pkg_resources: do not call stat() and access()

- setuptools/command/sdist.py
Fix `python2.6 bootstrap.py` failing on Travis.
> Fix Python 2.6 support

- README.rst
Currently, it is not obvious where to find CI or which versions are supported. Or what is the current version of released package.
It is useful to have visual representation of this information, accessible with a single click on shield at the main page of the repo (as well as PYPI):
* PYPI published version
* Travis CI
* AppVeyor CI
* List of currently supported Python versions
> Add badges to the top of README

- .travis.yml
Skip the deploy stage if no tag is present.
> travis: make deploy stage conditional

- docs/setuptools.txt
This pull request fixes various grammatical errors in the "Configuring setup() using setup.cfg files" section.
> Proofreading for the setup.cfg documentation

- pkg_resources/__init__.py
- pkg_resources/tests/test_pkg_resources.py
- setuptools/tests/test_egg_info.py
When tests are invoked with the Python flag -Wall, warnings appear in the form of:
```
ResourceWarning: unclosed file ...
```
Close all files and resources deterministically to avoid such warnings. Most often, easiest to do using a context manager.
> Clean up resource warnings during tests

- setuptools/tests/test_develop.py
- setuptools/tests/test_namespaces.py
This allows to run the testsuite on systems where `/usr/bin/pip` is a specific Python version, but the tests are run on a different one.
For example in Fedora RPM, when the Python 3 tests are invoked, they should use Python 3 pip, not Python 2 `/usr/bin/pip`.
Unlike other approaches, like using `pip2`/`pip3` which is currently done in Fedora RPM (downstream patch), this way it Works Everywhere™ and the downstream patch can be dropped.
See https://src.fedoraproject.org/rpms/python-setuptools/blob/54eaa03a4dc97f93a5e4c92c55e580a4ab55a058/f/0001-Run-test-on-a-version-specific-pip.patch
cc @torsava (author of that Fedora downstream patch)
> Tests: Run `python -m pip` instead of plain `pip`

- setuptools/command/__init__.py
- setuptools/command/dist_info.py
- setuptools/dist.py
- setuptools/pep517.py
- setuptools/tests/test_pep517.py
- setuptools/tests/test_pep_517.py
This PR combines the dist_info PR and the [original PR](/pypa/setuptools/pull/1039).
Summary:
- the `setuptools.pep517` module is added, which allows querying for `setup_requires`, among other things (see the PEP for full details)
- the functions in the added module are the ONLY public API added here. The `SetupRequirementsError` is not intended to be used except within setuptools.
> Implement PEP 517 Build backend

- CHANGES.rst
- setuptools/__init__.py
- setuptools/dist.py
- setuptools/tests/test_dist.py
- setuptools/tests/test_easy_install.py
Fix #1054.
The patch is not straightforward because: parsing `setup.cfg` is not part of `Distribution.__init__` (it's done later explicitly by `distutils.setup`), but installing `setup_requires`' requirements is (and this must be kept early, so all options passed to `setup` are correctly interpreted)... Additionally, instantiating a `Distribution` object with no arguments should not raise an error if there's an invalid `setup.cfg` in the current directory.
> support `setup_requires` in setup.cfg

- setuptools/build_meta.py
- setuptools/command/dist_info.py
- setuptools/tests/test_build_meta.py
Attached are some minor cleanups and fixes to the build_meta module that I added in #1143.
> Build meta: fixes and cleanups

- setuptools/ssl_support.py
I ran into a ssl certificate verification problem using buildout and a private package index using SNI.
The usual workaround to make sure that the ssl cert of the private registry server defaults to the package index hostname was not possible this time, so I thought I'll fix it at the core and use SNI when connecting to a ssl server.
Happy to ammend this pull request in any way, but I do believe that something like this would be good to have as it also uses good practice ssl settings maintained in python core ssl.py module, and sticks to officially document methods in ssl module.
> use ssl.create_default_context and SNI if available

- distutils/__init__.py
- pytest.ini
- setuptools/__init__.py
On Python 3.6 and above, setuptools replaces the builtin distutils with it's own version. Python 3.5 and below is unaffected. The idea is to start with Python 3.6 and then roll in future versions as they come, until setuptools always uses it's own copy of distutils. Eventually, python can remove distutils and add an ensuresetuptools module for building.
/cc @jaraco @zooba
> [distutils] fix test failures

- pkg_resources/__init__.py
This PR improves the message of the one place in `pkg_resources` that raises `ResolutionError`.
For the motivation for this change, see issue #1208.
> Fixes #1208: Improved exception message of pkg_resources.ResolutionError

- CHANGES.rst
- setuptools/tests/test_wheel.py
- setuptools/wheel.py
I'd like some feedback on this, not use if there's a better approach...
Fix #1214.
> fix namespace packages handling of wheels

- CHANGES.rst
- pkg_resources/__init__.py
- pkg_resources/tests/test_pkg_resources.py
- setup.cfg
- setup.py
Given a ZipProvider, if the underlying ZipImporter prefix is empty,
then resource_listdir('') and resource_listdir('subdir/') fail, while
resource_listdir('/') and resource_listdir('subdir') succeed.
On the other hand, if the underlying ZipImport prefix is not empty,
then resource_listdir('/') fails but resource_listdir('') succeeds.
With this change, the cases listed succeed with or without trailing
slashes.
Fixes #1188
> Fix trailing slash handling in pkg_resources.ZipProvider

- setuptools/command/egg_info.py
- setuptools/dist.py
- setuptools/tests/test_config.py
[This was already claimed in the docs.](https://github.com/pypa/setuptools/blob/d45be2cc4f7a1e4ddc70b363baaa613c6b068b98/docs/setuptools.txt#L2417) That this did not work before can be seen by cherry picking the changed test in this PR without the other changes: it will fail. Fixes issue #1206
> Add setup.cfg support for long_description_content_type

- CHANGES.rst
- setuptools/command/easy_install.py
This is an old warning (from 8 years ago) that isn't useful anymore.
If one disables generation of .pyc files, one constantly gets these warnings, polluting the output.
> Removed warning when PYTHONDONTWRITEBYTECODE is enabled

- setuptools/command/bdist_egg.py
- setuptools/tests/test_sandbox.py
- update scanning code to handle pyc header change
- handle change to `Exception.__repr__` output
> fix Python 3.7 support

- docs/setuptools.txt
find_packages doesnt find PEP420 packages but
the documentation suggests that it does.
see: pypa/setuptools#97
> Reflect find_packages behavior in doc

- docs/pkg_resources.txt
- docs/setuptools.txt
The `,` is the equivalent of an "and".
Also, the `pkg_resources` documents and behave like this too:
http://setuptools.readthedocs.io/en/latest/pkg_resources.html#requirement-methods-and-attributes
> [...] Adjacent redundant conditions are effectively consolidated (e.g. ">1, >2" produces the same results as ">2", and "<2,<3" produces the same results as``”<2”).
```
>>> pkg_resources.Requirement('requests>1,>2').specifier.contains('1.2.3')
False
>>> pkg_resources.Requirement('requests>1,>2').specifier.contains('2.3.4')
True
```
Also fixed a small spacing error messing up with formatting in the mentioned `pkg_resources` section.
> Fix documentation inconsistency on version specifier

- docs/setuptools.txt
Clarify the documentation around `package_data` so that it is clearer and highlight some of the cases that can cause issues when using it.
Fix #1198
> Updated package_data documentation

- CHANGES.rst
- setuptools/dist.py
- setuptools/tests/test_config.py
- setuptools/tests/test_egg_info.py
This PR makes the necessary updates for Metadata 2.1 ([PEP 566](https://www.python.org/dev/peps/pep-0566/)):
* Handles the new `Description-Content-Type` and `Provides-Extra` fields
* The former was already added in #1075, I made a slight tweak from #1207 to only set this field if it is present
* Correctly sets the `Version` field to `2.1` if either of the new fields are present
> Updates for Metadata 2.1 (PEP 566)

- CHANGES.rst
- setuptools/dist.py
- setuptools/tests/test_dist.py
Fixes #1288.
I have not really gone through this with a fine-toothed comb to see if it meets all of the specifications of PEP 345, but this is at least a step in the right direction.
> Add support for maintainer in PKG-INFO

- setuptools/dist.py
- setuptools/tests/test_dist.py
Fixes #1297.
I also don't think the version comparisons were working correctly in the original patch in certain situations, so that was updated.
> Fix unicode maintainer

- setuptools/dist.py
- setuptools/monkey.py
Fixes #1289. Since setuptools no longer supports Python 3.2, this patch is unnecessary.
I am aware that this may be an unnecessary risk considering this patch isn't actively hurting anything, but it's probably worth some cleanup.
I tried to dig around in the git history to figure out which, if any, tests test that this works correctly, but I couldn't find anything. @jaraco Do you know if there are any? If not, should I add them?
> Stop patching write_pkg_info

- setuptools/tests/test_egg_info.py
This ensures we don't unknowingly change the behavior of this again.
Signed-off-by: Stephen Finucane <stephen@that.guru>
Fixes #1307
> tests: Add regression test for #1081

- CHANGES.rst
- docs/_templates/indexsidebar.html
- docs/easy_install.txt
- docs/python3.txt
- docs/setuptools.txt
- setuptools/command/easy_install.py
- setuptools/package_index.py
- setuptools/tests/test_packageindex.py
For details on the new PyPI, see the blog post:
https://pythoninsider.blogspot.ca/2018/04/new-pypi-launched-legacy-pypi-shutting.html
> Update all pypi.python.org URLs to pypi.org

- .travis.yml
- tests/requirements.txt
pytest-flake8 1.0.1 has a hard dependency on pytest>=3.5 [1], which
does not support python3.3 [2].  Pin it until python3.3 is removed
[3].
[1] https://github.com/tholo/pytest-flake8/commit/25bbd3b42d3aa0962fb736202115dae9e5d2cd7c
[2] https://docs.pytest.org/en/latest/changelog.html#pytest-3-3-0-2017-11-23
[3] https://github.com/pypa/setuptools/pull/1342
> Pin pytest-flake8 to 1.0.0

- .gitignore
- docs/developer-guide.txt
- tox.ini
Support easy local builds of docs via `tox -e docs`, and update the developer documentation accordingly.
> Add tox environment for docs

- docs/developer-guide.txt
As discussed at the PycCn sprints 2018, day 1. These are small changes to the developer guide section of the docs to make the directions easier to follow for new developers.
Two changes: 
* changed `git checkout` to `git clone` in instructions for initially getting the codebase 
* Added instruction to run `python bootstrap.py` before invoking `tox` for the first time.
I did not update the CHANGES.txt as I was unsure on the protocol there and these are essentially typo fixes. Please let me know if I need to change that.
> Small fixes to Docs:Developer Guide

- changelog.d/1354.misc.rst
- docs/developer-guide.txt
- pyproject.toml
- towncrier_template.rst
Per #1341, this sets up `towncrier` using this:
```
towncrier --version
```
The current configuration more or less recreates the old changelog format. We can tweak from here if we want to make improvements that take advantage of what `towncrier` can give us.
We now just need documentation on how to use this.
> Add configuration for towncrier

- changelog.d/1357.doc.rst
- docs/conf.py
- docs/pkg_resources.txt
- docs/setuptools.txt
- tox.ini
Fixed all the current warnings from documentation builds, and configured tox to fail doc builds if any new warnings are introduced.  The `autosectionlabel` extension had to be disabled because it caused "duplicate label" warnings in `CHANGES.rst` where the same subsections are used in a few different releases.  Only 2-3 of the cross-references seem to have been depending on it anyway, fixed here by adding explicit section labels.
There was one link that no longer seems to correspond to any section in the docs; I just removed that one, let me know if there's something it should actually point to instead.
> Fix doc build warnings

- changelog.d/1365.change.rst
- setuptools/config.py
- setuptools/tests/test_config.py
Takes the `package_dir` option into account when loading `version` from a module attribute.  This should handle cases where all modules are located under a common parent and where that particular module is in a subdirectory and/or has a different name.  It doesn't attempt to handle cases where `package_dir` contains keys like "foo.bar", but I'm not sure such entries are even valid.
This required adding a dependency on the `options` section parsing in the `metadata` section parsing, in order to get the value of `package_dir`.  This seems pretty harmless since they happen right after each other, but let me know if it poses any problems.
Closes #1333
> Fix attr: with package_dirs

- changelog.d/1369.misc.rst
- setuptools/tests/test_glibc.py
- setuptools/tests/test_pep425tags.py
When code for supporting PEP 425 compatibility tags was copied from `pip` in https://github.com/pypa/setuptools/pull/1200, the unit tests weren't copied with it.  I'm adding those to make sure we don't inadvertently break that functionality.
> Add tests for PEP 425 support

- changelog.d/1360.change.rst
- setuptools/tests/test_wheel.py
- setuptools/wheel.py
wheel files contain a directory that ends with ".dist-info", but its full name may not exactly match the name of the package as written in the wheel filename. e.g. on Windows, the wheel file name may use different letter cases. Using canonicalize_name on both the package name from the wheel filename and the directories in the zip to find a match fixes the problem.
See issue #1350
The general logic was taken from the pip code: https://github.com/pypa/pip/blob/0ae0109901f63b7f133229a9fee41332dd7366b4/src/pip/_internal/wheel.py#L270
> Use canonicalize_name to look for .dist-info in wheel files

- .travis.yml
- changelog.d/1372.misc.rst
The Python 3.3 job in Travis failed in the last build on master because the new `wheel` release won't install on it.  We planned on dropping 3.3 support soon anyway, so just stop testing it on Travis to avoid further job failures.  We'll release one more version that officially supports Python 3.3 while incorporating all the latest fixes from master, and then the next one will fully remove support for it.
> Stop testing Python 3.3 in Travis

- changelog.d/1368.misc.rst
- setuptools/tests/test_egg_info.py
This fixes the only test cases which would fail if the network is unavailable.  They were running a `setup.py` with packages listed in `install_requires` that usually aren't installed locally.  This was causing 4 parameterized variants of the test case to fail if the network was unavailable, and triggered some AppVeyor failures when network access was slow or intermittent:
* https://ci.appveyor.com/project/pypa/setuptools/build/5/job/5bpipnfs2x66j2th
* https://ci.appveyor.com/project/pypa/setuptools/build/6/job/d6v69rilgjwqjvc4
* https://ci.appveyor.com/project/pypa/setuptools/build/19/job/c1l1r8n9ntags30o
I resolved this by switching the packages listed in `install_requires` to ones which are dependencies of the test suite, and hence should always be installed by the time the test runs.
> Don't require network in tests

- changelog.d/1352.misc.rst
- changelog.d/1353.doc.rst
- changelog.d/1356.doc.rst
- changelog.d/1376.doc.rst
- docs/releases.txt
- towncrier_template.rst
* Updated the release process docs to account for towncrier
* Removed blank lines between the non-labeled categories of changes in a release
* Added `changelog.d` entries for PRs going into the next release which preceded the addition of towncrier support
Currently the changelog entry for the next release comes out like this:
```
v39.2.0
-------
* #1359: Support using "file:" to load a PEP 440-compliant package version from
a text file.
* #1360: Fixed issue with a mismatch between the name of the package and the
name of the .dist-info file in wheel files
* #1365: Take the package_dir option into account when loading the version from
a module attribute.
* #1353: Added coverage badge to README.
* #1356: Made small fixes to the developer guide documentation.
* #1357: Fixed warnings in …
```
> Update release process docs

- CHANGES.rst
- changelog.d/1364.rst
- changelog.d/1379.doc.rst
- docs/releases.txt
I made some tweaks to the release process documentation after using it to create version 39.2.0.  I also updated the 39.2.0 changelog to reflect one item which was omitted because the file was named incorrectly (which prompted one of the doc updates).
The towncrier output is slightly inconsistent in its usage of newlines between preview and release modes, and edits to the template don't seem to affect this.  I manually added one newline and removed another for the 39.2.0 release to keep the formatting consistent; the new output review step is partially to catch things like this until we find a way to get towncrier to automatically get the formatting correct.
The `--allow-dirty` option is needed for bump2version to go ahead even though the changelog updates haven't been committed yet.
> Make minor fixes to release docs

- changelog.d/1342.breaking.rst
- docs/easy_install.txt
- pkg_resources/__init__.py
- pkg_resources/extern/__init__.py
- pkg_resources/py31compat.py
- pkg_resources/tests/test_resources.py
- setup.py
- setuptools/command/bdist_egg.py
- setuptools/command/build_ext.py
- setuptools/command/easy_install.py
- setuptools/extern/__init__.py
- setuptools/monkey.py
- setuptools/pep425tags.py
- setuptools/py31compat.py
- setuptools/site-patch.py
- setuptools/tests/test_easy_install.py
- setuptools/tests/test_egg_info.py
- setuptools/tests/test_install_scripts.py
- tox.ini
As suggested in https://github.com/pypa/setuptools/issues/1339, as it's EOL and Tox no longer supports it.
Also remove redundant code and update other code.
> Drop support for EOL Python 3.3

- docs/developer-guide.txt
The project "town-crier", with a hyphen, linked originally, is a blockchain integration. I'm certain the correct one is the one without a hyphen, which is for NEWS.
> Fix Town Crier Link

- setuptools/script (dev).tmpl
Avoid resource warnings on dev scripts installed editable.
ResourceWarning: unclosed file <_io.TextIOWrapper name='whatever' mode='r' encoding='UTF-8'> 
The `with` statement is supported since Python 2.5, so I assume we are OK to use this. Can use try: finally: instead if proj maintainers prefer?
> Avoid resource warning from dev scripts installed editable

- changelog.d/1404.misc.rst
- pyproject.toml
Add `build-system.requires` key to `pyproject.toml`:
- this is necessary with pip 10.0.1, as otherwise the defaults will be to require both `setuptools` and `wheel` (and we only need the later)
- a `pyproject.toml` with no `build-system.requires` key will be invalid and rejected by a future version of pip (see https://github.com/pypa/pip/issues/5416#issuecomment-399638608)
> fix PEP 518 configuration

- CHANGES.rst
- changelog.d/1403.doc.rst
- docs/developer-guide.txt
Drop `Source Code` section, as it contains an outdated guideline with respect to documenting changes and its contents are already covered by other sections.
> docs: fix developer guide

- changelog.d/1410.change.rst
- docs/setuptools.txt
- setuptools/command/register.py
- setuptools/command/upload.py
- setuptools/tests/test_register.py
- setuptools/tests/test_upload.py
As discussed in https://github.com/pypa/setuptools/issues/1381, this PR deprecates the `upload` and `register` commands by warning the user not to use these commands.
> Deprecate upload and register commands

- changelog.d/1388.change.rst
- setuptools/msvc.py
Fix Microsoft Visual C++ Build Tools dead link.
Closes #1394
> Fix "Microsoft Visual C++ Build Tools" link

- changelog.d/1312.change.rst
- docs/setuptools.txt
- setuptools/__init__.py
- setuptools/tests/test_find_packages.py
make find_packages() find also PEP420 namespace packages when supported
> fix #97 PEP420: find_packages()

- changelog.d/1416.change.rst
- pkg_resources/py31compat.py
- setuptools/command/bdist_egg.py
- setuptools/extern/__init__.py
- setuptools/pep425tags.py
Per the reasoning in #1415, I think that we should use `six.PY{2,3}` whenever possible and outsource how to determine the major version to them.
The one concession I made to #1413 is that I changed one `sys.version_info.major` to `sys.version_info[0]` in the version logic *itself*, because that is more consistent with how `six` does it. I'm not saying that we guaranteed that we'll never use `sys.version_info.major` in the future, just that this is another equally good way to check the value that doesn't trigger the Jython bug.
Closes #1415
- Changes have tests **N/A**
> Switch over to using six.PY{2,3} when possible

- changelog.d/1418.change.rst
- pkg_resources/__init__.py
- pkg_resources/tests/test_pkg_resources.py
This PR is an approach to #1412 that adds a test to induce this race condition. The test relies on implementation details, but that is made explicit in the text of the test, I have done it this way because there isn't another great way to deterministically induce the problem.
cc: @JonKohler
Closes #1256
> Egg race condition

- tox.ini
Starting with tox 3.2.0, the commands for installing/listing dependencies changed from `pip` to `python -m pip`, which is problematic as this will leave bits of the previous (from the virtualenv creation) older version of setuptools installed in the site-packages directory because from pip's point of view, the active setuptools version is the one in the current directory (which cannot be uninstalled).
> tox: fix configuration so newer tox versions are supported

- changelog.d/1450.change.rst
- pkg_resources/_vendor/pyparsing.py
- setuptools/_vendor/pyparsing.py
Fixes the first part of #1095 and https://github.com/pypa/setuptools/pull/1450 (see https://github.com/pypa/setuptools/pull/1451 for the second part).
Upgrade vendored PyParsing from 2.1.10 to 2.2.0.
* 2.1.10 was released on Oct 7, 2016
* 2.2.0 was released on Mar 6, 2017
https://pypi.org/project/pyparsing/#history
Upgrading means these deprecation warnings are fixed:
```
/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py:147: DeprecationWarning: invalid escape sequence \d
xmlcharref = Regex('&#\d+;')
/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py:832: DeprecationWarning: invalid escape sequence \d
"""
/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py:2736: DeprecationWarning: invalid escape sequence \d
""" …
```
> Upgrade vendored PyParsing from 2.1.10 to 2.2.0

- changelog.d/1451.change.rst
- pkg_resources/_vendor/appdirs.py
- pkg_resources/_vendor/vendored.txt
- setuptools/_vendor/vendored.txt
Fixes the second part of #1095 and #1450 (see https://github.com/pypa/setuptools/pull/1450 for the first part).
Upgrade vendored appdirs from 1.4.0 to 1.4.3 to remove deprecation warnings:
```console
$ python3 --version
Python 3.7.0
$ find . -name \*.py | xargs python3 -Wall -m py_compile
./setuptools/_vendor/pyparsing.py:147: DeprecationWarning: invalid escape sequence \d
xmlcharref = Regex('&#\d+;')
./setuptools/_vendor/pyparsing.py:832: DeprecationWarning: invalid escape sequence \d
"""
./setuptools/_vendor/pyparsing.py:2736: DeprecationWarning: invalid escape sequence \d
"""
./setuptools/_vendor/pyparsing.py:2914: DeprecationWarning: invalid escape sequence \g
ret = re.sub(self.escCharReplacePattern,"\g<1>",ret)
./pkg_resources/_vendor/appdirs.py:130: DeprecationWarning: invalid …
```
> Upgrade vendored appdirs from 1.4.0 to 1.4.3

- changelog.d/1389.change.rst
- setuptools/command/easy_install.py
- setuptools/tests/test_easy_install.py
Makes the `_to_ascii()` function able to handle script's contents in unicode format.
Closes #761
> Support for scripts with unicode content

- CHANGES.rst
- changelog.d/1312.change.rst
- changelog.d/1388.change.rst
- changelog.d/1389.change.rst
- changelog.d/1410.change.rst
- changelog.d/1416.change.rst
- changelog.d/1418.change.rst
- changelog.d/1420.change.rst
- changelog.d/1441.misc.rst
- changelog.d/1450.change.rst
- changelog.d/1451.change.rst
I think we're ready to cut a new release. I don't see any breaking changes, so I'm calling this the 40.1.0 release.
I think it might be a good idea to release an 40.1.0rc1 for a few days and then cut the final 40.1.0 release.
Thoughts @benoit-pierre @jaraco @jmbowman?
Anyone have any blockers that they wanted to make sure as in the next release?
> Prepare 40.1.0rc1

- changelog.d/1465.change.rst
- setuptools/command/egg_info.py
- setuptools/tests/test_egg_info.py
Ensure version is tagged only once. Fix #1462.
> setuptools: fix regression with `egg_info` command

- changelog.d/1466.change.rst
- setuptools/build_meta.py
- setuptools/tests/test_build_meta.py
Modifies the PEP 517 backend to handle a Unicode value for the `metadata_directory` in `prepare_metadata_for_build_wheel`. Distutils has an explicit check for a `str` value for `egg-base`, which fails on Python 2 when passed Unicode (even if the value is convertible to str), so we convert the parameter to a string using the filesystem encoding in that case.
> Fix for Unicode handling in PEP 518 backend

- changelog.d/1479.misc.rst
- setuptools/glob.py
- setuptools/tests/files.py
- setuptools/tests/test_glob.py
The type `bytes` is available on all supported Pythons. Makes the code more forward compatible with Python 3.
> Remove compatibility shim for bytes type

- changelog.d/1474.change.rst
- setuptools/build_meta.py
- setuptools/tests/test_build_meta.py
the wheel package is not required to build a source distribution @pganssle
> build_meta.get_requires_for_build_sdist does not include wheel

- changelog.d/1324.change.rst
- pkg_resources/__init__.py
According to PEP 503, a "normalized" project name has all runs of the
characters ., - and _ replaced with a single - character. [0]
Similarly, since version 8.1.2, that is the behaviour of pip as well. [1]
However, Setuptools still allows a . in the normalized name, which
is causing trouble down the line.
[0] https://www.python.org/dev/peps/pep-0503/#normalized-names
[1] https://github.com/pypa/pip/issues/3666
> Make safe_name compliant to PEP 503 and behaviour of pip > 8.1.2

- changelog.d/1402.change.rst
- pkg_resources/__init__.py
- setuptools/tests/test_namespaces.py
Improved ``__path__`` attribute handling for namespace packages, fixes a bug revealed with python3.6 when there are 2 packages in the same namespace one installed and one in current working directory.
Closes #1321
> Improved handling of  module __path__ attribute for namespace packages, fixes #1321

- changelog.d/1324.change.rst
- pkg_resources/__init__.py
> Revert "Make safe_name compliant to PEP 503 and behaviour of pip > 8.1.2"

- changelog.d/1481.change.rst
- setuptools/build_meta.py
- setuptools/tests/test_build_meta.py
This avoids a lot of current bugs (e.g. sdists are always generated in ``dist``, and at end moved out; however ``dist`` folder remains around - so if e.g. the version changes you'll get two sdists now); no need to move around just build in the requested location. Discovered this while trying to use this backend with tox's PEP-517/8.
> build_meta sdist directory delegate to --dist-dir

- .gitignore
Added .idea/ to gitignore, to cover cases where people are using a Jetbrains text editor
> Added .idea/ to gitignore, to cover cases where people are using a Jetbrains text editor

- .travis.yml
- appveyor.yml
- tox.ini
Travis:
- preemptively switch to VM-based jobs (rational: https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures)
- fix support for Python 3.7 and add support for 3.8
- ensure test requirements are installed and up-to-date
AppVeyor:
- only clone the first 50 commits (same as Travis)
- ensure test requirements are installed and up-to-date
Additionally, disable codecov's gcov processing: we don't need it and it generates a couple of error messages on AppVeyor.
> Update CI builds

- changelog.d/1517.change.rst
- setuptools/command/easy_install.py
Drop use of six.u in the code. Trivial changes, I thought you folks had more than one occurrence of six.u here.
Closes #1516
> Drop use of six.u

- changelog.d/1520.change.rst
- docs/setuptools.txt
- setuptools/config.py
- setuptools/tests/test_config.py
These commits add data_files support in setup.cfg, discussed in the issue #1189, such like the following.
```
[options.data_files]
data = data/48x48/logo.png, data/scale/logo.svg
conf =
site.d/00_default.conf
host.d/00_default.conf
```
I think it may close #1189.
> Add data_files support in setup.cfg

- changelog.d/1335.change.rst
- pkg_resources/__init__.py
This works around problems that stem from getcwd(3) on Cygwin returning paths containing symlinks. I am not sure at all whether this is a good place to fix it, but that's where I got hit by the issue when doing a `python setup.py develop` (or `pip install -e .`).
> Adds call to os.path.abspath() in pkg_resources.normalize_path() on Cygwin

- changelog.d/1531.misc.rst
- setuptools/tests/test_build_meta.py
- setuptools/tests/test_manifest.py
- setuptools/tests/test_namespaces.py
- setuptools/tests/test_sdist.py
- setuptools/tests/test_test.py
- setuptools/tests/test_virtualenv.py
Mark Python 2/3-only tests as skip instead of xfailing them. Also use predefined `py2_only` and `py3_only` decorators where appropriate.
Closes #1529.
> Mark Py 2/3-only tests as skip instead of xfail

- changelog.d/1539.doc.rst
- docs/setuptools.txt
added minumum column in metadata table; added minumum version for long_description_content_type
Closes 
#1236
> Added minumum column in metadata table and version info for long_description_content_type

- .travis.yml
- MANIFEST.in
- changelog.d/1533.misc.rst
This restricts the `recursive-include setuptools/_vendor` to contain only .py and .txt files.
Closes #1414
- ~Changes have tests~
> Exclude .pyc in sdist output

- changelog.d/1537.doc.rst
- docs/setuptools.txt
Document how to use setup.cfg with `src/` layouts.
Closes #1524.
> Document using setup.cfg for src-layouts

- README.rst
The current link to [setuptools-developers](https://github.com/orgs/pypa/teams/setuptools-developers) is a private link (gives an HTTP 404 for not priviledged viewers). PyPI links to github as the homepage so both links (the whole line) can be removed.
> remove private and redundant link

- changelog.d/1545.feature.rst
- pkg_resources/__init__.py
- pkg_resources/tests/test_resources.py
- setuptools/__init__.py
- setuptools/_deprecation_warning.py
- setuptools/command/easy_install.py
- setuptools/command/egg_info.py
- setuptools/dist.py
- setuptools/tests/test_dist.py
- setuptools/tests/test_easy_install.py
- setuptools/tests/test_egg_info.py
Added custom deprecation warning classes because DeprecationWarning is not visible unless the user opts in.
Closes Issue #159
> Custom Deprecation Warning classes.

- changelog.d/1541.deprecation.rst
- setuptools/config.py
- setuptools/tests/test_config.py
Will throw a `DeprecatedWarning` whenever `requires` parameter is used. 
Closes #1374
> Deprecate requires

- changelog.d/1456.doc.rst
- docs/setuptools.txt
Refs #1456
Document that rpmbuild is required for bdist_rpm, if distutils does not find it it'll use rpm which does not have (anymore?) the -b switch used to build packages.
Closes #1456 at least for the setuptools side
> Document that rpmbuild is required for bdist_rpm

- changelog.d/1552.doc.rst
- docs/python3.txt
"the Setuptools strongly recommends" -> "the Setuptools project strongly recommends"
> Add missing word to sentence in docs

- changelog.d/1560.doc.rst
- docs/ez_setup.txt
- docs/index.txt
- docs/setuptools.txt
* update setuptools documentatoin with a quick distribution guide.
* update index to show easy_install and ez_setup to the bottom.
* move ez_setup instructions to its own file.
Closes #1555
> Update documentation for setuptools distribution

- changelog.d/1554.change.rst
- setuptools/command/egg_info.py
- setuptools/tests/test_build_meta.py
- setuptools/tests/test_egg_info.py
- setuptools/tests/test_sdist.py
While creating sdists, we want the source dist .tar.gz to contain `setup.py` because this is what pip would use to install the source distribution. `python setup.py sdist` ensured setup.py was included because distutils by default adds the [script_name](https://github.com/python/cpython/blob/master/Lib/distutils/command/sdist.py#L250) that was executing the build process. However, for someone calling `build_sdist('.')` programatically, the script name is the script callind build_sdist function and not `setup.py`.
The problem is that sdist command uses the `egg-info` command to extract file list to be tar-ziped, which did not include setup.py as default (unless it was called via 'setup.py' as the script name). This fix adds an explicit check in the `egg-info` command for setup.py.
An …
> Egg include setup py

- changelog.d/1572.misc.rst
- setuptools/tests/test_build_meta.py
- tests/requirements.txt
`setuptools.tests.test_build_meta` relies on the Python 3 feature `concurrent.futures` to run, and as a result has been silently skipped in Python 2.7. This adds the `futures` backport to the 2.7 test requirements and turns the `pytest.importorskip` invocations in test_build_meta into standard import statements.
> Add futures and backport to Python 2.7 test requirements

- changelog.d/1519.change.rst
- pkg_resources/__init__.py
- pkg_resources/tests/test_pkg_resources.py
Closes #1519.
I’m not sure how the test should be constructred. It seems silly to just test whether the function is identical to calling the three functions, but any fixed strings would be platform-dependant.
> Call os.path.normpath to normalize paths for comp

- changelog.d/1576.change.rst
- setuptools/command/upload.py
- setuptools/dist.py
- setuptools/monkey.py
- setuptools/tests/test_dist.py
- setuptools/tests/test_upload.py
This PR adds `get_metadata_version` to `distutils.dist.DistributionMetadata` and also monkey patches `distutils.dist.DistributionMetadata.read_pkg_file` to populate the `metadata_version` attribute. We also have overridden  `distutils.command.upload.upload_file` so that the metadata version is retrieved from `get_metadata_version` rather than hard-coded as 1.0.
I felt that it would be preferable for `read_pkg_file` to actually store the specified metadata version rather than to infer it from the fields present (as is done when *writing* the metadata file), *however*, I think the bug I'm concerned about would still be fixed if we always had `get_metadata_version` infer the version from the keys present.
Closes #1381
> Fix upload metadata

- CHANGES.rst
- changelog.d/1395.doc.rst
- changelog.d/1456.doc.rst
- changelog.d/1519.change.rst
- changelog.d/1531.misc.rst
- changelog.d/1533.misc.rst
- changelog.d/1537.doc.rst
- changelog.d/1539.doc.rst
- changelog.d/1541.deprecation.rst
- changelog.d/1545.feature.rst
- changelog.d/1552.doc.rst
- changelog.d/1553.doc.rst
- changelog.d/1554.change.rst
- changelog.d/1560.doc.rst
- changelog.d/1564.doc.rst
- changelog.d/1572.misc.rst
- changelog.d/1576.change.rst
- docs/setuptools.txt
Updating the news for the 40.6.0 release.
Doing this as a PR so I can see the netlify generated docs.
> Release 40.6.0

- setuptools/command/upload.py
- setuptools/tests/test_dist.py
- setuptools/tests/test_upload.py
- tests/manual_test.py
Fix for usage external `six` module, that was added at #1576 (v.40.6.0).
Closes  #1592
> Import internal version of six

- changelog.d/1544.change.rst
- setuptools/tests/test_packageindex.py
- Added unittest for _download_git function
Closes 
#1504
> added unittest for _download_git

- changelog.d/1625.change.rst
- setuptools/build_meta.py
- setuptools/tests/test_build_meta.py
Always build gztar in build_meta
Closes #1623
> In build_meta (PEP 517), always built gztar

- changelog.d/1635.change.rst
- docs/pkg_resources.txt
- pkg_resources/__init__.py
- pkg_resources/tests/test_pkg_resources.py
Disallow parent path traversal in resource paths, part 1 (deprecation).
Reference #1635.
> Disallow parent path traversal in resource paths, part 1 (deprecation)

- changelog.d/1660.change.rst
- setuptools/dist.py
- setuptools/tests/environment.py
- setuptools/tests/test_build_ext.py
> Prefer native strings on Python 2 when reading config files.

- MANIFEST.in
Explicitly exclude `pyproject.toml` so it's never added (e.g. because `setuptools_scm` is used).
> tweak #1644 workaround to fix `test_pip_upgrade_from_source`

- pyproject.toml
Per @gaborbernat's suggestion, dropping the `build-backend`. I don't know if it makes sense to keep `build-system` at all, but this is the minimal change required to allow us to use `--no-use-pep517` (which is required on the current version of `pip` when building from the repo).
Bernat discovered this when building the first infrastructure for the integration testing repo.
> Drop build-backend from pyproject.toml

- changelog.d/1675.change.rst
- setuptools/build_meta.py
- setuptools/tests/test_build_meta.py
Many projects can get away with an empty `setup.py` and use *only* the declarative `setup.cfg`. With the new PEP 517 backend, we can supply a default empty `setup.py` if one is not provided.
> Add support for setup.cfg-only projects

- .bumpversion.cfg
- setup.cfg
- setup.py
This change moves the setuptools version to declarative config. In order to accomplish this, the bump2version config had to be moved to .bumpversion.cfg.
I'm creating this PR in light of #1679, which conflicts with this change, to highlight the direction that I'd prefer the setuptools project should move.
> Move version to declarative config

- .travis.yml
- appveyor.yml
- setuptools/tests/test_virtualenv.py
- tox.ini
Parametrize the test to check different versions of pip (including master) are correctly supported. Fix #1649.
> tests: improve `test_pip_upgrade_from_source`

- setuptools/dist.py
found by lgtm
A duplicate import of io has been removed. This duplication was found by lgtm.com
Closes
> remove duplicate import io

- setuptools/dist.py
Looks like this was copy-pasted and not updated.
Found here: https://twitter.com/maphewyk/status/1095933345912025088
> Fix typo in docstring

- changelog.d/1720.change.rst
- setuptools/build_meta.py
- setuptools/tests/test_build_meta.py
In the original `setup.py` interface, `setup_requires` would also accept some newline-delimited string format (including comments), but `setuptools.build_meta` assumes that you have passed a `list` when converting `setup_require` to `get_requires_for_*`.
In this PR, I've added this behavior to `setuptools.build_meta`, but an argument could be made for restricting this to `setuptools.build_meta:__legacy__` and requiring a `setup_requires` to take a list in the main `build_meta`.
Closes #1682.
> Support requirement parsing in setuptools.build_meta

- changelog.d/1664.change.rst
- pkg_resources/__init__.py
- pkg_resources/tests/test_pkg_resources.py
> Fix #1664: Include path in error message when version is missing

- changelog.d/1709.bugfix.rst
- setuptools/command/test.py
When running in a complex environment with lots of installed
packages, PYTHONPATH gets way too long. Instead, just make sure
that paths_on_pythonpath doesn't contain duplicates
I don't expect this to be accepted. Just letting you know there's a problem here and how to fix it.
> uniquify paths in PYTHONPATH

- changelog.d/1741.change.rst
- setuptools/package_index.py
- setuptools/tests/test_packageindex.py
Windows does not change the working directory for a process via `cd .. && <process>` (see e.g. this question: https://stackoverflow.com/q/55641332/8575607 ). This commit replaces the use of `(cd %s && <command>)` with arguments provided by `git` and `hg` respectively.
Closes #1740
> FIX: git and hg revision checkout under Windows

- setuptools/tests/test_build_meta.py
As a mitigation for #1730, this commit limits the number of workers in the `ProcessPoolExecutor` to 1 (default is the number of CPUs). On PyPy, having a higher number of available workers dramatically increases the number of concurrent processes, leading to some resource exhaustion issues.
This does not address the root issue, but should improve the situation until the root issue is addressed.
> Limit workers in ProcessPoolExecutor

- changelog.d/1671.change.rst
- setuptools/build_meta.py
- setuptools/py31compat.py
- setuptools/tests/test_build_meta.py
``build_meta.build_wheel`` uses a temporary directory for cases where ``wheel_directory`` already has 
existing `.whl` files (so as to not throw unpacking error).
Changes from the patch discussed in the issue:
- pay the cost of creating / cleaning a temp-dir only if necessary
- make it python2.7 compatible
Closes #1671
> Fix error with PEP 517 builds when wheel exists (GH #1761)

- .travis.yml
Now that the issue with invalid coverage data has been fixed.
> travis: re-enable coverage for Python 3.8 job

- changelog.d/1749.change.rst
- changelog.d/1750.change.rst
- setuptools/build_meta.py
- setuptools/tests/test_build_meta.py
Fix the following cases:
* `build_sdist` is called with another sdist already present in the destination directory (#1749)
* `build_wheel` is called with the destination directory not already created
Closes #1749.
> build_meta: fix 2 issues with `build_wheel` / `build_sdist`

- changelog.d/1697.change.rst
- setup.cfg
- setup.py
Moved most of the constants from setup.py to setup.cfg
Closes: #1697
> Migrate constants from setup.py to setup.cfg

- changelog.d/1756.change.rst
- setuptools/dist.py
- setuptools/tests/test_egg_info.py
Closes: #1756
Force `metadata_version` 1.2 in presence of project urls.
I'd have liked to add some tests, but looking at `test_dist.py`, I had no clue how to update any of the existing ones.
> Force metadata-version = 1.2 when project urls are present.

- tests/requirements.txt
The new releases for pytest-fixture-config and pytest-shutil are compatible with pytest>=4.0.
Close  #1638.
> tests: unpin pytest

- changelog.d/1788.change.rst
- setuptools/py33compat.py
HTMLParser.unescape is deprecated since Python 3.4.
- **N/A** Changes have tests
> stop using deprecated HTMLParser.unescape

- changelog.d/1776.doc.rst
- docs/setuptools.txt
The license field has a 'free' format, while the classifiers are unique
identifiers, similar to SPDX identifiers. In the documentation, we
should therefore showcase the use of classifiers.
> Use license classifiers rather than the license field.

- changelog.d/1790.change.rst
- pkg_resources/__init__.py
- pkg_resources/tests/test_pkg_resources.py
Fixes https://github.com/pypa/setuptools/issues/1790 .
> Fix #1790 : Include the file path in get_metadata() UnicodeDecodeErrors

- changelog.d/1769.change.rst
- setuptools/dist.py
- setuptools/tests/test_dist.py
`package_data` and `exclude_package_data` expect to receive a dictionary whose values are lists rather than strings. Previously, passing a str value did not cause any warning or error, which is dangerous because users accidentally input a glob/path that then gets iterated into individual characters.
Refs https://github.com/pypa/setuptools/issues/1459
> Perform a more thorough check of package_data structure

- setuptools/tests/test_virtualenv.py
Do not test pip's master on 3.4, as support for it has been dropped.
> tests: fix `test_pip_upgrade_from_source` on Python 3.4

- .travis.yml
- changelog.d/1565.misc.rst
- docs/conf.py
Changed html_sidebars from single string to list of string as per 
https://www.sphinx-doc.org/en/master/changes.html#id58
Closes https://github.com/pypa/setuptools/issues/1565
> Fixed html sidebars to supported version in Sphinx

- launcher.c
execv() requires process.h to be included according to the MSVC documentation
but for some reason it also works without it.
mingw-w64 on the other hand fails to build the launcher if the include isn't there,
so add it.
> launcher: Fix build with mingw-w64

- changelog.d/1690.change.rst
- setuptools/_vendor/ordered_set.py
- setuptools/_vendor/vendored.txt
- setuptools/dist.py
- setuptools/extern/__init__.py
- setuptools/tests/test_dist.py
Alternative approach to #1305, this approach simply replaces the set with an ordered set, retaining the order of extras as found in the package's 'extras_require' dictionary. On older Pythons where the dictionary ordering is non-deterministic, that non-determinism will still be present.
Closes
> Honor declared ordering for Provides-Extra entries in package metadata.

- changelog.d/1847.change.rst
- setuptools/config.py
- setuptools/tests/test_config.py
> Crash when invalid python_requires indicated in setup.cfg

- changelog.d/1860.doc.rst
- docs/setuptools.txt
* mention dependency links support was dropped in pip 19.0
* mention eggs are deprecated and not supported by pip
> Small documentation tweaks

- changelog.d/1878.change.rst
- docs/setuptools.txt
- setuptools/command/test.py
- setuptools/tests/test_test.py
> Deprecate the test command

- setuptools/tests/test_config.py
- setuptools/tests/test_test.py
While perfectly valid, the encoding 'UTF-8' (uppercase) is not
recognized by the Emacs MULE system. As such, it displays the following
warning when opening a file with it used as an encoding cookie:
Warning (mule): Invalid coding system ‘UTF-8’ is specified
for the current buffer/file by the :coding tag.
It is highly recommended to fix it before writing to a file.
Some discussion of this can be found at:
https://stackoverflow.com/questions/14031724/how-to-make-emacs-accept-utf-8-uppercase-encoding
While the post does offer a workaround for Emacs users, rather than ask
all to implement it, use the more typical utf-8 (lowercase).
> Change coding cookie to use utf-8 (lowercase)

- setuptools/tests/test_test.py
The test command has not called sys.exit since commit 2c4fd43277fc477d85b50e15c37b176136676270.
> Remove outdated comment and suppressed exception from test_test.py

- changelog.d/1884.doc.rst
- setup.cfg
Travis has official support for the Python 3.8 release, so can use that instead of 3.8-dev.
> Document support for Python 3.8 through a trove classifier

- changelog.d/1811.change.rst
- setuptools/msvc.py
* Improve VC++14 support for VS 2017 and 2019.
* Separate VC from VS version (Miss match starting VS15).
* Improve docstrings args and returns information + fixe typos.
* Fix coding style and minor coding issues.
* Remove Microsoft "Windows SDK 7.0" dead link.
Tested on Windows 10 with Python 3.7.4 and "Visual Studio Build Tools 2019" with following setup cases:
* VC++14.2 (VS 2019)
* VC++14.1 (VS 2017)
* VC++14.0 (VS 2015)
This setuptools file cover a wide variety of VS configurations that I cannot test easily. So any code review and other tests are really welcome. 
There is no automated tests for this. This setuptools part did not really had tests before this PR, and it may be very hard to do real relevant automated tests for it.
> Improve Visual C++ 14.X support

- changelog.d/1824.change.rst
- pkg_resources/__init__.py
- pkg_resources/api_tests.txt
- pkg_resources/tests/test_resources.py
- setup.py
- setuptools/command/bdist_egg.py
- setuptools/command/easy_install.py
- setuptools/package_index.py
- setuptools/tests/test_bdist_egg.py
found using [asottile/python3.10](https://github.com/asottile/python3.10)
> Fixes for python3.10

- docs/setuptools.txt
While the use of an asterisk key in the `package_data` section of `setup.cfg` is shown in an example, I couldn’t see it documented anywhere in reference material. As I was looking for reference material, not an example, I missed it for quite a while. Add a note to the table.
- I thought this was sufficiently trivial as to not require a changelog entry; I will make one if you think otherwise.
> Document using asterisk in package_data section

- changelog.d/1814.change.rst
- pkg_resources/__init__.py
- pkg_resources/tests/test_resources.py
Take PEP 508 direct URL into account.
> pkg_resources: fix ``Requirement`` hash/equality implementation

- changelog.d/479.bugfix.rst
- conftest.py
- setuptools/_imp.py
- setuptools/depends.py
- setuptools/py27compat.py
- setuptools/py34compat.py
- setuptools/tests/test_integration.py
Fix;
```console
(.venv) batuhan@x200-trisquel:~/astor$ python setup.py develop
/home/batuhan/.venv/lib/python3.8/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
import imp
```
> Upgrade setuptools.depends to importlib from depracated imp

- changelog.d/1861.change.rst
- setuptools/tests/test_wheel.py
- setuptools/wheel.py
Fix a corner case found with one of the tests when implementing #1830: handle installing a wheel with an empty namespace package.
> Fix empty namespace package wheel install

- pytest.ini
- tests/requirements.txt
- tools/tox_pip.py
- tox.ini
Make it possible to use a more recent version of pip for tests. Necessary for #1830.
> improve workaround for #1644

- setuptools/tests/test_integration.py
Fix those warnings:
```
setuptools/tests/test_integration.py:67: PytestWarning: Value of environment variable PYTHONPATH type should be str, but got u'...' (type: unicode); converted to str implicitly
monkeypatch.setenv('PYTHONPATH', os.path.pathsep.join(sys.path))
```
> tests: fix some pytest warnings under Python 2

- changelog.d/1767.change.rst
- docs/setuptools.txt
- setuptools/command/sdist.py
- setuptools/config.py
- setuptools/dist.py
- setuptools/tests/test_egg_info.py
Support for `license_file` was added to `bdist_wheel` in pypa/wheel#47 / pypa/wheel@0acfb4c19dc2d2f2d067eead3d59a5f3415c5c20 and then to setuptools in #1536. Last year, wheel also added support for a `license_files` option in pypa/wheel#138 / pypa/wheel@59976ab294e1b118f42cab404d95df66ed55f7e4 to enable including more than one license. At the same time, `license_file` was deprecated in that project, and using it leads to a `DeprecationWarning` if warnings are enabled. The [docs](https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file) for wheel also mention that `license_files` is the favored option.
Currently, setuptools only supports `license_file`, which leads to the `DeprecationWarning` code path if wheel is also used when building …
> Add support for `license_files` option in metadata

- changelog.d/1830.breaking.rst
- changelog.d/1909.breaking.rst
- docs/easy_install.txt
- docs/index.txt
- easy_install.py
- setup.cfg
- setup.py
- setuptools/command/easy_install.py
- setuptools/tests/test_easy_install.py
- setuptools/tests/test_namespaces.py
This reverts commit 6e1838a9fb5feb000ba9b6a3c37c8b39d7e872b3.
> Revert "drop easy_install script and associated documentation"

- changelog.d/1918.change.rst
- setuptools/tests/test_wheel.py
- setuptools/wheel.py
Fix `Wheel.is_compatible` implementation, which I bungled in #1829.
> wheel: fix `is_compatible` implementation

- changelog.d/1922.change.rst
- setuptools/installer.py
- setuptools/tests/test_easy_install.py
Handle the case where a missing transitive build dependency is required by an extra for an already installed build dependency.
Example:
* a test package with a `setup.py` containing: `setup_requires=['dep[extra]']`
* `dep` is already installed, and the dependencies for `extra` are: `['extra_dep']`
* `extra_dep` is not already installed, and `fetch_build_egg('extra_dep; extra =="extra"')` is called
If the marker is not stripped, `pip wheel [...] 'extra_dep; extra =="extra"'` ignores the requirement, and does not build a wheel, but still returns with no error.
Closes the second issue found in #1920.
> fix possible issue with transitive build dependencies

- changelog.d/1921.change.txt
- setuptools/installer.py
- setuptools/tests/test_easy_install.py
The easy_install's `find-links` option can sometime be a string (and not a list of string), e.g. when its value comes from `setup.cfg` (see handling in [easy_install own code](https://github.com/pypa/setuptools/blob/master/setuptools/command/easy_install.py#L345)).
Ensure it's similarly handled in `fetch_build_egg`.
Closes #1920, #1375, and probably #1880.
> fix support for easy_install's find-links option in setup.cfg

- .travis.yml
- tox.ini
This approach adopts the release process from jaraco/skeleton. This approach gives the project more control over the release process, decoupling from DPL (which has its own issues) and relies on tokens as installed to environment variables (as travis has issues with that).
This approach makes it possible to cut manual releases with `tox -e release` (assuming TWINE_PASSWORD is set to a valid token) as well as control other things about the release process (such as using pep517 to build the dists).
Compared to the attempt in #1925, this approach avoids switching to pep517 for the build. Even though that approach proved viable for cutting releases, it's not viable for the test environments.
> Simplified mechanized release process through tox

- changelog.d/1927.change.rst
- pyproject.toml
- tools/tox_pip.py
Per Paul's [comment](https://github.com/pypa/setuptools/issues/1644#issuecomment-554677756) in #1644, this change restores the build backend and removes the workaround to avoid pep517.
Rather than selecting 40.0, I chose 40.8 based on the error message reported in #1923.
> Restore build-backend and remove switch to avoid pep517.

- .travis.yml
- changelog.d/1908.breaking.rst
- docs/easy_install.txt
- pkg_resources/__init__.py
- setup.cfg
- setuptools/tests/test_virtualenv.py
- tests/requirements.txt
- tox.ini
Drop support for Python 3.4, which reached end-of-life in March 2019.
> drop support for Python 3.4

- changelog.d/1959.change.rst
- setuptools/command/build_ext.py
- setuptools/command/develop.py
- setuptools/command/easy_install.py
- setuptools/command/egg_info.py
- setuptools/command/sdist.py
- setuptools/command/test.py
- setuptools/command/upload_docs.py
- setuptools/dist.py
- setuptools/tests/test_develop.py
- setuptools/tests/test_sdist.py
- setuptools/tests/test_setopt.py
We don't yet know if 3.10 or 4.0 will follow Python 3.9, but whichever it is, it will probably happen in [2020 when Python 3.9 reaches beta](https://www.python.org/dev/peps/pep-0596/#schedule) and work begins on Python 3.9+1.
There's some code which uses `six.PY3`:
```python
if six.PY3:
print("Python 3+ code")
else:
print "Python 2 code"
```
Where:
```python
PY3 = sys.version_info[0] == 3
```
When run on Python 4, this will run the Python 2 code! Instead, use `six.PY2`.
Found using https://github.com/asottile/flake8-2020
> Fix for Python 4: replace unsafe six.PY3 with PY2

- .travis.yml
- appveyor.yml
- changelog.d/1458.breaking.rst
- pkg_resources/__init__.py
- pkg_resources/py2_warn.py
- setup.cfg
This change does not yet remove any of the compatibility for Python 2, but only aims to declare the dropped support.
Closes #1458
> Require Python 3.5 or later, dropping support for Python 2.

- docs/setuptools.txt
This was incorrectly changed in #1938.
> Fix TestPyPI upload URI

- tools/tox_pip.py
- tox.ini
Minimize the hook for removing setuptools from the environment.
> Rely on tox-pip-version to upgrade pip

- .travis.yml
- tools/tox_pip.py
- tox.ini
Follow-up to #1955, this change allows the tests to run on Python 2 even though the packages declares a requirement on Python 3.5 or later. This change will prevent the risk of bit-rot on the master and maintain the expectation that Python 2 compatibility is retained for those installers not honoring PEP 345.
> Restore testing on Python 2, bypassing the requires-python check when installing Setuptools.

- .github/workflows/python-tests.yml
Demo: https://github.com/webknjaz/setuptools/runs/209318165 (in fork because it won't show up in upstream w/o merge)
> Integrate GitHub Actions CI/CD  tests

- changelog.d/1704.change.rst
- setuptools/build_meta.py
- setuptools/tests/test_build_meta.py
Some setup.py scripts, use sys.argv[0] to locate the source directory of a project. I only added this to build_meta.\_\_legacy__ since that is focused on backwards compatibility with old scripts. However, @pganssle said this behaviour should not be added to setuptools.build_meta. 
Closes #1628
> Set sys.argv[0] in build scripts run by build_meta

- setup.cfg
The project has been Python 3 only since
a46a6bfd903ecc292fc3645c37c1b72781528095.
> Add 'Programming Language :: Python :: 3 :: Only' trove classifier

- setup.cfg
v45 doesn't support Python 2 any more, but  [`setup.cfg`](https://github.com/pypa/setuptools/blob/master/setup.cfg) is still set to create a universal wheel. I've removed the `[bdist_wheel]` block.
Closes #1976 
Alternative solution to #1977
> Ensure bdist_wheel no longer creates a universal wheel [remove bdist_wheel block], close #1976

- changelog.d/1968.misc.rst
- tests/requirements.txt
Add https://github.com/asottile/flake8-2020 plugin to Flake8.
To prevent regressions of things like https://github.com/pypa/setuptools/pull/1959 and make sure no problematic version comparisons are introduced which may break on Python 3.10, Python 4 or Python 10.
> Add flake8-2020 to tests/requirements.txt

- pyproject.toml
Because Requires-Python is disabled for Python 2 to allow this declared-incompatible version to install on Python 2, the build-requirements must exclude installing setuptools 45 during the build-system setup.
Because Python 2 tests are only needed for internal validation, and because the latest pip is already installed, the build-system can rely on `backend-path = ["."]`.
Fixes #1996.
> Avoid installing setuptools 45 on Python 2.

- changelog.d/1994.change.rst
- setuptools/dist.py
The order attribute (if specified) is now honored for the targets of entrypoints in the `setuptools.finalize_distribution_options` group. Since introduction of these entrypoints in #1055 / #1877 there was a bug that caused the default `order` of `0` to be used regardless of what the target specified.
Closes  #1993
This is my first PR in setuptools. I will add a towncrier changelog file and maybe a test of entrypoint execution order as soon as I have the chance and people here agree that my change is acceptable.
> honor order attribute in "finalize_distibution_options" group of entrypoints

- .readthedocs.yml
- docs/requirements.txt
- setup.cfg
Fixes #2001 (option 2). Ref readthedocs/readthedocs.org#6662
> Copy docs requirements to a separate file due to RTD constraints.

- appveyor.yml
- changelog.d/1904.change.rst
- setuptools/msvc.py
- setuptools/tests/test_msvc14.py
- tox.ini
Update `msvc.py` to use CPython 3.8.0 mechanism to find msvc 14+ as recommended in this [comment](https://github.com/pypa/setuptools/issues/1851#issuecomment-537714885).
Closes #1903 
This PR has been tested as part of [cibuildwheel tests using various CI providers](https://github.com/joerick/cibuildwheel/pull/194).
Please note that I can't test it more thoroughly cause I don't have any Windows environment at hand (except for CI which requires very long iterations).
> Use CPython 3.8.0 mechanism to find msvc 14+

- changelog.d/2011.doc.rst
- docs/setuptools.txt
Fix a broken link that leads to `distutils` documentation for the `package_data` argument.
The broken link used to point to Python 2 docs (which has been moved).
Since Python 2 has reached its end-of-life, link to Python 3 docs instead.
> Fix broken link to distutils docs for package_data

- MANIFEST.in
- changelog.d/1991.misc.rst
This is the error otherwise:
```
_____________ TestFindDistributions.test_standalone_egg_directory ______________
self = <pkg_resources.tests.test_find_distributions.TestFindDistributions object at 0x7f17518a86d0>
target_dir = local('/tmp/pytest-of-mockbuild/pytest-0/test_standalone_egg_directory0/target')
def test_standalone_egg_directory(self, target_dir):
(TESTS_DATA_DIR / 'my-test-package_unpacked-egg').copy(target_dir)
dists = pkg_resources.find_distributions(str(target_dir))
>       assert [dist.project_name for dist in dists] == ['my-test-package']
E       AssertionError: assert [] == ['my-test-package']
E         Right contains one more item: 'my-test-package'
E         Use -v to get the full diff
pkg_resources/tests/test_find_distributions.py:25: AssertionError …
```
> Include pkg_resources test data in sdist

- setuptools/package_index.py
When an authentication error occurs fetching the package index, it's difficult to tell the cause of the error.  This PR adds a short error message that indicates an authentication error occured.
Before:
Searching for flask
Reading http://localhost:8081/repository/pypi-proxy/simple/flask/
Couldn't find index page for 'flask' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading http://localhost:8081/repository/pypi-proxy/simple/
No local packages or working download links found for flask
error: Could not find suitable distribution for Requirement.parse('flask')
After:
Searching for flask
Reading http://localhost:8081/repository/pypi-proxy/simple/flask/
Authentication error: Unauthorized
Couldn't find index page for 'flask' (maybe misspelled?)
Scanning index of …
> Add info message on package index auth error 

- changelog.d/308.change.rst
- setuptools/__init__.py
- setuptools/dist.py
- setuptools/tests/test_dist.py
As discussed in #308, this proposed change adds a simple API to bypass version number normalization, forcing the user to explicitly opt into this undesirable behavior. Now a user can specify:
```
from setuptools import setup, sic
setup(version=sic('1.0.0a'))
```
And version number normalization will be skipped.
> Add 'sic' function to bypass version number normalization

- changelog.d/1431.change.rst
- changelog.d/1431.chnage.rst
- setuptools/command/easy_install.py
Problem: In Fedora, `sudo python3 setup.py install` installs to /usr/local/lib/pythonX.Y/site-packages. However that directory is not always there as it is not installed together with the python3 package (Fedora packages should not install stuff to /usr/local).
When the directory does not exist an installation attempt fails with:
[Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/test-easy-install-11875.write-test'
Solution: Make the directory if it doesn't exists yet. If user has no permissions, the above error is preserved, yet with root (sudo) it works now.
I realize that this is not usefull outside Fedora's specific setup, yet I don't like downstream only patches and this breaks nothing.
> Make install directory if it doesn't exist yet

- changelog.d/1563.change.rst
- pkg_resources/__init__.py
Change the call of `find_module` to `find_spec`.
Attempts to fix Ron89/thesaurus_query.vim#33 and analogous issue tbabej/taskwiki#183, probably others brought about by vim/vim@79a494d5.
> Change find_module to find_spec for py37 compat

- changelog.d/1424.change.rst
- setuptools/command/build_py.py
Prevent keeping files mode for package_data build. It may break a build if user's package data has read only flag. It will be copied to build folder and set RO flag again. Then at the clean up stage a script will not be able to remove this files, asserting Access denied.
Closes #1424
> Don't keep file modes for package data.

- changelog.d/2041.bugfix.rst
- setuptools/command/build_py.py
- setuptools/tests/test_build_py.py
Closes #2041, supersedes #2044 and #2043.
> Retain executable mode

- changelog.d/2040.change.rst
- setuptools/command/bdist_wininst.py
- setuptools/tests/test_bdist_deprecations.py
For #1988.
Already deprecated in CPython 3.8's `distutils`.
The deprecation method, message and tests are modelled on the recent https://github.com/pypa/setuptools/pull/1764 (deprecate "eggsecutable" scripts).
I had a go at the other bdists mentioned in #1988, but had a hard time with the tests, so here's just one to be getting on with.
> Deprecate bdist_wininst

- changelog.d/1698.doc.rst
- docs/build_meta.txt
#1698  Summary of changes
Added documentation for build_meta. It is not fully completed but with enough content to get started with the module. (This is my first time contributing and I'm trying my best to follow the guidelines and beginner docs, hopefully I didn't miss anything:) 
I have made the simplification that it is a ``setup.cfg`` only package. But I can definitely change this later!
> Added documentation for build_meta

- .gitignore
- CHANGES.rst
- changelog.d/2062.change.rst
- docs/history.txt
- docs/pkg_resources.txt
- pkg_resources/__init__.py
- pkg_resources/_vendor/appdirs.py
- pkg_resources/api_tests.txt
- setuptools/package_index.py
Signed-off-by: Reece Dunham <me@rdil.rocks>
OS X isn't what macOS is called anymore.  This fixes it.
A couple other small fixes included aswell related.
> change: Mac OS X -> macOS

- changelog.d/2082.misc.rst
- pytest.ini
lib2to3 is deprecated in Python 3.9: https://bugs.python.org/issue40360
Workarounds https://github.com/pypa/setuptools/issues/2081
> Filter lib2to3 (Pending)DeprecationWarning in testes

- changelog.d/2086.change.rst
- setuptools/lib2to3_ex.py
- setuptools/tests/test_test.py
As discussed in #2086, and as planned for years, deprecate the 2to3 feature. Instead, packagers are encouraged to write single-source code or build a tool chain outside of setuptools to perform conversions.
> Emit deprecation warning when 2to3 is used.

- docs/setuptools.txt
This note has gotten a bit out of date, since setup.py is no longer required.
- N/A Changes have tests
> Tweak note about setup.cfg

- changelog.d/2075.breaking.rst
- changelog.d/2075.change.rst
- pkg_resources/__init__.py
- pkg_resources/tests/test_pkg_resources.py
As proposed in [PEP 376](https://www.python.org/dev/peps/pep-0376/), dist-info distributions must be directories.
Closes pypa/pip#8122.
Edit: apparently files with `dist-info` extension seems to be an supported behavior for `setuptools`.  I'll try to investigate why.
> Stop recognizing files ending with .dist-info as dist

- changelog.d/2105.misc.rst
- setuptools/tests/__init__.py
- setuptools/tests/test_develop.py
- setuptools/tests/test_test.py
Closes https://github.com/pypa/setuptools/issues/2100
> Reuse @ack_2to3 in TestDevelop.test_2to3_user_mode

- changelog.d/1753.change.rst
- docs/setuptools.txt
- setuptools/config.py
- setuptools/tests/test_config.py
As I'm sure we all know, the `attr:` config directive for the `version` option in `setup.cfg` doesn't work when the specified module imports one or more third-party packages, thereby forcing package authors to [use a different strategy](https://packaging.python.org/guides/single-sourcing-package-version/).  Proposals have been made (#1316, #1679, others?) to add a function to `setuptools` that encapsulates the necessary code for strategy number 1, but these have been rejected, most recently with [the comment](https://github.com/pypa/setuptools/pull/1679#pullrequestreview-204563938):
> On the other hand, we're already discouraging use of imperative code in setup.py. Most importantly, this behavior doesn't have a comparable syntax in setup.cfg. That is, one cannot specify to load the …
> Support attr directive with static evaluation

- docs/pkg_resources.txt
In the API reference for requirements parsing:
https://setuptools.readthedocs.io/en/latest/pkg_resources.html#requirements-parsing
There is offered an example `PickyThing<1.6,>1.9,!=1.9.6,<2.0a0,==2.4c1` that strongly implies commas mean logical OR.  [But PEP440 says commas mean logical AND](https://www.python.org/dev/peps/pep-0440/#version-specifiers).
I've edited it into a more realistic example to avoid this potential confusion. 
Related is https://github.com/pypa/pip/issues/2744, which was promptly closed some time ago but never actually fixed (maybe just a simple oversight - ping @dstufft?)
> Give a less confusing example for requirements parsing

- docs/userguide/quickstart.txt
This PR should now have incorporated/complemented what's made in #1738 and the ``build_meta.txt`` file but I will check more thoroughly on that. Please let me know there were mistakes in this documentation too:) I have tried my best to go through the source code to see how keywords in ``setup.cfg`` are handled and tested out my own examples, but there might still be things I overlooked. If there are suggestions please let me know I'm more than happy to have other people's input.
Step 4 on #2093 
Proposed a quickstart user guide that adheres to PEP517 and provides a brief overview on the following functionalities of setuptools, with each section pointing to another page (WIP) that covers the details and more advanced usage. 
1. installation
1. basic use 
1. Automatic package discovery
1. …
> Step 4: A PEP517-styled quickstart user guide and room for collaboration

- docs/userguide/package_discovery.txt
Step 5 on #2093 
Created user guide for automatic package discovery and namespace package supported by setuptools. It covers the following aspects in both ``setup.py`` and ``setup.cfg`` style:
- automatic package discovery with ``find_packages``
- overview on namespace package
- automatic package discovery with ``find_namespace_package``
- legacy use of namespace package
The quickstart guide's package discovery section references this file
If these looks good I can do the rebasing myself to make merging easier.
> Step 5 on 2093: Package discovery and namespace package userguide now ready

- docs/build_meta.txt
The `decalrative config`_ link present higher in the document is also
unresolved, I'm not quite sure what the intended target was.
> DOC: fix link missing >

- changelog.d/2156.doc.rst
- docs/developer-guide.txt
Per https://groups.google.com/d/msg/pypa-dev/rUNsfIbruHM/LCEx-CB5AgAJ
the pypa-dev Google Group is now decommissioned.
Pointing to distutils-sig instead.
Signed-off-by: Sumana Harihareswara <sh@changeset.nyc>
> DOC: Update mailing list link

- changelog.d/2194.change.rst
- setuptools/command/easy_install.py
- setuptools/tests/test_easy_install.py
When `importlib.metadata` is present, the generated scripts will use that rather than the significantly slower `pkg_resources`.
Closes https://github.com/pypa/setuptools/issues/510 completely as editable installs are the final affected part (that is actionable) brought up in that issue and what I've been experiencing the last 2 weeks (it's indeed annoying)
The issue is locked, so here are some pings: @jaraco @scopatz @ninjaaron @untitaker @asottile @pganssle @gaborbernat @pfmoore @pradyunsg
Before and after, using  [hyperfine](https://github.com/sharkdp/hyperfine):
> Decrease start-up time of editable-installed entry points on newer versions of Python

- changelog.d/2197.change.rst
- setuptools/command/easy_install.py
Follow-on to #2194 honoring #2195.
> Unify the entry point template.

- setuptools/package_index.py
I recently went over [Matplotlib](https://github.com/matplotlib/matplotlib/pull/16706), [Pandas](https://github.com/pandas-dev/pandas/pull/32322) and [NumPy](https://github.com/numpy/numpy/pull/15731), fixing a small mistake in the way that Python 3's exception chaining is used. If you're interested, I can do it here too. I've done it on just one file right now. 
The mistake is this: In some parts of the code, an exception is being caught and replaced with a more user-friendly error. In these cases the syntax `raise new_error from old_error` needs to be used.
Python 3's exception chaining means it shows not only the traceback of the current exception, but that of the original exception (and possibly more.) This is regardless of `raise from`. The usage of `raise from` tells Python to put a …
> Fix exception causes in package_index.py

- changelog.d/2071.misc.rst
- setuptools/command/bdist_egg.py
- setuptools/command/build_ext.py
When the PYTHONWARNINGS environment variable is set, I often see the message `DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses` in conjuction with bootstrap files for compiled modules. This pull request fixes the code that triggers that warning.
> Use importlib instead of imp in __bootstrap__ functions

- .coveragerc
- .github/workflows/python-tests.yml
- .travis.yml
- pytest.ini
- tox.ini
In #2221, I learned a lot more about the coverage configuration.
There are settings around coverage scattered across CI invocations, tox configurations, etc. This approach instead attempts configure the coverage in one place, enable it in one place, and provide one workaround for PyPy slowness.
> Improve coverage configuration

- pkg_resources/__init__.py
- setuptools/launch.py
- setuptools/msvc.py
- setuptools/tests/test_build_ext.py
This is a start: there are still 3 pypy failures after this change.
I think they are related to sysconfig specifically finding `Python.h`, and one may be a bad test.
> add pypy schemas to command/install.py

- docs/developer-guide.txt
I noticed a very minor typo in `docs/developer-guide.txt`. In the section _Vendored Dependencies_, the path to `vendored.txt` in `pkg_resources/` reads `pkg_reosurces/_vendor/vendored.txt`, where it should instead be `pkg_resources/_vendor/vendored.txt`. This was introduced in https://github.com/pypa/setuptools/commit/8aeff6b2c9a64e47ad2a22533d7e65c08cd4103f.
Because the change is so small, I haven't created an issue or a changelog entry. Previous corrected-typos-in-docs PRs that have been merged have done the same, so hopefully this is okay.
> Fix typo in path to vendored.txt

- changelog.d/2137.change.rst
- pkg_resources/__init__.py
In #1832, I learned that at least some users think the `RequirementParseError` should be exposed in `pkg_resources.__all__`. But diving into the history of that class, I don't think it was ever meant to be anything other than a nice error renderer. Can it just be removed?
> Remove superfluous RequirementParseError

- changelog.d/2180.change.rst
- pkg_resources/_vendor/packaging/__about__.py
- pkg_resources/_vendor/packaging/__init__.py
- pkg_resources/_vendor/packaging/_compat.py
- pkg_resources/_vendor/packaging/_structures.py
- pkg_resources/_vendor/packaging/markers.py
- pkg_resources/_vendor/packaging/requirements.py
- pkg_resources/_vendor/packaging/specifiers.py
- pkg_resources/_vendor/packaging/tags.py
- pkg_resources/_vendor/packaging/utils.py
- pkg_resources/_vendor/packaging/version.py
- pkg_resources/_vendor/vendored.txt
I bumped the version of vendor `packaging` of `pkg_resources` to v19.2 using the script proposed in #2179. I bumped it to v19.2 to keep it consistent with the version of packaging vendored under setuptools, but I can update this vendor to the latest version along with others as well if that's okay?
Closes #2175.
> Update vendor packaging in pkg_resources to v19.2

- changelog.d/2228.change.rst
- conftest.py
- setuptools/__init__.py
Based on emergent concerns (#2228, #2230), disable distutils adoption for now.
> Disable distutils adoption

- setuptools/_distutils/command/build_py.py
- setuptools/_distutils/tests/__init__.py
- setuptools/_distutils/tests/py38compat.py
- setuptools/_distutils/tests/support.py
- setuptools/_distutils/tests/test_archive_util.py
- setuptools/_distutils/tests/test_bdist_msi.py
- setuptools/_distutils/tests/test_bdist_wininst.py
- setuptools/_distutils/tests/test_build_ext.py
- setuptools/_distutils/tests/test_core.py
- setuptools/_distutils/tests/test_dist.py
- setuptools/_distutils/tests/test_extension.py
- setuptools/_distutils/tests/test_file_util.py
- setuptools/_distutils/tests/test_filelist.py
- setuptools/_distutils/tests/test_register.py
- setuptools/_distutils/tests/test_sdist.py
- setuptools/_distutils/tests/test_spawn.py
- setuptools/_distutils/tests/test_sysconfig.py
- setuptools/_distutils/tests/test_unixccompiler.py
Pull in 4 changes from distutils in CPython (mainly refactorings of the test suite).
> Refresh distutils

- changelog.d/2232.misc.patch
- setuptools/__init__.py
- setuptools/distutils_patch.py
In preparation for re-enabling a local copy of distutils, Setuptools now honors an environment variable, SETUPTOOLS_USE_DISTUTILS. If set to 'stdlib' (current default), distutils will be used from the standard library. If set to 'local' (default in a imminent backward-incompatible release), the local copy of distutils will be used.
> Re-enable distutils adoption with escape hatch

- .travis.yml
Run tests on `3.9-dev`, the nightly build of the CPython 3.9 branch. 
Python 3.9 is in beta with final release due out in October. 
3.8-dev is already tested. 
This should help avoid regressions or bugs due to changes in 3.9, or even help find problems in CPython 3.9 itself.
The build currently passes, suggesting https://github.com/pypa/setuptools/issues/2246 isn't yet covered by tests. 
- [n/a?] News fragment added in changelog.d. See [documentation](http://setuptools.readthedocs.io/en/latest/developer-guide.html#making-a-pull-request) for details
> Test Python 3.9-dev on Travis CI

- changelog.d/2249.misc.rst
- setuptools/command/bdist_egg.py
- setuptools/command/build_ext.py
I originally wrote this code using `load_module` and then changed it to `exec_module` because [the documentation](https://docs.python.org/3/library/importlib.html#importlib.abc.Loader.load_module) says that `load_module` is deprecated, but I didn't notice that `exec_module` requires an argument. Since it's not clear from the documentation how `exec_module` is supposed to be used, and `load_module` doesn't actually emit a DeprecationWarning (fixing the warning was the original motivation for changing this code), I think we should just use `load_module` for now.
> Change exec_module to load_module

- .github/ISSUE_TEMPLATE/blank.md
- changelog.d/2212.misc.rst
> Fix race in spawn

- changelog.d/2230.change.rst
- setuptools/distutils_patch.py
Discourage this usage and direct users to the recommended usage. Closes #2230.
> Warn the user when distutils is present

- conftest.py
- tox.ini
Building on #2224 and using the advice from pytest-dev/pytest-cov#418, programmatically disable coverage.
> Programmatically disable coverage when running on PyPy.

- docs/distutils-legacy.txt
- docs/index.txt
Give the users some guidance on porting from distutils, intended to capture the most common use-cases and recommended practices.
> Add docs on porting from distutils.

- .github/workflows/python-tests.yml
GHA has recently started shipping Python betas so I thought I'd add it.
`3.9.0-beta.4 - 3.9.0` is a semver range syntax that will get 3.9-beta set up in the worker.
I kept 3.9-dev and added 3.8-dev — these are still coming from deadsnakes PPA.
I've changed ubuntu-latest to concrete ubuntu-18.04 so that it's deterministic (at some point it'll be ubuntu-20.04 and that may come as a surprise).
I think it's possible to install the beta on macOS too but didn't know if that'd be wanted so I left it out.
> Set up GHA to test on Python 3.9-beta and 3.8-dev

- setup.cfg
- setuptools/tests/requirements.txt
- setuptools/tests/test_distutils_adoption.py
Add three tests to capture the expected and anticipated behavior for distutils adoption.
Ref #417
> Add tests capturing expected distutils behavior.

- CHANGES.rst
This was an artifact of the fact that I did not use `tox -e finalize` to do the latest release in order to make a patch release.
> Remove superfluous 'v' in CHANGES.rst

- changelog.d/2297.misc.rst
- setuptools/command/bdist_egg.py
- setuptools/command/build_ext.py
#2249 changed back from `exec_module` to the deprecated `load_module` (so I'll cc @alexhenrie). This PR moves forward to `exec_module` again. Credit to posts like https://stackoverflow.com/a/41595552/4093019
Also fixes the Pillow compilation error reported in #2261.
> Change load_module to exec_module

- changelog.d/2300.doc.rst
- docs/pkg_resources.txt
- Improve safe_version documentation
> Improve safe_version documentation

- docs/setuptools.txt
Hi, I moved the metadata description from `setup.py` to `setup.cfg`.
I found it desirable to have consistent indentation [in the documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html).
Python programmers are familiar with 4 space indentation. I also prefer consistent indentation in the `setup.cfg` documentation. What do you think?
Thanks to the maintainers of the setuptools source code and documentation.
> docs: Suggestion - Provide consistency in the description of setup.cfg

- changelog.d/2306.change.rst
- setuptools/build_meta.py
- setuptools/tests/test_build_meta.py
Under PEP 517, installing build dependencies is up to the frontend. `setup_requires` are already reported as build dependencies, but setuptools should not attempt to install them itself when used as a PEP 517 backend.
Closes #2303
> Don't install setup_requires when run as a PEP-517 backend.

- changelog.d/2129.change.rst
- pkg_resources/__init__.py
In pkg_resources, no longer detect any pathname ending in .egg as a Python egg. Now the path must be an unpacked egg or a zip file.
Avoid detecting arbitrary paths ending in .egg as eggs.
Closes #2129.
> Stricter egg detection

- docs/userguide/dependency_management.txt
step 7 on #2093 
This guide covers:
- build system requirement (on package and python)
- ``install_requires`` keyword with three use cases (basic, dependency_link, platform specific)
- optional dependencies with two use cases (entry point & inter-package)
I haven't tested the examples here and there were some components I'm debating whether to move to another file for deprecated usage (since we still want to adhere to PEP 517). But i'd like to have the bigger picture painted first before fixing those.
> step 7 on 2093: dependency management guide ready

- changelog.d/2334.change.rst
- setuptools/msvc.py
Changed two error strings to be up to date.
Closes 2302
> Resolving error text issue (#2302)

- _distutils_hack/__init__.py
- changelog.d/2361.change.rst
Get the 'Loader' abstract class from importlib.abc rather than
importlib.util.abc (alias removed in Python 3.10).
Closes
> Add Python 3.10 support to _distutils_hack

- _distutils_hack/__init__.py
- changelog.d/2352.misc.rst
Ref [bpo-30876](https://bugs.python.org/issue30876).
Fixes #2352.
> In distutils hack, use absolute import rather than relative to avoid bpo-30876.

- changelog.d/2380.change.rst
- setuptools/command/bdist_rpm.py
There are some setuptools specific changes in the bdist_rpm module that
are no longer needed, because the upstream/shipped version of distutils
already contains them. The code that is removed in this commit from
bdist_rpm is already part of the python-3.5 version of distutils.
Related: #2377
Closes
> Reduce size of setuptools' bdist_rpm._make_spec_file

- _distutils_hack/__init__.py
- changelog.d/2355.change.rst
> When pip is imported as part of a build, leave distutils patched.

- appveyor.yml
- conftest.py
- pyproject.toml
- pytest.ini
- setup.cfg
> Enable flake8 and cov plugins only when installed.

- .travis.yml
- changelog.d/2379.misc.rst
Hi,
I have added few jobs to support PPC64LE architecture, request you to please review.
Enhancement
- [No] Changes have tests
- [No] News fragment added in changelog.d. See [documentation](http://setuptools.readthedocs.io/en/latest/developer-guide.html#making-a-pull-request) for details
> Adding changes to support PPC64LE

- changelog.d/2395.doc.1.rst
- changelog.d/2395.doc.2.rst
- changelog.d/README.rst
- conftest.py
- docs/conf.py
- docs/developer-guide.rst
This change places a `README.rst` document under `changelog.d/` dir in
order for GitHub to render it when users navigate to this location via
the web UI. So that PR submitters can navigate to `changelog.d/` from
the main repo view and see something like this:
https://github.com/webknjaz/setuptools/tree/docs/changelog-fragments/changelog.d
It also includes that into the dev guide in Sphinx docs.
As a related change (totally atomic though), this PR also introduces a
`:user:` role that can be used in change note signatures as a means to
credit contributions to their authors.
(Demo: https://ansible-pylibssh.rtfd.io/en/latest/changelog/#vrelease-unreleased-draft-2020-09-09)
I've picked up this trick from tox and it's been working great for me so far.
Let me know what you think!
> Make an illustrative change notes guide in GH UI

- changelog.d/2413.misc.rst
- setuptools/command/build_py.py
Related to https://github.com/pypa/setuptools/issues/2086
lib2to3 appears to have a problem loading the pickled pgen files, when running in parallel on pypy: https://github.com/twisted/ldaptor/runs/1205572060#step:12:103 (raises EOFError)
Instead of catching the `EOFError` I catch any `Exception`, as that seems cleaner
I've not added tests yet, as I'd like a concept ACK first, eg, If you'd rather I just remove all use of lib2to3 from the codebase I could do that instead.
> ignore any exception when loading 2to3

- changelog.d/2394.doc.rst
- pyproject.toml
- towncrier_template.rst
This change adds news categories into the rendered changelog entries
so that it's visible what types of changes a new version brings.
Fixes #2394
> 📝 Enable showing news categories in towncrier log

- docs/userguide/index.rst
I added a paragraph of text in the index that briefly mentions how setuptools works under pep517,  and provided a link to the build_meta document as mentioned in (#1698 ). 
At first I thought the quickstart has already covered this document, but judging from the discussion, it seems like it still deserves its own page. It appears that the quickstart should target the end users that are not concerned about this internal module.
> Link to build_meta documentation

- .github/workflows/python-tests.yml
- changelog.d/2420.misc.rst
The CI is failing because it's failing to set up 3.9-beta via deadsnakes.
```
/usr/bin/python3.9 -mvenv /home/runner/venv-3.9
Error: Command '['/home/runner/venv-3.9/bin/python3.9', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
Error: The process '/usr/bin/python3.9' failed with exit code 1
```
* https://github.com/pypa/setuptools/runs/1239771433?check_suite_focus=true
Python 3.9.0 final is now available on GitHub Actions as `3.9`.
Let's add that, and we can remove the betas:
* `3.9.0-beta.4 - 3.9.0` from GHA
* `3.9-beta` from deadsnakes
I left in the `3.8-dev` and `3.9-dev` dev versions from deadsnakes. Still useful to keep them both?
I also left in the logic for checking `-beta`, will be useful for when 3.10 reaches beta (or to adapt for alpha). Let …
> GHA: Replace 3.9 beta with 3.9 final

- changelog.d/2421.misc.rst
- setup.cfg
> Add Python 3.9 trove classifier to the metadata

- CHANGES.rst
- changelog.d/2430.doc.1.rst
- changelog.d/2430.doc.2.rst
- docs/index.rst
This change corrects a few typos in Sphinx docs that haven't been caught
by the new strictness settings because of the race conditions in CI runs
that happened before the strictness PR merge.
> Fix sphinx strictness-related failures

- .github/pull_request_template.md
$sbj. This is necessary because the document has been moved in PR #2426.
> 📝 Update devguide links in the PR template

- CHANGES.rst
This change injects change categories into the static changelog using the
historic data from Git as a follow-up for
https://github.com/pypa/setuptools/pull/2399#issuecomment-711014643.
I'm not sure if the script I used for the first data extraction step is
useful in the repo so I'm not enclosing it but you can find it attached
to https://github.com/pypa/setuptools/pull/2399#issuecomment-711104367.
[PR docs]:
> Reconstruct changelog with categories from history

- docs/conf.py
- docs/deprecated/distutils/apiref.rst
- docs/deprecated/distutils/configfile.rst
- docs/deprecated/distutils/examples.rst
- docs/deprecated/distutils/extending.rst
- docs/deprecated/distutils/introduction.rst
- docs/deprecated/distutils/setupscript.rst
This change corrects references to nowhere in the distutils docs
by pointing some of them to proper locations (like docs.python.org)
and allowing others to stay unlinked.
[PR docs]:
> Fix refs in distutils sphinx docs

- .github/workflows/python-tests.yml
This change effectively makes broken GHA work. They were broken because they
pinned old action versions that used a mechanism for setting env vars that
is now deprecated.
[PR docs]:
> Upgrade GHA actions using deprecated env mechanism

- docs/userguide/quickstart.rst
https://setuptools.readthedocs.io/en/latest/userguide/quickstart.html today reads
> The change is driven under 517.
and I think that should be "PEP 517".
> s/517/PEP 517/

- docs/userguide/quickstart.rst
Quotes in the name and packages field causes an "Invalid distribution name or version syntax" if you follow this quickstart guide directly. pep517.build also requires you to specify the directory.
Removes quotes, adds a "." to the build invocation
Closes #2448
> Fixes syntax issues in quickstart (#2448)

- .github/workflows/python-tests.yml
This change gets rid of `set-env` and `add-path` workflow commands from GHA
because they've been deprecated due to a CVE.
[PR docs]:
> Fix all deprecated set-env and add-path uses @ GHA

- docs/pkg_resources.rst
See https://setuptools.readthedocs.io/en/latest/pkg_resources.html#entry-points
`For more details, see the [setuptools documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins).`
The link's target is orphaned, and the link itself also does not render correctly (using markdown in a restructured text file)
> fix broken link to entry-points details

- changelog.d/2471.misc.rst
- setuptools/tests/test_integration.py
In a PEP 517 world without distutils, packagers will need to find another way to build and supply the dependencies.
Fixes #2471.
> Remove tests guaranteeing that (vendored) dependencies can be installed without setuptools.

- changelog.d/2487.misc.rst
- pkg_resources/tests/test_resources.py
- setuptools/tests/fixtures.py
- setuptools/tests/test_develop.py
- setuptools/tests/test_easy_install.py
- setuptools/tests/test_egg_info.py
- setuptools/tests/test_msvc.py
- setuptools/tests/test_virtualenv.py
The latest pytest deprecates `pytest.yield_fixture` in favor of 
`pytest.fixture` [1]. The changelog [2] says that both are the same.
[1] https://github.com/pytest-dev/pytest/pull/7988
[2] https://docs.pytest.org/en/stable/changelog.html#pytest-6-2-0-2020-12-12
[PR docs]:
> Fix tests with pytest 6.2

- docs/build_meta.rst
Docs update to recommend PyPA build instead of pep517.build.
Closes #2503
> docs: recommend pypa build instead of pep517.build

- changelog.d/2493.change.rst
- pkg_resources/__init__.py
Fixes https://github.com/pypa/setuptools/issues/2493
As I said in the issue,
> As for the calling of load_module in `pkg_resources.__init__`, it seems to me that the only purpose of the call is to ensure the module is loaded, so that its `__path__` can be fixed up using `_rebuild_mod_path`. The call uses the default loader.
>
> So, it could be replaced by `importlib.import_module(packageName)`. From the load_module docs, the only thing it does in addition to what import_module does is reloading the module if it already exists. To me, that seems like an unintended side effect.
But I could also be off; the docs are written for implementing of loaders, not for calling them. …
> Avoid deprecated load_module() in pkg_resources namespace delaration

- docs/setuptools.rst
This is a minor docs edit to suggest PyPA-build instead of pep517.build, which is no longer intended as a public interface. See https://github.com/pypa/packaging.python.org/issues/770 (and others)
Edit: or more recently, https://github.com/pypa/setuptools/pull/2504 (Forgot it was in the same repo :flushed:)
> fix: suggest PyPA build instead of pep517.build

- .flake8
- pkg_resources/__init__.py
- setuptools/archive_util.py
- setuptools/command/bdist_egg.py
- setuptools/command/easy_install.py
- setuptools/command/egg_info.py
- setuptools/dist.py
- setuptools/glob.py
- setuptools/installer.py
- setuptools/msvc.py
- setuptools/package_index.py
- setuptools/ssl_support.py
flake8 can check code for complexity, it's the best practice to enable it.
This change makes sure to gate overly complex code guiding the contributors
to make it simpler when necessary.
It also disables the check in some places while fixing the others. I've only
simplified things that are easy to address and those changes can be easily
cherry-picked separately.
Ref: https://github.com/jaraco/skeleton/issues/34
[PR docs]:
> Enable McCabe complexity check in flake8

- changelog.d/2481.change.rst
- pkg_resources/extern/__init__.py
- setuptools/extern/__init__.py
Fixes https://github.com/pypa/setuptools/issues/2481
_(See [documentation][PR docs] for details)_ -- TODO
[PR docs]:
> Define create_module()/exec_module() in VendorImporter

- setup.cfg
Singular `license_file` is deprecated since wheel v0.32.0.
Refs:
* https://wheel.readthedocs.io/en/stable/news.html
* https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file
[PR docs]:
> Use license_files instead of license_file in meta

- .flake8
This option allows adding extra ignored rules to the default list
instead of replacing it.
The default exclusions are: E121, E123, E126, E226, E24, E704,
W503 and W504.
Refs:
* https://github.com/pypa/setuptools/pull/2486/files#r541943356
* https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-extend-ignore
* https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-ignore
* #2501
* https://github.com//skeleton/issues/28
[PR docs]:
> Use `extend-ignore` in flake8 config

- docs/userguide/entry_point.rst
In __init__.py the function helloworld() was defined, but everywhere else, hello_world() is called. Rename this function so that it is consistent with the naming in the rest of the file.
Closes 
[PR docs]:
> Fix code typo in entry_point.rst

- .flake8
This PR gets rid of the invalid ignore entries in the flake8 config. They were introduced in https://github.com/pypa/setuptools/commit/313ac58f51c6ef92170647c4cc8626043f68a26b while being moved from the pytest config. The correct flake8 syntax is `per-file-ignores` with colon-separated entries.
I'm pretty sure this never worked.
Also, `setuptools/site-patch.py` doesn't even exist anymore + `setuptools/py*compat.py` matches `setuptools/py34compat.py` that doesn't generate any violations meaning that introducing the correct `per-file-ignores` is currently unnecessary.
Refs:
* https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-per-file-ignores
* #2501 …
> Fix misplaced/mistyped per-file-ignores in flake8

- .flake8
This makes sure that flake8's defaults are in use. Specifically, it
excludes `.tox/` dir that is known to contain a lot of files in nested
folders that are not supposed to be linted.
Refs:
* https://github.com/pypa/setuptools/issues/2501#issuecomment-749144396
* https://github.com/pypa/setuptools/pull/2486/files#r546877674
* https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-extend-exclude
* https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-exclude
Ref #2501.
[PR docs]:
> Migrate to `extend-exclude` in flake8 config

- docs/build_meta.rst
Fix a minor spelling mistake that I found while reading the ``build_meta.rst`` docs online.
[PR docs]:
> docs (build_meta): fix spelling mistake

- changelog.d/1390.change.rst
- setuptools/dist.py
Quick fix for #1390.
This surgical fix addresses the reported and most common validation failure reported in that issue while a more complete solution is developed in pypa/packaging#147.
No tests are added, though I tested the behavior manually:
```
setuptools master $ .tox/python/bin/python -c "import setuptools; setuptools.setup(description='a\\nb')" egg_info
running egg_info
writing setuptools.egg-info/PKG-INFO
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/jaraco/code/public/pypa/setuptools/setuptools/__init__.py", line 153, in setup
return distutils.core.setup(**attrs)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
dist.run_commands()
File …
```
> Description cannot contain a newline.

- changelog.d/1390.misc.rst
- setuptools/dist.py
> Repair Descriptions with newlines and emit a warning

- changelog.d/2459.change.rst
- pyproject.toml
- pytest.ini
- setup.cfg
- setuptools/tests/fixtures.py
- setuptools/tests/test_build_meta.py
- setuptools/tests/test_distutils_adoption.py
- setuptools/tests/test_virtualenv.py
This is a demo showing how using pytest-xdist affects the test runs.
Resolves #2458
Comparing before/after, this patch makes the jobs run 2x faster in the CI and 4x faster locally.
|                    |        main        |      this PR      |
|--------------------|--------------------|-------------------|
| py36/ubuntu-latest | 240.99s  (0:04:00) | 137.93s (0:02:17) |
| pypy3/macos-latest | 1642.34s (0:27:22) | 732.48s (0:12:12) |
[PR docs]:
> Parallelize the test runs via pytest-xdist

- changelog.d/2537.breaking.rst
- setuptools/installer.py
- setuptools/tests/test_easy_install.py
- setuptools/tests/test_virtualenv.py
This feature has been deprecated since the introduction of pip-based fetch_build_eggs.
> Remove support for easy_install-based downloads for fetch_build_eggs

- changelog.d/2545.breaking.rst
- setup.py
- setuptools/command/bdist_egg.py
- setuptools/command/easy_install.py
- setuptools/tests/test_bdist_egg.py
> Remove eggsecutable

- changelog.d/2544.breaking.rst
- easy_install.py
- setup.cfg
- setup.py
- setuptools/command/easy_install.py
- setuptools/tests/test_easy_install.py
- setuptools/tests/test_namespaces.py
> Remove easy_install script and module.

- changelog.d/2573.change.rst
- setup.cfg
- setuptools/command/upload_docs.py
- setuptools/tests/requirements.txt
- setuptools/tests/test_sphinx_upload_docs.py
Closes #1060
Sphinx now uses `builder_target_dirs` in replacement of `builder_target_dir`  https://github.com/sphinx-doc/sphinx/blob/3.x/sphinx/setup_command.py#L143-L145. This fix will set the `target_dir` in `upload_docs` to the path of the html builder. 
Note: `Upload_docs` was restored support for sites other than PyPi as noted here: https://github.com/pypa/setuptools/blob/e1ffc2abbae4f2aa78dd09ee9827d754b7702b7b/CHANGES.rst#v3610
[PR docs]:
> Fix error uploading Sphinx doc with upload_docs. Fixes #1060

- docs/setuptools.rst
The [former developer's guide](https://setuptools.readthedocs.io/en/latest/setuptools.html) in `setuptools.rst` has been updated, so that it points the user to the [new developer's guide](https://setuptools.readthedocs.io/en/latest/userguide/index.html) in `userguide/index`.
Closes #2456 
[PR docs]:
> Include link to new developer guide in doc. Fixes #2456

- changelog.d/1937.breaking.rst
- changelog.d/1937.change.rst
- setuptools/dist.py
- setuptools/tests/test_config.py
Closes #1937
To address the bug of entry point names being made lower-case by Setuptools, this fix preserves case-sensitivity of keys in `setup.cfg` by changing`ConfigParser` to become case-sensitive. Edit: by extension this will also address any issues about keys in `setup.cfg` not retaining case-sensitivity such as in #2480
[PR docs]:
> Fix case sensitivity of entry point names and keys in setup.cfg. Fixes #1937

- changelog.d/2570.change.rst
- setuptools/config.py
- setuptools/tests/test_config.py
> Correctly parse cmdclass in setup.cfg. Fixes #2570

- changelog.d/1932.change.rst
- setuptools/dist.py
- setuptools/tests/test_dist.py
Closes  #1932
`Dist.check_specifier` verifies that the specifiers are valid and raises `DistutilsSetupError` if found invalid, however in the situation that the specifier is a non-string (e.g. a list with a string element) it would fail with an `AttributeError` because `SpecifierSet` from _vendor/packaging will assume that the specifier is a string. This fix will change `check_specifier` to handle the `AttributeError` by raising `DistutilsSetupError` when the situation of a non-string specifier occurs. 
[PR docs]:
> Handle AttributeError by raising DistutilsSetupError in check_specifier. Fixes #1932

- docs/conf.py
- docs/userguide/quickstart.rst
Docs update to recommend PyPA build instead of pep517.build (see https://github.com/pypa/pep517/issues/91). Similar to #2504 but for docs/userguide/quickstart.rst
> quickstart: recommend PyPA build instead of pep517.build

- changelog.d/2584.doc.rst
- docs/conf.py
- docs/requirements.txt
- docs/userguide/dependency_management.rst
- docs/userguide/package_discovery.rst
- docs/userguide/quickstart.rst
- setup.cfg
Closes #1699
Add the [sphinx-inline-tabs](https://github.com/pradyunsg/sphinx-inline-tabs) extension to allow tabbed containers for comparing `setup.py` and `setup.cfg`. The tabs works even when JS is disabled. This PR also replaces instances of adjacent code-blocks with the new extension. 
However, I wasn't sure if there was an issue with the default styling. It currently looks like this: 
The only thing that stood out and possibly needed overriding was the accent color of the tabs.
[PR docs]:
> Add mechanism for comparison of setup.py and its equivalent setup.cfg

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
This change makes the submitted GitHub issue structure predictable. The result of the submitted issue forms is saved as Markdown and can be freely edited later. The validation rules are only enforced on the initial issue creation.
Docs: https://gh-community.github.io/issue-template-feedback/structured/
I've made a demo repo with the configs from this PR. Check it out!
Resolves #2556
N/A
> Introduce issue forms in the repo

- changelog.d/2595.misc.rst
- setuptools/dist.py
- setuptools/tests/test_config.py
Closes #2595
This change limits the scope of the dash deprecation warning to sections which Setuptools/distutils uses in `setup.cfg` 
~~- [ ] Changes have tests~~ Change was tested locally
[PR docs]:
> Reduce scope of dash deprecation warning. Fixes #2595

- changelog.d/2608.change.rst
- setuptools/build_meta.py
- setuptools/tests/test_build_meta.py
Previously, when `build_sdist` or `build_wheel` were unable
to build a distribution (and were therefore unable to find the
distribution file), they would throw a
ValueError: not enough values to unpack (expected 1, got 0)
which did not offer any clues as to where the issue might lie.
[PR docs]:
> build_meta: produce informative error when a dist is not found

- .readthedocs.yml
- docs/requirements.txt
- setup.cfg
Now that Setuptools builds from git source without a bootstrap step, reset RTD config to match skeleton and rely on package metadata for docs build requirements. Eliminates duplication.
[Tested in this build](https://readthedocs.org/projects/setuptools/builds/13360943/).
> Align RTD config with skeleton

- setup.cfg
This change reverts the workaround for installing a proper version of `sphinx-inline-tabs` since @pradyunsg published the new release today.
Fixes #2614
[PR docs]:
> Use `sphinx-inline-tabs` from PyPI in sphinx docs

- setuptools/tests/test_virtualenv.py
pip changed its default branch to `main` which caused a test case to fail.
[PR docs]:
> Test - Fix url for pip download

- docs/userguide/quickstart.rst
Fix a small typo in the 'Basic Use' example of the Quickstart section of the User Guide.
> Fix typo in setup.py example in quickstart guide.

- changelog.d/2620.breaking.rst
- changelog.d/2620.change.rst
- changelog.d/2620.deprecation.rst
- changelog.d/2620.doc.rst
- docs/references/keywords.rst
- docs/userguide/declarative_config.rst
- setuptools/command/sdist.py
- setuptools/tests/test_egg_info.py
- setuptools/tests/test_manifest.py
- Add support for glob patterns in `license_file` and `license_files` options.
- Add default patterns if neither is specified to match behavior of `bdist_wheel`.
https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file
- Added deprecation warning if `license_file` file is used. `license_files` is a full replacement.
- Added additional documentation for the `license_files` option.
The implementation is similar to the one used by `wheel`: [wheel/bdist_wheel.py](https://github.com/pypa/wheel/blob/41b375ef33e3368f6f58c13f9649491d01c2ba5e/src/wheel/bdist_wheel.py#L410-L435)
Closes #2616
[PR docs]: …
> License_files improvements

- changelog.d/2632.change.rst
- pkg_resources/extern/__init__.py
- setuptools/extern/__init__.py
This change makes the import warning emitted by Python 3.10 disappear
but implementing the hook that is supposed to replace the old import
mechanism.
Refs:
* https://bugs.python.org/issue42134
* https://bugs.python.org/issue43540
* https://github.com/pypa/setuptools/issues/2632#issuecomment-815701078
Fixes #2632
[PR docs]:
> Implement `find_spec` in vendored module importers

- setuptools/dist.py
- setuptools/tests/test_dist.py
Refactor `read_pkg_file` from `setuptools/dist.py` in preparation for #2628, see https://github.com/pypa/setuptools/pull/2628#discussion_r610941513
Additionally added `rfc822_unescape` function to reverse escaping which is applied to the `Description` field.
https://packaging.python.org/specifications/core-metadata/#description
/CC: @webknjaz 
[PR docs]:
> Refactor ``read_pkg_file``

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/documentation-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
This change drops deprecated options from the issue forms schema files.
@jaraco this must be merged ASAP to reenable the forms.
> Drop deprecated `issue_body` from the forms

- changelog.d/2644.misc.rst
- setuptools/tests/server.py
Set daemon attribute instead of using setDaemon method that was deprecated in Python 3.10
Closes #2643 
[PR docs]:
> Set daemon attribute instead of using setDaemon method that was deprecated in Python 3.10

- changelog.d/2654.misc.rst
- towncrier_template.rst
This change fulfills the expectation of the recent Towncrier versions that the changelog version title is generated within the corresponding Jinja2 template.
Ref: https://github.com/pypa/pip/issues/9815
[PR docs]:
> Make changelog tmpl compatible w/ new Towncrier

- _distutils_hack/__init__.py
- changelog.d/2664.misc.rst
There is new message:
> The distutils.sysconfig module is deprecated, use sysconfig instead
> Relax the distutils deprecation regex

- docs/userguide/quickstart.rst
The first `setup.cfg` example in the quickstart lacks indentation of the `install_requires` declaration: 
Not sure if it's valid or not, but it's certainly hard to visually parse. 
Later on it's better indented: 
This adjusts the first example to add the indentation.
> Corrected indent in setup.cfg example.

- docs/userguide/quickstart.rst
This link on [the quickstart page](https://setuptools.readthedocs.io/en/latest/userguide/quickstart.html#python-packaging-at-a-glance) is broken: 
The implicit link target that should have been created from the title was not
being detected correctly. This was causing the link to be interpreted as an
external hyperlink reference, resulting in a 404 in the rendered docs.
Adding the explicit target and `ref` allows the link to resolve correctly.
I don't think these apply 🤔
[PR docs]:
> Fixed quickstart packaging resources hyperlink.

- changelog.d/2641.change.rst
- setuptools/dist.py
- setuptools/tests/test_dist.py
- setuptools/tests/test_egg_info.py
`setuptools` should always try to use the latest supported metadata version when writing the `PKG-INFO` file.
[PR docs]:
> Always use latest metadata version for PKG-INFO

- changelog.d/2650.misc.rst
- docs/conf.py
- docs/history.rst
- setup.cfg
The recent towncrier release now requires a `{{ top_line }}` variable in the template (as discovered in https://github.com/pypa/pip/issues/9815). Without this change, the changelog updates will have no title when the new Towncrier is used and this will happen sooner or later because it's unpinned in the deps.
Also, besides fixing that problem above this change integrates an extension for showing the upcoming release change notes in the Sphinx docs whenever standalone fragments are present in the tree.
Blocked by: https://github.com/pypa/setuptools/pull/2651.
[PR docs]: …
> Show not-yet-released change notes in Sphinx docs

- changelog.d/2650.misc.rst
- docs/conf.py
- docs/history.rst
- setup.cfg
A reprise of #2650 with a fix for publishing clean release notes when no changes are pending.
> Publish draft change notes

- docs/userguide/declarative_config.rst
Since [v56.0.0](https://setuptools.readthedocs.io/en/latest/history.html#v56-0-0) / https://github.com/pypa/setuptools/pull/2620:
> The `license_file` option is now marked as deprecated. Use `license_files` instead.
So `license_file` (`str`) isn't _exactly_ the same as `license_files` (`list-comma`), but is it close enough to put it in this table? Would it need a note?
For example, if you have `license_file = LICENSE.txt`, you can replace that with `license_files = LICENSE.txt` 
- [n/a] News fragment added in [`changelog.d/`].
[PR docs]:
> Docs: Use license_files instead of license_file

- changelog.d/2645.breaking.rst
- changelog.d/2645.change.rst
- setuptools/command/egg_info.py
- setuptools/command/sdist.py
- setuptools/config.py
- setuptools/dist.py
- setuptools/tests/test_egg_info.py
- setuptools/tests/test_manifest.py
This PR adds the ``License-File`` field to the package metadata. Although not yet part of the official metadata spec, including this field will enable third party tools easier access to all included license files through `importlib.metadata`. This is especially useful if a file doesn't have an easily recognizable name or is in an unusual location.
`setuptools` already parses the `license_file` and `license_files` options and cross-references them with all project files to see which ones should be included. With this change, the result of that would be made available for others to use as well.
Closes #2631
--
For reference: [PEP 639](https://www.python.org/dev/peps/pep-0639/), currently still in a draft, plans to add the `License-File` field to the metadata spec, …
> Add ``License-File`` field to package metadata

- changelog.d/2604.doc.rst
- docs/userguide/declarative_config.rst
The documentation still states it is not though.
Closes:  #2603
Removed inaccurate statement
Added an example of the now supported feature.
Closes 
[PR docs]:
> Entrypoints in declarative config are now supported

- changelog.d/2692.change.rst
- setuptools/dist.py
globbing uses os.listdir() which returns order on disk which is unsorted.
Ultimately this leads to random ordering of License-File entries in PKG-INFO
and means the resulting output isn't deterministic.
Adding a sort fixes that. Switch to glob instead ot iglob since sorted()
removes the benefit of an iterator.
https://github.com/pypa/setuptools/issues/2691
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Closes 
[PR docs]:
> setuptools/dist: Fix reproducibility issue by sorting globbing

- .github/workflows/main.yml
- tox.ini
Added minimal configuration for codecov.
Closes #2642 
> Adding codecov configuration

- .github/workflows/main.yml
In #2693, I recommended to remove the `gcov` exclusion. When I did, I believe that the error message was modest and ignorable. It can't possibly be a good design that every non-C program is meant to add this line to their project. Let's keep it simple and rely on defaults where possible. Doing so would make this technique more applicable to other projects too.
> Remove gcov exclusion. Defaults are fine.

- changelog.d/2722.change.rst
- setuptools/command/build_ext.py
- setuptools/tests/test_build_ext.py
Adds an environment variable SETUPTOOLS_EXT_SUFFIX to override the suffix inferred from the host Python runtime.
Closes #2722
[PR docs]:
> Fixes #2722 Adds an environment variable SETUPTOOLS_EXT_SUFFIX

- setuptools/command/easy_install.py
The external link below is broken: https://setuptools.readthedocs.io/en/latest/easy_install.html
This PR fixes broken links in easy_install.py
[PR docs]:
> Fix broken external links in easy_install.py

- docs/setuptools.rst
Minor edit to setuptools docs on PEP 517
Removed a repeated part of the sentence in the setuptools docs. Does not touch any code.
> Remove repeated information in same sentence

- changelog.d/2746.doc.rst
- docs/userguide/dependency_management.rst
> add python_requires example

- changelog.d/2765.patch.rst
- setuptools/dist.py
...~~for a year~~ to avoid issues with older Setuptools. Fixes #2765.
> In Distribution.finalize_options, suppress known removed entry points

- changelog.d/2769.misc.rst
- setup.cfg
- setuptools/dist.py
> Fail fast when use_2to3 is supplied.

- .github/workflows/main.yml
- .gitignore
- changelog.d/1988-change.rst
- pytest.ini
- setuptools/command/bdist_rpm.py
- setuptools/tests/test_bdist_deprecations.py
Similar to https://github.com/pypa/setuptools/pull/2040, deprecate `bdist_rpm`.
For #1988.
---
Also some test/CI improvements (please let me know if these should be in another PR):
* Ignore a generated file from running tox locally
* CI: test slower PyPy3 first, to make full use of parallel jobs to finish faster
* CI: turn on pytest colours for GitHub Actions logging, makes it more readable
[PR docs]:
> Deprecate bdist_rpm

- changelog.d/2785-change.rst
- setuptools/command/easy_install.py
`configparser`: replace deprecated `readfp` with `read_file`, deprecated since Python 3.2 and potentially being removed in Python 3.11 (due for release October 2022).
* https://bugs.python.org/issue45173
[PR docs]:
> configparser: replace deprecated readfp with read_file

- docs/userguide/quickstart.rst
It seems that the content of the "Development Mode" page is already stable, so I added a link to it in the "`setuptools` Quickstart" page.
Generate the documentation with tox (build finished with problems, 2 warnings):
<details>
<summary>console output</summary>
```console
$ python3 -m tox -e docs
docs create: /home/ubuntu/setuptools/.tox/docs
docs installdeps: sphinx@git+https://github.com/sphinx-doc/sphinx; python_version>="3.10"
docs develop-inst: /home/ubuntu/setuptools
docs installed: alabaster==0.7.12,attrs==21.2.0,autocommand==2.2.1,Babel==2.9.1,backports.entry-points-selectable==1.1.0,beautifulsoup4==4.10.0,black==21.8b0,certifi==2021.5.30,cffi==1.14.6,charset-normalizer==2.0.4,click==8.0.1,click-default-group==1.2.2,contextlib2==21.6.0,coverage==5.5,cryptography==3.4.8,dataclasses …
```
> Docs: add a link to the "Development Mode" page in "`setuptools` Quickstart"

- changelog.d/2796.change.rst
- setuptools/_distutils/command/build_ext.py
- setuptools/_distutils/command/install.py
- setuptools/_distutils/sysconfig.py
- setuptools/_distutils/tests/test_sysconfig.py
- setuptools/_distutils/tests/test_unixccompiler.py
- setuptools/_distutils/unixccompiler.py
- Prefer sysconfig.python_build
- adopt more standard schema for pypy3.8 (#51)
- Support overriding ranlib on macOS with env var
- override ldshared on non-macos platforms too if CC is overriden
- Split CC to make sure we get the correct basename of the compiler
- Use shlex
Closes 
[PR docs]:
> distutils 02e9f65ab0

- changelog.d/2800.change.rst
- setuptools/command/sdist.py
Controlling the file ownership recorded in tar archives is useful for those striving towards reproducible builds, as discussed in #1893. These options are already understood by `distutils.command.sdist.sdist`, so just need to be accepted by `setuptools.command.sdist.sdist` to be propagated.
I didn't see any tests of the adjacent `sdist` options such as `--keep-temp` or `--dist-dir`, so as the change is to data only and effectively just forwards to already existing distutils code, I haven't added any additional tests. If there is somewhere appropriate to add a new test, please recommend where and I will add something appropriate. A similar comment applies to documentation.
Closes #1893. …
> sdist: Accept -u/--owner and -g/--group options

- docs/userguide/distribution.rst
"Above" here refers to a section further down the page.
I guess the sections may have been moved around at some point? 
That, or someone wrote it upside down, anyway this fixes the direction for most right-side-up readers :)
[PR docs]:
> fix typo: above -> below

- docs/development/developer-guide.rst
In the developer-guide [Paver] is very briefly mentioned.
The purpose of this change is to expand a little bit more the text to provide context and help the potential contributors find their way.
A URL reference and a short description for what is [Paver] were added to the developer-guide.
Closes #2834 
Sorry for deviating a little bit of the procedure in the [PR docs]. These are the reasons behind it:
- Since it is a doc-only change, it is difficult to add tests...
- I felt like adding a news fragment was unnecessary (it is just a small change in the docs to clarify a particular aspect, and does not change the way setuptools work). But I could add one if the maintainers prefer...
Please let me know if I could improve this PR or do things …
> [Docs] Add reference and short description for Paver

- changelog.d/2932.doc.1.rst
- changelog.d/2932.doc.2.rst
- docs/userguide/declarative_config.rst
According to the following references:
- https://setuptools.pypa.io/en/latest/references/keywords.html
- https://packaging.python.org/guides/distributing-packages-using-setuptools/#package-data
the usage of ``data_files`` is deprecated.
Therefore we should avoid having it in the main configuration example for declarative config to avoid causing confusion among users.
- Removed ``data_files`` from example
- Change the type of the ``data_files`` option from ``dict`` to ``section`` (to match previous example - by looking at the [config module]( https://github.com/pypa/setuptools/blob/4bce6d5a30accecc848d8e7f0dabd212bfea9475/setuptools/config.py#L743) that also seem to be the case).
- Added a note about deprecation and a link to the data files support docs.
Closes #2832 
_(See …
> [Docs] Remove data_files from declarative config example

- changelog.d/2497.change.rst
- pkg_resources/__init__.py
- pytest.ini
> Deprecate LegacyVersion

- CHANGES.rst
Fix a typo in the History changelog.
https://setuptools.pypa.io/en/latest/history.html#v58-4-0
Should be https://github.com/pypa/setuptools/issues/2832 not https://github.com/pypa/setuptools/issues/2932. 
[PR docs]:
> Docs: Fix typo in History

- CHANGES.rst
Fix a typo in `CHANGES.rst`.
The line should have linked #2846, but it linked #2486 (middle two digits transposed) instead.
> Fix wrong issue number in CHANGES.rst

- changelog.d/2856.deprecation.rst
- setuptools/command/egg_info.py
- setuptools/tests/test_sdist.py
This PR replaces the log messages introduced in #2849 about using custom commands that inherit directly from distutils classes, with an actual deprecation warning.
The main advantage of this approach is that warnings can be filtered.
Including this deprecation in the changelog is also positive.
Closes #2856
[PR docs]:
> Deprecate support for commands inheriting from distutils

- changelog.d/2698.change.rst
- changelog.d/2698.doc.1.rst
- changelog.d/2698.doc.2.rst
- docs/deprecated/distutils-legacy.rst
- docs/userguide/extension.rst
- setuptools/errors.py
As stated in #2698, exposing `distutil.errors` via the `setuptools` module might facilitate people that want to tackle the migration motivated by PEP 632.
These exceptions might appear when customising commands like `build_py` and `build_ext`, and there are examples of projects explicitly checking them in the original issue.
This PR re-exports *most of* these functions via `setuptools.errors`.
`DistutilsGetoptError` and `DistutilsArgError` are left out, since they are related to the deprecated practice of running the `setup.py` script directly (I think).
I also removed the `"Distutils"` part of the name of some exceptions and added notes about the migration/replacements in the docs.
Closes #2698  …
> Re-export `errors` from `distutils`

- .github/workflows/main.yml
- changelog.d/2866.change.rst
- distutils/unixccompiler.py
- distutils/util.py
- Fix PyPy3.8 install locations
- distutils/ccompiler.py (CCompiler.has_function): Do not fail if self.outputdir is set
- distutils/tests/test_unixccompiler.py (UnixCCompilerTestCase.test_has_function): New
- .github/workflows/main.yml: Add integration testing with setuptools
- Use simple expression for resolution of outputdir.
> Incorporate pypa/distutils@f1b0a2b.

- .github/workflows/main.yml
- conftest.py
- pytest.ini
- setup.cfg
- setuptools/tests/test_distutils_adoption.py
- setuptools/tests/test_virtualenv.py
- tox.ini
This also makes the integration workflow added in https://github.com/pypa/distutils/pull/67 actually work.
Closes #2861 
[PR docs]:
> Test SETUPTOOLS_USE_DISTUTILS = stdlib, local on GH Actions

- changelog.d/2871.doc.rst
- docs/conf.py
- docs/userguide/quickstart.rst
$sbj. This was implemented in https://github.com/pypa/pip/pull/9547, in March.
Preview of the docs section that got updated: https://setuptools--2871.org.readthedocs.build/en/2871/userguide/quickstart.html#development-mode.
[PR docs]:
> Document that pip works with editable `setup.cfg`

- changelog.d/2880.misc.rst
- setup.cfg
- tox.ini
It seems that #2865 might have accidentally introduced a kind of dependency that is not accepted by PyPi:
```diff
[options.extras_require]
testing =
...
-	pytest-virtualenv>=1.2.7
+	pytest-virtualenv @ git+https://github.com/jaraco/pytest-plugins@distutils-deprecated#subdirectory=pytest-virtualenv
```
in `setup.cfg`.
PyPI forbids uploading packages with dependencies outside of PyPI (via URLs specs).
- Leave the previous pytest-virtualenv version in setup.cfg
- Overwrite the version using `deps` in tox.ini
Closes #2880 
Closes #2881
[PR docs]:
> Fix 2880, 2881 - Avoid depdencies with URLs in setup.cfg

- changelog.d/2877.change.rst
- pytest.ini
- setuptools/__init__.py
- setuptools/installer.py
Only deprecate the installation of these requirements, but still honor setup_requires in PEP 517 installers. Fixes #2877.
> Reduce scope of setup_requires deprecation

- changelog.d/2885.misc.rst
- pkg_resources/__init__.py
- pkg_resources/tests/test_resources.py
- pytest.ini
- setuptools/config.py
- setuptools/package_index.py
- Remove suppression of deprecation warning for LegacyVersion. Ref #2885.
- Fix sorting of filenames not to rely on LegacyVersion. Fixes #2885.
- Replace invalid local version with a valid form.
- Update config.ConfigMetadataHandler._parse_version not to rely on LegacyVersion.
- Suppress invalid versions when parsing in package_index. They will still be allowed for now as long as DeprecationWarnings aren't treated as errors.
Closes 
[PR docs]:
> Correct behavior under LegacyVersion when deprecation warnings are enabled.

- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/pull_request_template.md
- CHANGES.rst
- README.rst
- docs/deprecated/distutils/_setuptools_disclaimer.rst
- docs/deprecated/distutils/apiref.rst
- docs/development/developer-guide.rst
- pkg_resources/__init__.py
- setup.cfg
- setuptools/command/easy_install.py
Update links to point to the new docs URL: https://setuptools.pypa.io
And fix a typo in the feature request template.
- [n/a] News fragment added in [`changelog.d/`].
[PR docs]:
> Docs: Update setuptools.readthedocs.io to setuptools.pypa.io

- docs/pkg_resources.rst
Besides the name the function returns bytes.
> Reduce resource_string documentation confusion.

- _distutils_hack/__init__.py
- changelog.d/2906.misc.rst
- setuptools/tests/test_test.py
> In ensure_local_distutils, re-use DistutilsMetaFinder

- distutils/tests/test_unixccompiler.py
- Incorporate Fedora's distutil patch
- Expose _prefix_addition as a class property on install.
- Update comment for _distutils_system_mod.
- Load _prefix_addition attribute directly from sysconfig
- Revert "Update comment for _distutils_system_mod." as Fedora is not using that hook.
- Move _prefix_addition inline, so it's only configurable through sysconfig.
- Employ the TempdirManager to avoid creating 'scratch' in the test directory. Fixes #72.
> Merge with distutils at 8f2df0bf6

- changelog.d/2925.change.rst
- setuptools/_distutils/command/build_ext.py
- setuptools/_distutils/cygwinccompiler.py
- setuptools/_distutils/tests/test_version.py
- setuptools/_distutils/version.py
- setuptools/_distutils/versionpredicate.py
- setuptools/depends.py
- setuptools/dist.py
- setuptools/tests/test_setuptools.py
- sys._home -> sys.base_exec_prefix (pypa/distutils#42)
- Remove LooseVersion.__init__ as it's identical to super().__init__
- Mark Version classes as deprecated. (pypa/distutils#75)
- Suppress deprecation warnings in distutils test suite.
>  Sync with distutils 92082ee42c

- .github/workflows/main.yml
Add GH Actions job for testing on Cygwin
Closes 
[PR docs]:
> Add CI for Cygwin

- docs/conf.py
There are seven references to `distutils` commits that Sphinx renders as email addresses. I have added a rule to convert these commits into the proper GitHub URLs. I opted to explicitly encode `distutils` into the pattern because it is the only repository for which the documentation references commits. I felt that trying something more general would be more error prone, and this implementation at least solves the current problem. It might be worth revisiting if this documentation links to commits from other repositories.
Closes #2884
> Render `distutils` commit links properly in documentation

- changelog.d/2944.misc.rst
- setuptools/_distutils/command/install.py
- setuptools/command/easy_install.py
- Extract _select_scheme function to be re-used by Setuptools.
- In easy_install, re-use scheme selection from distutils if available.
- Add fallback support for distutils in stdlib.
Fixes #2938
> Add support for extended install schemes in easy_install.

- changelog.d/2960.misc.rst
- setuptools/_distutils/command/install.py
- Fix AttributeError when sysconfig does not supply platsubdir
- When headers are missing in a preferred scheme, use the default scheme as a fallback to resolve headers. Workaround for and fixes #88.
Closes 
[PR docs]:
> Sync with pypa/distutils@9867e2e42

- changelog.d/2963.change.rst
- setuptools/_distutils/_msvccompiler.py
- setuptools/_distutils/command/install.py
- setuptools/_distutils/cygwinccompiler.py
- setuptools/_distutils/tests/test_cygwinccompiler.py
- MinGW/Cygwin: Remove checks for ancient gcc/binutils
- Remove unused imports in cygwincompiler and the reliance on them in tests.
- Raise a `DeprecationWarning` for `gcc_version` attribute
- Move 'str' cast into the one place where it's needed and allow config_vars to have None values.
- Use mock.patch.dict to patch os.environ
Closes 
[PR docs]:
> Merge with pypa/distutils@a5af364910.

- setup.cfg
- tox.ini
It seems that Sphinx now supports Python 3.10, which means that we can
remove the dependency workaround.
- Updated docs/tests dependency on Sphinx to >=4.3.2
Closes 
[PR docs]:
> Remove workaround for test/CI dependency on Sphinx

- changelog.d/2974.change.rst
- setuptools/__init__.py
- setuptools/logging.py
- Add setuptools.log to supersede distutils.log. Ref #2973.
Closes #2973. Closes #2023.
[PR docs]:
> Enable logging through Python logging module

- _distutils_hack/__init__.py
- changelog.d/2983.misc.rst
- setup.py
> Restore 'add_shim' as the way to invoke the hook

- _distutils_hack/__init__.py
- changelog.d/2962.misc.rst
Prevents `_distutils_hack` finder shim from interacting with a possibly incompatible setuptools higher on sys.path
Closes #2957
[PR docs]:
> distutils shim should ignore setuptools on another path

- .github/workflows/main.yml
- changelog.d/2862.misc.rst
- conftest.py
- setup.cfg
- setuptools/tests/integration/helpers.py
- setuptools/tests/integration/test_pip_install_sdist.py
- tox.ini
As shown in https://github.com/pypa/setuptools/issues/2849, sometimes it is tricky to identify when a change introduces backward compatibility problems, specially considering that a lot o packages still rely on `distutils`.
Integration tests able to identify when such rare errors scenarios happen are very useful.
This PR introduces one specific type of integration tests: installing sdists using `pip`
Although very specific, this class of tests works very well for setuptools, since it exercises the API exposed by users that want to not only include binary extensions, but also customise their compilation process.
The configurations for pytest, tox and Github Actions were changed in such a way that integration tests will only run before a release (not on regular merge or push).
The selection …
> Add integration tests focusing on installing sdists via pip

- .github/workflows/main.yml
- .gitignore
- changelog.d/2968.misc.1.rst
- changelog.d/2968.misc.2.rst
- changelog.d/2968.misc.3.rst
- setup.cfg
- setuptools/tests/contexts.py
- setuptools/tests/environment.py
- setuptools/tests/fixtures.py
- setuptools/tests/integration/test_pip_install_sdist.py
- setuptools/tests/test_bdist_deprecations.py
- setuptools/tests/test_distutils_adoption.py
- setuptools/tests/test_setuptools.py
- setuptools/tests/test_virtualenv.py
- tox.ini
This change supersedes #2922.
As discussed in #2922, the `tmp_src` fixture copies the `.git` repository, which is error prone and may increase testing time.
I noticed that this fixture was used only in `test_virtualenv` and `test_distutils_adoption`, mainly to populate a virtual environment with the version of setuptools that is currently under test.
This PR proposes building sdist/wheel artifacts from the source tree and using them to populate these virtualenvs, instead of `pip install <setuptools directory>` or `python setup.py install/develop`. It also uses a lockfile approach discussed in the [`pytest-xdist` homepage](https://github.com/pytest-dev/pytest-xdist/blob/f9f8a765bae0d177bbecf4150db9853bf700554f/README.rst#making-session-scoped-fixtures-execute-only-once) to make these …
> [CI] Remove the need for the `tmp_src` fixture

- changelog.d/2952.misc.rst
- pavement.py
- pkg_resources/_vendor/packaging/LICENSE
- pkg_resources/_vendor/packaging/LICENSE.APACHE
- pkg_resources/_vendor/packaging/LICENSE.BSD
- pkg_resources/_vendor/pyparsing.LICENSE.txt
- setuptools/_vendor/more_itertools/LICENSE
- setuptools/_vendor/ordered_set.MIT-LICENSE
- setuptools/_vendor/packaging/LICENSE
- setuptools/_vendor/packaging/LICENSE.APACHE
- setuptools/_vendor/packaging/LICENSE.BSD
- setuptools/_vendor/pyparsing.LICENSE.txt
As pointed out by #2950, it is probably a good idea to keep the license
files for the vendored dependencies.
This is done by changing the `pavement.py` tasks:
- In the case of vendored packages, the license files are moved to the package folder
- In the case of vendored modules, the license files are renamed to:
`f"{module.basename()}.{license_file.basename()}"`
Closes #2950 (probably? not sure if legally that is enough)
[PR docs]:
> Change vendoring script to preserve license files

- setuptools/tests/integration/test_pip_install_sdist.py
Numpy now uses a version cap for setuptools in their `pyproject.toml`, which defies a bit the value of including it in the integration tests.
As revealed in a conversation with `numpy` maintainer, it seems that they don't plan to remove this cap (maybe only update it from time to time, if strictly necessary). Moreover they are also studying other build backends.
So I think that now the best thing to do would be stop trying to build numpy sdists with the current version of setuptools, otherwise we risk to break this test.
[PR docs]:
> Remove `numpy` sdists from integration tests

- changelog.d/2674.doc.rst
- docs/userguide/quickstart.rst
Quickstart guide has a section for additional resources on packaging in Python, but did not provide any links. Based on the discussion at #2674, this PR adds a link to Python Packaging User Guide.
Closes #2674
> docs/2674: packaging resources in quickstart guide

- exercises.py
- setup.cfg
- tox.ini
In order to measure and protect the performance of interpreter startup, add performance tests. Ref #3006.
> Capture performance of interpreter startup.

- _distutils_hack/__init__.py
- changelog.d/3006.change.rst
- pytest.ini
``_distutils_hack`` is imported by a ``.pth`` file at every start of a
Python interpreter. The import of costly modules like ``re`` and
``contextlib`` almost doubles the initial startup time of an
interpreter.
- replace ``contextlib`` with simple context manager and try/except
- replace ``re`` with simple string match
- move import of ``importlib`` into function body
- remove ``warnings.filterwarnings()``, which imports ``re``, too.
Fixes: #3006
Signed-off-by: Christian Heimes <christian@python.org>
Closes 
[PR docs]:
> Speedup startup of Python by importing less

- _distutils_hack/__init__.py
- changelog.d/2990.change.rst
- setuptools/tests/test_distutils_adoption.py
set origin so spec finding reports the correct location -- https://docs.python.org/3/library/importlib.html#importlib.machinery.ModuleSpec
Closes https://github.com/asottile/reorder_python_imports/issues/210
[PR docs]:
> set origin= for distutils.__spec__

- changelog.d/2918.misc.rst
- pkg_resources/__init__.py
https://github.com/pypa/setuptools/pull/1563 introduced a subtle bug in the fallback code for `pkg_resources` enumeration. The original code that only used `find_module` later accounts for a `None` loader return value (ie, the requested module couldn't be found), but the new code blindly dots into the return from `find_spec` (which can also be `None`) to grab its `loader`. When this occurs, it inadvertently trips the `AttributeError` that was supposed to be there for py2 loaders that don't implement `find_spec`, causing `find_module` to be called even on a py3-native loader. Loaders that still implement the deprecated 2.x methods will (correctly) return `None`, triggering the old fallback path, all is well. However, new loaders that don't implement `find_module` will blow up the …
> fix `pkg_resources` import failures w/ py3-only loaders

- _distutils_hack/__init__.py
- changelog.d/2993.misc.rst
Ref #3022. Fixes #2993.
Closes 
[PR docs]:
> Instead of detecting 'get-pip' during the import of pip, detect 'import setuptools'

- changelog.d/3026.misc.rst
- setuptools/_distutils/command/install.py
- setuptools/command/easy_install.py
- Trim excess indentation.
- Honor sysconfig variables in easy_install. Fixes #3026.
Closes #3026
[PR docs]:
> Honor sysconfig vars in easy_install

- setup.cfg
- setuptools/tests/test_setuptools.py
Add a new exclude pattern to `setup.cfg [options.packages.find]`.
This new exclude pattern should prevent any files contained in the tests directories to be added to the wheel.
Closes #3017
[PR docs]:
> Prevent test files from being included in setuptools own wheel

- _distutils_hack/__init__.py
- changelog.d/3031.misc.rst
> Suppress distutils replacement when building or testing CPython.

- .github/workflows/main.yml
Use the official GH action for installing cygwin instead of
going through choco.
See #3016
-----
The job is still disabled. I can re-enable it if wanted.
> CI/cygwin: use cygwin/cygwin-install-action instead of choco

- setuptools/logging.py
- setuptools/tests/test_logging.py
For some reason `distutils.log` module is getting cached in `distutils.dist` and then loaded again when we have the opportunity to patch it.
This implies: `id(distutils.log) != id(distutils.dist.log)`, and therefore the function `setuptools.logging.set_threshold` never gets called (instead the old version `setuptools._distutils.log.set_threshold` is used).
- Add a test case to ensure the correct verbosity level is set for logging
- Replace the cached `distutils.dist.log` with the "correct" patched module object.
Closes #3038
[PR docs]:
> Ensure log level is set correctly (and `setuptools.logging.set_threshold` is called)

- changelog.d/3056.docs.rst
- docs/build_meta.rst
- docs/userguide/dependency_management.rst
- docs/userguide/quickstart.rst
This dependency is exposed automatically by setuptools and the users do not need to declare it explicitly — it will be installed by PEP 517 front-ends automatically when building wheels.
[PR docs]:
> Stop mentioning `wheel` in the context of PEP 517

- changelog.d/3054.misc.rst
- pkg_resources/__init__.py
- setuptools/__init__.py
- setuptools/command/easy_install.py
- setuptools/extension.py
- setuptools/package_index.py
> Use super()

- changelog.d/2897.docs.rst
- docs/build_meta.rst
- docs/conf.py
Added instructions about wrapping `setuptools.build_meta` for customising the backend.
This is useful for dynamically specifying build requirements, according to PEP 517.
I believe this should be enough to close #2854.
Moreover by looking at the issues, I also have the impression that #1698 is already covered and could be closed.
[PR docs]:
> Docs: Add instructions about `build_meta` wrappers as alternative to dynamic `setup_requires`

- changelog.d/3057.change.rst
- setuptools/dist.py
Similar to `Download-URL`, `Home-page` is handled as an optional field by PyPI. No need to include it in the package metadata if it's unknown. This will better support packages which choose to specify all urls inside `project_urls`.
[pypa/warehouse - forklift/legacy.py](https://github.com/pypa/warehouse/blob/213fdf9dd849580ced0759b1dc16edac368ca955/warehouse/forklift/legacy.py#L520-L528)
Reading a missing field is also not an issue. `msg[field]` will return `None` in these cases.
https://github.com/pypa/setuptools/blob/d3124ac33e1407ced092deb2e8854471773786d4/setuptools/dist.py#L71-L76
[PR docs]:
https://setuptools.pypa.io/en/latest/development/developer-guide.html#maki …
> Don't include `Home-page` with UNKNOWN value

- setuptools/tests/contexts.py
- setuptools/tests/fixtures.py
> Rely on session context when building sdist and wheel

- changelog.d/3070.misc.rst
- setuptools/command/easy_install.py
`sysconfig.get_config_vars()` can return values which are not strings (including integers), but the current code assumes all values are strings. This results in an `AttributeError`. Adding a check for non-string values and skipping them avoids the error.
Closes #3063
[PR docs]:
> Skip non-string values from sysconfig.get_config_vars()
