pypa/setuptools

setup.py
Signed-off-by: Gabi Davar <grizzly.nyo@gmail.com>
=> bump certifi to 2016.2.28

docs/setuptools.txt
Hi,
I believe this could fix issue #445.
=> Update link to Resource Management API

setuptools/msvc9_support.py
- Fix issue #593
- Fix some forgotten "vcver" => "vc_ver" renames in previous commit.
- Fix PEP8 line length.
- Add comments on why I didn't followed PEP8 for some variables names (For eventual future contributors).
=> Issue #593 and other fixes

CHANGES.rst, setuptools/msvc.py
Add the new link to "Microsoft Visual C++ Build Tools" if MSVC14 is not installed.
=> Minor change : Link to MSVC14 Standalone

setuptools/package_index.py, setuptools/unicode_utils.py
This time comments adjacent to their relevant code.
=> Add missing blank line.

setuptools/dist.py, setuptools/tests/test_egg_info.py
Alternate implementation of #665
=> Also update the Metadata-Version when adding Requires-Python

setuptools/msvc.py
=> Fix regression in commit e404a4a

pkg_resources/__init__.py
by defining dist so there's something to delete
closes #702
=> fix NameError when initial working_set is empty

setuptools/msvc.py
Try to fix #694.
Wait result from issue before merging.
=> #694 Patch distutils._msvccompiler.library_dir_option

setup.py
=> bump certifi to 2016.8.8

tox.ini
- have tox pass env variables used by setuptools on windows.
=> fix tests on windows using tox

setuptools/command/build_ext.py
=> Use EXT_SUFFIX instead of SO for py_limited_api renaming

setuptools/monkey.py
=> Move msvc import to avoid a circular import

setup.py
=> certifi 2016.8.31

setuptools/command/sdist.py
=> Remove _add_defaults_data_files override

setup.py
I forgot to add 3.6 in https://github.com/pypa/setuptools/pull/925.
=> Update Python versions

docs/setuptools.txt, setuptools/config.py, setuptools/tests/test_config.py
=> Dropped support for classifiers subsection handling in setup.cfg

ez_setup.py
Useful for users of https://bootstrap.pypa.io/bootstrap-buildout.py
=> Deprecation message if not doing 'python ez_setup.py'

CHANGES.rst, setuptools/command/upload.py
=> In upload, infer the username using getpass.getuser()

setuptools/dist.py
This fixes: #997 
I didn't write a test because it's likely a test would pass because of imports elsewhere.
=> fixed incomplete import of packaging.specifiers and packaging.version

docs/setuptools.txt
=> Docs: notes on setup.cfg and ez_setup

.gitignore, tox.ini
=> Tox doc comments

setuptools/command/test.py
Fixes https://github.com/pypa/setuptools/issues/1032
=> Document -s to run single test

.travis.yml
This is aiming to improve safety of the PYPI publishing flow.
/cc: @jaraco 
P.S. If needed I may also add OS X support.
=> Run build stages (pipelines) in Travis CI config

setuptools/dist.py, setuptools/tests/test_egg_info.py
This reverts commit a3ec721ec1e70f1f7aec6c3349ad85b446410809.
My interpretation was wrong, fix #1099.
=> Revert "fix `install_requires` handling of extras"

setuptools/dist.py, setuptools/tests/test_egg_info.py
=> do not strip empty sections in `extras_require`

setuptools/command/test.py, setuptools/tests/test_easy_install.py, setuptools/tests/test_virtualenv.py
=> Fix `test` command handling of `extras_require`

setuptools/dist.py, setuptools/tests/test_config.py, setuptools/tests/test_egg_info.py
=> fix requires handling when using setup.cfg

setuptools/command/dist_info.py
The dist_info command did not say anything like other
commands did. This gives some more helpful information.
=> commands: dist_info: say something!

CHANGES.rst, setuptools/command/test.py, setuptools/tests/test_test.py
* fix tests discovery with Python 2
* fix tests running twice with Python 3 (fix #701).
=> Fix test command

CHANGES.rst, setuptools/tests/test_wheel.py, setuptools/wheel.py
=> fix `data_files` handling when installing from wheel

setuptools/command/easy_install.py, setuptools/tests/test_easy_install.py
Fix #1261.
Note: it looks like the latest nightly break the build on Travis.
=> Fix dry-run handling

setuptools/dist.py, setuptools/tests/test_egg_info.py
Resolves https://github.com/pypa/setuptools/issues/1292
=> Don't claim to provide the extra ''

.codecov.yml, .travis.yml, appveyor.yml, tests/requirements.txt, tox.ini
Coverage metrics work with tox locally, need to test it out with CI.
Resolves #1302.
=> Set up code coverage

setuptools/tests/test_wheel.py
Per @benoit-pierre's detective work on #1318, this should fix the failing test suite.
Fixes #1318.
=> Update wheel tests to reflect latest version

setuptools/pep425tags.py
fixes #1314 
See https://github.com/pypa/pip/issues/3383 and https://github.com/pypa/pip/pull/3399/commits/c67e3ba987de53f6cb08fb287d2dbb446e6a5574
=> pep425tags: turn warning into a debug log entry

README.rst
This shows the coverage of the master branch as measured by Codecov.
=> Add coverage badge to README

.github/pull_request_template.md, changelog.d/1355.misc.rst, docs/developer-guide.txt
Adding pull request template
Closes 1355
- [*] News fragment added in changelog.d.
=> Pull request template

netlify.toml
Tell Netlify how to build and publish the documentation preview for each pull request.
=> Generate doc previews for pull requests

changelog.d/1312.change.rst, changelog.d/1420.change.rst, docs/setuptools.txt, setuptools/__init__.py, setuptools/config.py, setuptools/tests/__init__.py, setuptools/tests/test_config.py, setuptools/tests/test_find_packages.py
Rename find_namepaces_ns to find_namespace_packages
Closes #1421
=> Rename find_namepaces_ns to find_namespace_packages

docs/pkg_resources.txt
add missing link to setuptools documentation
=> link to setuptools doc

docs/requirements.txt
=> Pin against sphinx 1.8.0 due to sphinx-doc/sphinx#5417.

changelog.d/1525.doc.rst, docs/easy_install.txt
=> Fix easy install warning #1525

setup.py
Officially support Python 3.7 in classifiers.
Closes #1528.
=> Officially support Python 3.7

docs/setuptools.txt
Closes #1522
No tests or fragment in changelog.d as this is a small change to documentation.
=> Update setup.cfg documentation to include data_files

changelog.d/1564.doc.rst, docs/setuptools.txt
Progress on #1535 
~~- [ ] Changes have tests~~
=> Document setup.cfg minimum version for version and project_urls

changelog.d/1499.change.rst, setuptools/package_index.py, setuptools/tests/test_packageindex.py
=> Remove use of splituser

setuptools/command/develop.py, setuptools/tests/test_packageindex.py
Fixes GH issue #1612, bug introduced in commit 0902f02d9d68f18
No news is required as this fixes a change introduced since the last version.
=> Import distribution in doctest

.mergify.yml
=> Only allow auto-merge PRs submitted by authorized users

docs/developer-guide.txt
=> Add documents on auto-merge

docs/developer-guide.txt, docs/setuptools.txt, setuptools/config.py, setuptools/pep425tags.py
=> Spelling fixes

setuptools/build_meta.py
Unifies common behavior using preferred idioms.
=> Refactor build_meta

tests/requirements.txt, tox.ini
=> tests: temporary pin pip to fix the Python 2.7 job

setuptools/tests/test_build_py.py
Reuse the existing `tmpdir_cwd` fixture.
=> tests: minor cleanup

changelog.d/1665.change.rst, setuptools/package_index.py
=> Ensure port is included in package-index

CHANGES.rst, changelog.d/1536.change.rst, changelog.d/1635.change.rst, changelog.d/1652.change.rst
Prepare release notes for version 40.8.0
=> Update changelog for version 40.8.0

README.rst
✨ 
* Consistent Styling
* Add Logos of CI services
* Shorten CI badge labels
* Reorder for better wrapping
- Not needed
- Not needed
=> Improve badges in README

changelog.d/1705.doc.rst, docs/setuptools.txt
This commit involves removing of the unwritten sections of the documentation which refer to deprecated things.
Closes #1701
=> Removed unwritten section of the documentation.

.travis.yml
Attempting to update the Travis configuration to use a newer version of `pypy2.7` by updating to xenial, per @webknjaz's suggestion. Not sure this will actually work, so I've marked it WIP.
Trying to debug or solve #1730
=> Update pypy in travis

CHANGES.rst, changelog.d/1664.change.rst, changelog.d/1675.change.rst, changelog.d/1705.doc.rst, changelog.d/1720.change.rst
Update changelog in preparation for the version 40.9.0 release.
=> Update changelog for version 40.9.0

CHANGES.rst
I was bumping in dead links a bit, so I git-logged them out of the way :smile:
- Update some dead old PR links to their commits counterpart
FTR because the project moved, the previous `PR`s are gone, therefore I've replaced them with commits instead.
=> Update super old CHANGES.rst dead links

setuptools/tests/test_build_meta.py
Add a unit test for the bug in issue #1671.
This test is now failing (xfail) and should be passing when the bug is fixed.
=> Add failing test for issue #1671 (ValueError when .whl is present)

.travis.yml
* preemptively switch to xenial as it will soon become the default: https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
* update PyPy 3 job to latest supported version (hopefully this will fix #1730)
=> Tweak Travis CI configuration

appveyor.yml, setuptools/tests/test_integration.py, tox.ini
Ignore distutils' warning: `Unknown distribution option: 'python_requires'`.
=> tests: fix_test_build_deps_on_distutils

changelog.d/479.change.rst, setuptools/command/build_ext.py, setuptools/command/install_lib.py
Partial resolution of #479 -- the other usage is a little more tricky and will require some more clever fixes
=> Fix some usage of deprecated `imp` module

setuptools/command/easy_install.py
Remove duplicate `'site_dirs'`.
=> minor cleanup

.travis.yml, changelog.d/1886.misc.rst
=> Add Python 3.8 final to Travis test matrix

changelog.d/1868.doc.rst, docs/development.txt, docs/formats.txt, docs/pkg_resources.txt, docs/setuptools.txt
In prevision of EasyInstall removal.
=> doc: drop most references to EasyInstall

changelog.d/1891.change.rst, setuptools/msvc.py
=> Fix code for detecting Visual Studio's version on Windows under Python 2.

tools/tox_pip.py, tox.ini
Work around buggy pip detection code for "pip.exe install/update pip ...".
=> tweak workaround for #1644

docs/setuptools.txt
fixes https://github.com/pypa/setuptools/issues/1943
=> Fix dead link

docs/setuptools.txt
This PR will make the following changes:
- fix some typos;
- remove the `python` command from `setup.py` calls;
- uniformise quotation marks.
=> Improve setuptools.txt

.github/workflows/python-tests.yml, .travis.yml, appveyor.yml, docs/conf.py, docs/developer-guide.txt, tools/tox_pip.py, tox.ini
…and simplifying all of the pipelines.
=> Bootstrap the environment in tox, allowing simple 'tox' to run tests.

.github/workflows/python-tests.yml, tox.ini
This is a follow-up for #1840 adding improvements that I've learned since it was first created.
=> Improve tests setup in GH Actions CI/CD workflow

changelog.d/1985.change.rst, setuptools/command/install_scripts.py
=> Fix install_scripts() if bdist_wininst is missing

tox.ini
=> Pin virtualenv to <20 as workaround for #1998.

docs/references/keywords.txt
parts of the efforts in #2093 
Created directory setuptools/docs/references and place ``keywords.txt`` from PR #1765  in it en bloc
=> Incorporate PR 1765's keywords.txt

changelog.d/2158.misc.rst, setuptools/__init__.py
=> Defer finalize options

docs/userguide/entry_point.txt
Step 6 on #2093
This user guide covers:
- console_script
- plugin support
- optional dependencies
=> Step 6 on 2093: userguide on entry points now available

.github/workflows/python-tests.yml
Like https://github.com/pypa/setuptools/pull/2248 but for GHA.
=> Test Python 3.9-dev on GitHub Actions

_distutils_hack/__init__.py, changelog.d/2316.change.rst
=> Fix issue with distutils warning

changelog.d/2310.change.rst, pkg_resources/_vendor/packaging/__about__.py, pkg_resources/_vendor/packaging/_compat.py, pkg_resources/_vendor/packaging/_structures.py, pkg_resources/_vendor/packaging/_typing.py, pkg_resources/_vendor/packaging/markers.py, pkg_resources/_vendor/packaging/requirements.py, pkg_resources/_vendor/packaging/specifiers.py, pkg_resources/_vendor/packaging/tags.py, pkg_resources/_vendor/packaging/utils.py, pkg_resources/_vendor/packaging/version.py, pkg_resources/_vendor/vendored.txt, setuptools/_vendor/packaging/__about__.py, setuptools/_vendor/packaging/_compat.py, setuptools/_vendor/packaging/_structures.py, setuptools/_vendor/packaging/_typing.py, setuptools/_vendor/packaging/markers.py, setuptools/_vendor/packaging/requirements.py, setuptools/_vendor/packaging/specifiers.py, setuptools/_vendor/packaging/tags.py, setuptools/_vendor/packaging/utils.py, setuptools/_vendor/packaging/version.py, setuptools/_vendor/vendored.txt
=> Update packaging to 20.4

appveyor.yml, changelog.d/2401.misc.rst
This basically enables AppVeyor UI to show test results.
Azure Pipelines already do this too.
=> Report test results in the AppVeyor UI

docs/userguide/package_discovery.rst
=> docs: editorial word fix

docs/userguide/development_mode.rst
The wording seemed backwards to me, so I made it a little clearer.
=> Clarify Development Mode first paragraph

docs/userguide/entry_point.rst
Added ini to the code block about syntax for entry points to make it visible. 
Closes #2562 
[PR docs]:
=> Add ini to display code block in doc

changelog.d/2553.doc.rst, docs/userguide/declarative_config.rst
Signed-off-by: Pablo Woolvett <pablowoolvett@gmail.com>
Closes 2553
[PR docs]:
=> docs(userguide): Marker example for extras_require

setuptools/tests/fixtures.py, setuptools/tests/test_develop.py
=> Add test demonstrating how site dirs can be added for discoverability

CHANGES.rst, changelog.d/README.rst, docs/pkg_resources.rst, docs/python 2 sunset.rst, docs/userguide/dependency_management.rst, docs/userguide/quickstart.rst, pkg_resources/_vendor/pyparsing.py, setuptools/_distutils/ccompiler.py, setuptools/_imp.py, setuptools/_vendor/pyparsing.py, setuptools/package_index.py, setuptools/tests/environment.py, setuptools/tests/test_easy_install.py, setuptools/tests/test_windows_wrappers.py
=> Fix misc. doc typos

setup.py
=> Remove 'wheel' from setup_requires.

docs/build_meta.rst
Fix a broken external link
[PR docs]:
=> Fix a broken external link

docs/userguide/entry_point.rst
Correct typo in docs
[PR docs]:
=> Correct typo (s/brakets/brackets/)

changelog.d/2792.doc.rst, docs/userguide/distribution.rst
Closes #2618. Document how the legacy versions and non-legacy versions are compared, and reference to PEP 440.
[PR docs]:
=> Document the version comparisons

CHANGES.rst
* confirparser -> configparser
* Add code formatting
- [n/a] News fragment added in [`changelog.d/`].
[PR docs]:
=> Fix typo and add code formatting

changelog.d/2954.misc.rst, setuptools/_distutils/command/install.py
=> Merge with pypa/distutils@eba2bcd310

_distutils_hack/__init__.py, changelog.d/2958.change.rst, setup.py, setuptools/tests/test_distutils_adoption.py
=> Add metadata finder once.

setuptools/tests/test_easy_install.py
This error was first reported in https://github.com/pypa/setuptools/commit/bfa75fc56d0bd47bd6c0edf9a0e579508c9fae9e#commitcomment-63663642
The approach taken here is to check for the '3.10' substring only if '3.1' is present.
Closes 
[PR docs]:
=> Fix failing test when user site-packages has no version number

.github/workflows/ci-sage.yml
Update the Sage portability CI: Fix `gentoo`, drop `centos-8`, add `centos-stream-8`, `centos-stream-9`
[PR docs]:
=> Ci sage update

changelog.d/3102.misc.rst, setuptools/_importlib.py
=> Workaround for older importlib_metadata.

setuptools/tests/test_virtualenv.py
As discussed in #3149, builds with setuptools will always try to
download `wheel`, therefore if the network is not available there is
little sense in testing those builds (they will fail).
- Skip `test_pip_upgrade_from_source` even if `pip` is not updated.
Closes #3149 
[PR docs]:
=> [CI] Disable test_pip_upgrade_from_source when network if off

CHANGES.rst
=> Fixed typos

changelog.d/3224.change.rst, setuptools/_distutils/command/build_scripts.py, setuptools/_distutils/command/check.py, setuptools/_distutils/tests/test_check.py
- Don't warn on false positive for author/maintainer's email
- 👹 Feed the hobgoblins (delint).
- Rewrite docstring for imperative voice and proper structure.
- Move 'updated_files' operation outside of if statement as it appears in both branches unconditionally.
- Extract method for copying a file.
- Remove outfiles, unused.
- Extract _change_modes and _change_mode functions.
- Rewrite the comment to match the implementation.
- Use 'shebang_' for pattern and match.
- Extract method to validate the shebang.
- Restore Setuptools compatibility.
- In build_scripts, open scripts as text. Fixes pypa/distutils#124.
Closes 
[PR docs]: …
=> Merge with distutils@e1d5c9b1f6

docs/userguide/dependency_management.rst
- A couple small wording / punctuation tweaks for readability.
[PR docs]:
=> Small wording tweaks for readability

setuptools/dist.py
Closes #3320
- [N] Changes have tests
- [N] News fragment added in [`changelog.d/`].
[PR docs]:
=> Fix typo which causes TypeError

docs/userguide/quickstart.rst
In the sentence "If you are experimenting with configuration using, or have version of..."
Closes 
[PR docs]:
=> Missing the word "pyproject.toml" in Quickstart.

docs/deprecated/commands.rst, docs/deprecated/distutils-legacy.rst, setuptools/config/_apply_pyprojecttoml.py, setuptools/logging.py, setuptools/tests/test_easy_install.py
=> fixed some spelling mistakes,

docs/userguide/package_discovery.rst
Small fixes and improvements to the package discovery guide.
Closes 
[PR docs]:
=> [Docs] package discovery guide: Small improvements and fixes

changelog.d/3305.doc.rst, docs/userguide/pyproject_config.rst
Add example of 'requires-python' and a comment re-iterating that these values are all defined in the PEP
Closes #3305 
=> #3305 Update doc example code

.github/workflows/main.yml
The changes here are based on the workaround discussed in: https://github.com/actions/checkout/issues/766
Closes #3408.
[PR docs]:
=> Add workaround for git problems in cygwin

.github/workflows/ci-sage.yml
Update system configurations tested by ci-sage.yml after https://trac.sagemath.org/ticket/33316
Closes #3389 
[PR docs]:
=> .github/workflows/ci-sage.yml: Update system configurations

docs/build_meta.rst, docs/setuptools.rst
This is a follow up on #3056.
- Remove `wheel` dependency from docs example
[PR docs]:
=> Remove `wheel` dependency from docs example

docs/userguide/quickstart.rst
=> type in quickstart.rst

docs/deprecated/commands.rst
=> docs: correct calling setuptools commands

changelog.d/3497.misc.rst, setuptools/command/editable_wheel.py, setuptools/tests/test_editable_install.py
* Fix typo
Closes: #3498
[PR docs]:
=> Fix typo in editable_wheel.py

changelog.d/3502.misc.rst, setuptools/command/editable_wheel.py, setuptools/tests/test_editable_install.py
=> Fix issue with editable install and single module packages

changelog.d/3529.doc.rst, docs/userguide/quickstart.rst
=> Docs: Clarify 'setup.py' support on Quickstart

docs/userguide/extension.rst
https://dictionary.cambridge.org/dictionary/english/bellow
=> Fix typo in docs/userguide/extension.rst

setup.cfg
This will make my life a little easier
=> Add changelog to project URLs

docs/userguide/ext_modules.rst
- Small fix for URL used in docs
[PR docs]:
=> Docs: fix url

.github/workflows/main.yml
Update codecov GHA to v3 (v1 is now deprecated).
Closes 
[PR docs]:
=> Update codecov GHA to v3

setuptools/command/build.py
Simply correcting some grammar/typos in the docstring for `command/build/.py:SubCommand`.
[PR docs]:
=> Typo corrections

docs/userguide/development_mode.rst
Small typo fix in `docs/userguide/development_mode.rst` ("continuous" -> "continuously") 
[PR docs]:
=> Fix typo in docs/userguide/development_mode.rst

.github/workflows/main.yml
=> Report coverage from Cygwin jobs

docs/conf.py, docs/deprecated/distutils-legacy.rst
The Github Actions job for the docs has been failing: https://github.com/pypa/setuptools/actions/runs/3860994927/jobs/6581689871
- Ignore problems inherited from bundled distutils docs
- Replace missing ref.
[PR docs]:
=> CI: Attempt to fix build for docs

docs/deprecated/distutils-legacy.rst
=> [Docs] Add migration for `distutils.core.Command`

changelog.d/3827.misc.rst, pkg_resources/__init__.py
=> Make clear which package is calling `pkg_resources.declare_namespaces`

changelog.d/3820.misc.rst, setuptools/_distutils/ccompiler.py, setuptools/_distutils/tests/test_ccompiler.py
- distutils.ccompiler.CCompiler.has_function: Quote #include argument
- Update changelog.
Closes 
[PR docs]:
=> Merge with distutils@4435cec3

changelog.d/3838.misc.rst, setuptools/config/_validate_pyproject/fastjsonschema_validations.py
- Improve error messages when validating `pyproject.toml` files.
(this follows the methodology introduced in `fastjsonschema==2.16.3`).
Closes 
[PR docs]:
=> Improve error messages for pyproject.toml validation

changelog.d/3902.misc.rst, setuptools/command/easy_install.py, setuptools/config/setupcfg.py, setuptools/package_index.py
Fix #3901
Fix #3879
[PR docs]:
=> Fix URLs in warnings and logs

setuptools/tests/test_virtualenv.py, tox.ini
- Fix tests with pip for Python 3.12 (requires pip>=23.1.2, `https://github.com/pypa/pip/issues/11501`)
- Temporarily disable deprecation enforcement (until deprecated code is removed #3948)
Closes 
[PR docs]:
=> Fix failing tests

newsfragments/3525.feature.rst, setuptools/command/install_scripts.py
=> Remove code reliant on bdist_wininst

docs/deprecated/zip_safe.rst
=> Fix a sentence (minor change)

docs/userguide/pyproject_config.rst
=> Typo fix pyproject_config.rst

docs/userguide/datafiles.rst, docs/userguide/package_discovery.rst, docs/userguide/pyproject_config.rst, docs/userguide/quickstart.rst, newsfragments/3962.feature.rst, pytest.ini, setuptools/config/pyprojecttoml.py
- Remove *beta* status for configurations coming from `[tool.setuptools]` in `pyproject.toml`.
Closes 
[PR docs]:
=> Promote `pyproject.toml`'s `tool.setuptools` out of beta.

MANIFEST.in
=> Exclude `__pycache__` and cache files in `MANIFEST.in`

docs/userguide/development_mode.rst, setuptools/build_meta.py, setuptools/config/_validate_pyproject/formats.py, setuptools/tests/test_virtualenv.py
Just fix typos reported by [codespell](https://github.com/codespell-project/codespell).
[PR docs]:
=> Fix a couple typos found by codespell

docs/userguide/quickstart.rst
Simple non-coding change
Updating of quickstart documentation to reflect valid imports
=> Fix import statement on quickstart guide

tox.ini
Let's disable this temporarily for now, so we don't have surprises if we need quick fixes during the holiday season...
[PR docs]:
=> Temporarily disable deprecation enforcement

.github/workflows/ci-sage.yml
=> CI: Update ci-sage.yml after move of Sage development to GitHub

README.rst
=> Remove broken link in README to inexistent page in PyPUG

pkg_resources/__init__.py, pkg_resources/tests/test_pkg_resources.py, setuptools/build_meta.py, setuptools/command/build_ext.py, setuptools/command/build_py.py, setuptools/command/editable_wheel.py, setuptools/command/egg_info.py, setuptools/command/sdist.py, setuptools/command/test.py, setuptools/config/_validate_pyproject/error_reporting.py, setuptools/config/setupcfg.py, setuptools/monkey.py, setuptools/tests/config/test_setupcfg.py, setuptools/tests/test_build_meta.py, setuptools/tests/test_easy_install.py, setuptools/tests/test_msvc14.py, setuptools/tests/test_sdist.py, setuptools/tests/test_setuptools.py, tools/build_launchers.py
Fix [refurb issues](https://github.com/dosisod/refurb) reported by [ruff](https://docs.astral.sh/ruff/rules/#refurb-furb) 0.1.9.
Closes 
[PR docs]:
=> Fix a couple refurb warnings

.github/workflows/ci-sage.yml
Repair the currently failing GH Actions workflow `.github/workflows/ci-sage.yml`.
=> CI: Update .github/workflows/ci-sage.yml for downstream changes

docs/userguide/dependency_management.rst
A small addition of  the word "to" to improve the grammar of the sentence.
=> doc: small grammar fix to dependency management user guide

newsfragments/4260.misc.rst, pkg_resources/__init__.py
Extracted from https://github.com/pypa/setuptools/pull/4242/files#r1513644506
[PR docs]:
=> `pkg_resources`: Remove unused and shadowed variables

newsfragments/4263.misc.rst, pkg_resources/tests/test_pkg_resources.py
Follow up on #4261. Same style of changes but for `pkg_resources/tests`.
Closes 
[PR docs]:
=> Attempt on improving encoding in pkg_resources.tests

.github/workflows/main.yml
Update cache action to v4
[PR docs]:
=> Update cache action to v4

.github/workflows/main.yml
Update checkout action to v4
[PR docs]:
=> Update checkout action to v4

setuptools/build_meta.py
=> Typo fix in build_meta.py docstring

newsfragments/4136.bugfix.rst, setuptools/command/install.py
Fixes #4136
Closes 
[PR docs]:
=> Use super in commands.install

pkg_resources/__init__.py
Reference https://github.com/pypa/setuptools/pull/4389/files#r1612103499
Closes 
[PR docs]:
=> Fix mypy error for unnecessary quotes

pkg_resources/__init__.py, setuptools/build_meta.py, setuptools/command/install_lib.py, setuptools/command/install_scripts.py, setuptools/config/expand.py
Staying updated with Typeshed for #2345 
There's a bunch of small changes that could be done to support `StrPath` in more places, but this PR is only meant to update annotations to work as-is.
[PR docs]:
=> Merge "Relax path related params" from typeshed

newsfragments/4434.bugfix.rst, setuptools/_core_metadata.py
Improve implementation of #3593
[PR docs]:
=> Improve support for PEP 625 - bugfix for versions like '1.0-2'

setuptools/msvc.py, setuptools/package_index.py
```
RET502 Do not implicitly `return None` in function able to return non-`None` value
RET503 Missing explicit `return` at the end of function able to return non-`None` value
```
[PR docs]:
=> Apply assorted ruff/flake8-return rules (RET)

docs/userguide/declarative_config.rst
Closes #1260
Closes 
[PR docs]:
=> Add a section on interpolation.

newsfragments/+4571b0f4.bugfix.rst, setuptools/_distutils/sysconfig.py, setuptools/_distutils/tests/test_mingwccompiler.py
Closes pypa/distutils#268
[PR docs]:
=> Merge with distutils@34f9518ef

MANIFEST.in, newsfragments/4480.bugfix.rst, setuptools/tests/test_setuptools.py
- **Add a failing test covering the missed expectation.**
- **Include all vendored files in the sdist.**
Closes #4480
[PR docs]:
=> Include all vendored metadata

docs/userguide/dependency_management.rst
=> Add guidance on pinning the upper bound in build-system.requires.

docs/userguide/dependency_management.rst
=> [Docs] Minor grammar fix in dependency_management.rst

docs/userguide/package_discovery.rst
=> Fix example code in documentation

pkg_resources/__init__.py
Removes a TODO in `pkg_resources`
[PR docs]:
=> `pkg_resources`: use `_typeshed.importlib.LoaderProtocol`

newsfragments/4598.feature.rst, pkg_resources/__init__.py
As title says, removes a TODO and file-scoped mypy ignore
[PR docs]:
=> `pkg_resources` fully type all collection attributes

.coveragerc
See https://github.com/pypa/setuptools/discussions/4588#discussioncomment-10416891
[PR docs]:
=> disable coverage for integration tests

docs/conf.py
Included in #4604, but here's a tiny PR to run autofixes on the last skeleton merge.
[PR docs]:
=> Run Ruff (fix CI)

pkg_resources/__init__.py
Fixes error in CI: https://github.com/pypa/setuptools/actions/runs/11441691348/job/31830326138#step:9:68
[PR docs]:
=> Remove unused `type: ignore`

setuptools/config/setupcfg.py
Adopt f-strings and dict-comprehensions.
[PR docs]:
=> Modernise some syntax in `setupcfg.py`

docs/userguide/miscellaneous.rst
Closes #4713.
Closes 
[PR docs]:
=> Mention that type-stubs need to be contained in a package directory.

.github/workflows/main.yml
Workaround for recent errors in CI, possibly caused by actions/setup-python#981.
Closes #4768
[PR docs]:
=> [CI] Workaround for `actions/setup-python#981`

setuptools/tests/test_build_ext.py
Leftover link from https://github.com/pypa/setuptools/pull/4599/files#diff-19b6ed43e0708223cda0de9aed6071f1e0f04aab82e6610ba23e7257326f2a04R186 to closed issue
[PR docs]:
=> Remove link to jaraco/path#232

.readthedocs.yaml
=> Fix new mandatory configuration for RTD

.github/workflows/main.yml
See https://github.com/actions/setup-python/issues/981#issuecomment-2581805373
[PR docs]:
=> Change workaround for GHA failure in 'macos-latest' with 3.9

.github/workflows/main.yml
=> [CI] Attempt to solve problems with `cygwin` in the CI

docs/userguide/pyproject_config.rst
https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-files
=> Update link in userguide

NEWS.rst
Fix version typo in `NEWS.rst`
- ~~[ ] Changes have tests~~
- ~~[ ] News fragment added in [`newsfragments/`].~~
[PR docs]:
=> Fix version typo in NEWS.rst

NEWS.rst
=> Fix docs syntax issue in CI.

docs/userguide/pyproject_config.rst, newsfragments/4904.misc.rst, setuptools/config/_apply_pyprojecttoml.py
=> Document version of setuptools introducing support for PEP 639

NEWS.rst
Fix a broken link to a distutils PR.
=> Fix broken link

pytest.ini
Workaround discussed in https://github.com/pypa/setuptools/pull/5042#issuecomment-2981138461
[PR docs]:
=> Attempt to ignore coverage warnings preventing CI to run on cygwin 
